### PR TITLE
ConformanceStatement generation for DSTU3 is out of date

### LINKED ISSUE #3736: ConformanceStatement generation for DSTU3 is out of date
The code that generates the ConformanceStatement for DSTU3 has suffered a few regressions.

- The list of search parameters for a resource does not include system parameters such as `_id` and `_lastUpdated`
- The `searchInclude` and `searchRevInclude` lists are not being populated

These problems have already been fixed for R4 and later versions, so those fixes can be copied over more or less verbatim.

### PR DESCRIPTION
**Pull request by JasonRoberts-smile**
* modify conformance provider to include `_include` and `_revinclude` portions. 

closes #3736

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/dstu3/JpaConformanceProviderDstu3.java [hunk 1]
```diff
@@ -175,6 +188,77 @@ public CapabilityStatement getServerConformance(HttpServletRequest theRequest, R
...
+		// Borrowed from hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/provider/ServerCapabilityStatementProvider.java
+
+
+		/*
+		 * If we have an explicit registry (which will be the case in the JPA server) we use it as priority,
+		 * but also fill in any gaps using params from the server itself. This makes sure we include
+		 * global params like _lastUpdated
+		 */
+		ResourceSearchParams searchParams;
+		ResourceSearchParams serverConfigurationActiveSearchParams = myServerConfiguration.getActiveSearchParams(theResourceName);
```
Comment (fil512) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/dstu3/JpaConformanceProviderDstu3.java:201]: How does R4 work without this code?

Comment (fil512) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/dstu3/JpaConformanceProviderDstu3.java:201]: If it does exist elsewhere, suggest consolidating rather than copy/paste

File: hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/dstu3/ResourceProviderDstu3BundleTest.java [hunk 2]
```diff
@@ -32,8 +43,25 @@ public void testProcessMessage() {
...
 			assertThat(e.getMessage(), containsString("This operation is not yet implemented on this server"));
 		}
-
 	}
 
+	@Test
+	public void testConformanceContainsIncludesAndRevIncludes() {
+		CapabilityStatement execute = ourClient.capabilities().ofType(CapabilityStatement.class).execute();
+		Optional<CapabilityStatement.CapabilityStatementRestResourceComponent> patient = execute.getRestFirstRep().getResource().stream().filter(resource -> resource.getType().equalsIgnoreCase("Patient")).findFirst();
+		if (patient.isEmpty()) {
```
Comment (fil512) [inline hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/dstu3/ResourceProviderDstu3BundleTest.java:52]: I don't understand how a @Test can have an if statement

**Review by fil512 — APPROVED** [review]

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/dstu3/JpaConformanceProviderDstu3.java (hunk 1 above)
Comment (tadgh) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/dstu3/JpaConformanceProviderDstu3.java:201]: Yeah the overall shape of conformance is pretty different on the jump from DSTU3 -> R4, looks like we tore out the whole thing in R4 and wrote it using the terser. It would be a very heavy lift to backport that to work with DSTU3, so I'm just adding the piecemeal requirements to the STU3 provider instead.

File: hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/dstu3/ResourceProviderDstu3BundleTest.java (hunk 2 above)
Comment (tadgh) [reply hapi-fhir-jpaserver-test-utilities/src/test/java/ca/uhn/fhir/jpa/provider/dstu3/ResourceProviderDstu3BundleTest.java:52]: It just returns an optional, so i wanted to validate it, but can happily ignore it and raw get on the optional.
