### PR TITLE
Fix NPE in ReadPartitionIdRequestDetails.forGeneric for system requests

### LINKED ISSUE #7681: NullPointerException in PatientIdPartitionInterceptor when REST operation type is null
When ReadPartitionIdRequestDetails.forGeneric() is called with a SystemRequestDetails (e.g. from an internal/programmatic request), getRestOperationType() returns null. Partition interceptors that switch on this value —  such as PatientIdPartitionInterceptor.identifyForRead() — throw a NullPointerException.

### PR DESCRIPTION
**Pull request by another-luis**
SystemRequestDetails has no REST operation type, causing a NullPointerException in partition interceptors that switch on that value. Default to EXTENDED_OPERATION_SERVER for requests with no operation type.

Fixes #7681

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/interceptor/model/ReadPartitionIdRequestDetails.java [hunk 1]
```diff
@@ -69,14 +69,15 @@ private ReadPartitionIdRequestDetails(
 	}
 
 	public static ReadPartitionIdRequestDetails forGeneric(RequestDetails theRequestDetails) {
+		RestOperationTypeEnum operationType = theRequestDetails.getRestOperationType();
+		if (operationType == null) {
+			// Programmatic/internal requests (e.g. SystemRequestDetails, CamelExchangeRequestDetails)
+			// have no HTTP context and therefore no REST operation type. Default to a server-level
+			// operation so partition interceptors can route them correctly without NPEs.
+			operationType = RestOperationTypeEnum.EXTENDED_OPERATION_SERVER;
```
Comment (fil512) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/interceptor/model/ReadPartitionIdRequestDetails.java]: This doesn't look right to me. EXTENDED_OPERATION_SERVER is a special type of request where an operation name would expect to be present.

Comment (fil512) [reply hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/interceptor/model/ReadPartitionIdRequestDetails.java]: A more appropriate fix for this specific NPE would be to set the operation name to `mdm-link-history` and  type to EXTENDED_OPERATION_SERVER upstream where the call is actually made. It will run the risk of other NPEs existing in the code, but we'll want to fix those one at a time so READ vs CREATE are handled by the partition interceptor properly.

Comment (another-luis) [reply hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/interceptor/model/ReadPartitionIdRequestDetails.java]: Done

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_8_0/7681-fix-npe-in-patient-id-partition-interceptor-for-system-requests.yaml [hunk 2]
```diff
@@ -0,0 +1,4 @@
+---
+type: fix
+issue: 7681
+title: "Programmatic/Internal system requests (e.g. those triggered by MDM operations) may cause errors under certain partition scenarios. This has been fixed."
```
Comment (codeforgreen) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_8_0/7681-fix-npe-in-patient-id-partition-interceptor-for-system-requests.yaml]: The message itself is a little generic. Can we say more about what the problem is? Along the lines of operation type not being populated.

Comment (another-luis) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_8_0/7681-fix-npe-in-patient-id-partition-interceptor-for-system-requests.yaml]: Done. Also moved the changelog entry to its proper location.

File: hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptorTest.java [hunk 3]
```diff
@@ -146,6 +147,15 @@ void testHistoryInstance_Patient_ResolvesPartition() {
...
 	}
 
+	@Test
+	// Generated by claude-sonnet-4-6
+	void testIdentifyForRead_NullRestOperationType_ThrowsIllegalArgumentException() {
+		ReadPartitionIdRequestDetails readDetails = ReadPartitionIdRequestDetails.forGeneric(new SystemRequestDetails());
+
+		assertThatThrownBy(() -> mySvc.identifyForRead(readDetails, new SystemRequestDetails()))
+				.isInstanceOf(NullPointerException.class);
+	}
```
Comment (tadgh) [inline hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptorTest.java:157]: question: Shouldn't this test _not_ throw an error, after our fix? E.g. doesnt this test now fail that you've fixed the NPE?

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/7681-fix-npe-in-patient-id-partition-interceptor-for-system-requests.yaml [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+type: fix
+issue: 7681
+title: "Programmatic/Internal system requests (e.g. those triggered by MDM operations) may cause errors under certain 
+partition scenarios if the operation type is not populated. This has been fixed."
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/7681-fix-npe-in-patient-id-partition-interceptor-for-system-requests.yaml:5]: issue: Improve precision of the changelog. Which partition scenarios? Specifically PatientIdPartition mode? what else was required to trigger this "error" (also, please specify the error).

File: hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptorTest.java [hunk 5]
```diff
@@ -146,6 +147,15 @@ void testHistoryInstance_Patient_ResolvesPartition() {
 		assertThat(actual.getPartitionIds()).containsExactly(expectedPartitionId);
 	}
 
+	@Test
+	// Generated by claude-sonnet-4-6
+	void testIdentifyForRead_NullRestOperationType_ThrowsIllegalArgumentException() {
```
Comment (tadgh) [inline hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptorTest.java:152]: issue: test name is incorrect for the behaviour defined in it.

File: hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptorTest.java (hunk 3 above)
Comment (another-luis) [reply hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptorTest.java:157]: This is a negative test. It expects to get an NPE if the operation type is null by the time it gets to PatientIdPartitionInterceptor, caught via the Validate statement I added (see below). The test is sending an empty SystemRequestDetails, so the NPE is expected.

`
Validate.notNull(
				theReadDetails.getRestOperationType(),
				"REST operation type must be set on RequestDetails before invoking partition identification.");
`

File: hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptorTest.java (hunk 5 above)
Comment (another-luis) [reply hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptorTest.java:152]: Agreed.
