### PR TITLE
5198 fixing searching everything op

### LINKED ISSUE #5198: Patient/$everything operation returns empty pages if _count parameter is equal to max page size
Reproduction:
Create > MAX_PAGE_SIZE patient resources without any owning resources
- max page size default is 50, so > 50
Request a /Patient/$everything operation (everything type-patient operation)

Ensure all pages of results are returned.

### PR DESCRIPTION
**Pull request by TipzCM**
closes #5198

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 1]
```diff
@@ -178,7 +178,17 @@ public class SearchBuilder implements ISearchBuilder<JpaPid> {
 	@PersistenceContext(type = PersistenceContextType.TRANSACTION)
 	protected EntityManager myEntityManager;
 
+	/**
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:181]: I love this javadoc!  Thank you!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 2]
```diff
@@ -1967,18 +1994,23 @@ private void fetchNext() {
 						}
 					}
 
-					// assigns the results iterator
+					/*
+					 * assigns the results iterator.
+					 * Can also assign and populate myAlsoIncludePids.
+					 * Specifically in type/$everything mode
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:2000]: Very nice.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java [hunk 3]
```diff
@@ -382,6 +382,31 @@ private void saveUnsynced(final IResultIterator theResultIter) {
...
+		if (myMaxResultsToFetch != null && totalFetched < myMaxResultsToFetch) {
+			// total fetched < max results to fetch -> we've exhausted the search
+			return true;
+		} else {
+			if (nonSkippedCount == 0) {
+				// no skipped resources in this query
+				if (myParams.getCount() != null) {
+					// count supplied
+					// if the count is > what we've fetched -> we've exhausted the query
+					return myParams.getCount() > totalFetched;
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:399]: question:  I don't get what page-size has to do with exhausting the query?  I think if myMaxResultsToFetch is null, then running out of results means we are done.  No?  Or are there two copies of myMaxResultsToFetch floating around?

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java [hunk 4]
```diff
@@ -573,12 +573,22 @@ private void doSearch() {
...
 		if (myParams.getCount() != null) {
-			minWanted = myParams.getCount() + 1; // Always fetch one past this page, so we know if there is a next page.
-			minWanted = Math.min(minWanted, myPagingProvider.getMaximumPageSize());
+			// we want either the max page size or the requested count size
+			// (+1 iff count == max page size)
+			minWanted = Math.min(myParams.getCount(), myPagingProvider.getMaximumPageSize());
+			// Always fetch one past this page size, so we know if there is a next page.
+			if (minWanted == myParams.getCount()) {
+				minWanted += 1;
+			}
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:587]: I don't think this is right.  I think we want +1 for both cases.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java [hunk 5]
```diff
@@ -678,4 +689,37 @@ private void doSearch() {
 			throw new InternalErrorException(Msg.code(1166) + e);
 		}
 	}
+
+	/**
+	 * Does the query but only for the count.
+	 * @param myParamWantOnlyCount - if count query is wanted only
+	 */
+	private void doCountOnlyQuery(boolean myParamWantOnlyCount) {
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:697]: problem: shadowing a field name.  Why bother passing the param since it is a field, and we use other members?

```suggestion
	private void doCountOnlyQuery(boolean theParamWantOnlyCount) {
```

**Review by michaelabuckley — COMMENTED** [review]
I'm not sure about your new `isFinished()`, but that is the right code to be working in.  I think we need to be clearer about the bookkeeping.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java (hunk 4 above)
Comment (TipzCM) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:587]: updated

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 6]
```diff
@@ -1925,11 +1924,28 @@ private final class QueryIterator extends BaseIterator<JpaPid> implements IResul
...
+		/**
+		 * The count of resources found in the cached search
+		 */
 		private int mySkipCount = 0;
+		/**
+		 * The count of resources that are new in this search
+		 * (ie, not cached in previous searches)
+		 */
 		private int myNonSkipCount = 0;
+
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:1948]:
```suggestion
		/**
		 * The list of queries to use to find all results.
		 * Normal JPA queries will normally have a single entry.
		 * Queries that involve Hibernate Search/Elasticsearch may have multiple queries because of chunking.
		 * The $everything operation also jams some extra results in.
		 */
```

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4SearchOptimizedTest.java [hunk 7]
```diff
@@ -649,14 +649,14 @@ public void testFetchSecondBatchInManyThreads() throws Throwable {
 		 */
 
 		waitForSize(
-			20,
+			21,
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4SearchOptimizedTest.java:652]: These little +1 changes are a pain, but they reassure me we really are fetching more.

**Review by michaelabuckley — APPROVED** [review]
Approved.  Made some javadoc suggestions

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 8]
```diff
@@ -1925,11 +1924,28 @@ private final class QueryIterator extends BaseIterator<JpaPid> implements IResul
...
 		private IncludesIterator myIncludesIterator;
+		/**
+		 * The next JpaPid value of the next result in this query.
+		 * Will not be null if fetched using getNext()
+		 */
 		private JpaPid myNext;
+		/**
+		 * ResultsIterator is the QueryExecutor that runs the sql
+		 * and fetches data from the db.
+		 */
```
[the remark this answers is not in the document]
Comment (TipzCM) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:1935]: updated

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 9]
```diff
@@ -1925,11 +1924,28 @@ private final class QueryIterator extends BaseIterator<JpaPid> implements IResul
...
 		private ISearchQueryExecutor myResultsIterator;
+
 		private boolean myFetchIncludesForEverythingOperation;
+		/**
+		 * The count of resources found in the cached search
```
[the remark this answers is not in the document]
Comment (TipzCM) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:1940]: updated

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java (hunk 6 above)
Comment (TipzCM) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:1948]: added

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 10]
```diff
@@ -1967,109 +1983,102 @@ private void fetchNext() {
...
+									message.setMessage(msg);
+									HookParams params = new HookParams()
+											.add(RequestDetails.class, myRequest)
+											.addIfMatchesType(ServletRequestDetails.class, myRequest)
+											.add(StorageProcessingMessage.class, message);
+									CompositeInterceptorBroadcaster.doCallHooks(
+											myInterceptorBroadcaster,
+											myRequest,
+											Pointcut.JPA_PERFTRACE_WARNING,
+											params);
```
[the remark this answers is not in the document]
Comment (TipzCM) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:2049]: done
