### PR TITLE
Fix chained searches with count never completes

### LINKED ISSUE #6849: FHIR chain search never finishes with count parameter
**Describe the bug**
Under certain conditions, a FHIR chained search may never finish when combined with the `_count` parameter.

The following conditions must be true: 
- The search result must have multiple pages
- The resulting resources in the search must have some resources with multiple references, and some resources with single references
- The search must be a chained search (search for reference parameters within a resource)
- deduplicateInDatabase must be FALSE 
    - This means the appropriate pre-fetch threshold CANNOT be -1
    - Fewer results were requested from the DB (maxResultsRequested) than the max pre-fetch threshold number 
- `_count` must equal number of resources with multiple references
- The total number of references in resources that should be returned by the search >= the appropriate pre-fetch threshold

**To Reproduce**
1. Start with default configuration 
2. POST this bundle: [testdata.json](https://github.com/user-attachments/files/19640413/testdata.json)
    a. This bundle contains
        i.  10 Encounters that reference 2 Locations
        ii. 2 Encounters that reference 1 Location
        iii. The 2 Locations that are being referenced
    b. The appropriate threshold will be 13 (since the search we will do will return the 12 Encounters) 
    c. Total number of references = (2 Locations * 10 Encounters) + (2 Encounters * 1 Location) = 22 > appropriate (default) threshold of 13
3. Do FHIR Search: `/Encounter?location.status=active&_count=10`
4. Get next page of search with the next link
5. Observe that the search will now timeout and never complete

**Expected behavior**
The search should complete, and return the 2 remaining Encounters 

**Environment (please complete the following information):**
 - HAPI FHIR Version: Latest (8.1.3-SNAPSHOT)

### PR DESCRIPTION
**Pull request by jdar8**
**What was done:**
- Ensure `myMaxResultsToFetch` (used to decide if a search is finished) actually reflects the max results requested from the search
- Add tests/changelog
- Fix various typos
- 3 existing tests were changed
    -  2 tests in `ConsentEventsDaoR4Test` - had incorrect assertions for number of times Pre-Access interceptor was called (see old comment left from dev when test was written)
    - 1 test in `FhirResourceDaoR4SearchOptimizedTest` - since my fix now causes searches to be marked as finished once all matching resources are found, attempting to load the next batch (where 0 match) will no longer cause the search to continue
- Small fix to remove TODO from a previous ticket that was done to avoid version bump

Closes #6849

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

**Comment by robogary** [comment]
**This Pull Request has failed the formatting check**

Please run `mvn spotless:apply` or `mvn clean install -DskipTests` to fix the formatting issues. 

You can automate this auto-formatting process to execute on the git pre-push hook, by installing [pre-commit](https://pre-commit.com/) and then calling `pre-commit install --hook-type pre-push`. This will cause formatting to run automatically whenever you push.

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java [hunk 1]
```diff
@@ -119,6 +119,7 @@ public class SearchTask implements Callable<Void> {
 	private int myCountBlockedThisPass = 0;
 	private boolean myAdditionalPrefetchThresholdsRemaining;
 	private List<JpaPid> myPreviouslyAddedResourcePids;
+	// The max number of results that we request from the search
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:122]: question: who is we? the original requestor's _count parameter? the MAXIMUM_FETCH_SIZE configured on the server settings? What is the provenance of this value?

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java [hunk 2]
```diff
@@ -664,7 +670,131 @@ public void testSearchLinksWorkWithIncludes() {
...
+				assertThat(output.getEntry()).hasSize(count);
+			} else {
+				int numLeft = totalNumberOfPatientsCreated % count;
+				numLeft = numLeft == 0 ? count : numLeft;
+				assertThat(output.getEntry()).hasSize(numLeft);
+			}
+		}
+	}
+
+	private List<String> getLogMessagesOfType() {
```
Comment (tadgh) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java:742]: issue: this method name indicates it should take a type parameter, yet it does not

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/config/JpaStorageSettings.java [hunk 3]
```diff
@@ -137,6 +137,8 @@ public class JpaStorageSettings extends StorageSettings {
 	public static final int DEFAULT_TRANSACTION_ENTRIES_FOR_WRITE =
 			Integer.parseInt(DEFAULT_TRANSACTION_ENTRIES_FOR_WRITE_STRING);
 
+	public static final List<Integer> DEFAULT_SEARCH_PRE_FETCH_THRESHOLDS = Arrays.asList(13, 503, 2003, 1000003, -1);
```
Comment (tadgh) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/api/config/JpaStorageSettings.java:140]: suggestion: Also submit an MR to jpaserver-starter, which hardcodes this value in application.yml if i recall.

**Review by tadgh — COMMENTED** [review]
I gotta say this one has me stumped. What is the actual _fix_ here? Maybe I'm blind but I don't see how this patches the problem. Is there a missing file, or am I glossing over something critical?

**Review by tadgh — APPROVED** [review]

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java (hunk 1 above)
Comment (jdar8) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:122]: It depends:

The maximum of 
- The server-chosen pre-fetch threshold (which appears to be hard-coded, not configurable by the user atm). This depends on how many resources we have already loaded as part of earlier pages in the search.
- The minimum of 
    - The `_count` parameter
    - The configured maximum page size (in the Paging Provider settings)

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java (hunk 2 above)
Comment (jdar8) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java:742]: Oops, it originally did. Forgot to rename the method. 
Fixed

**Comment by jdar8** [comment]
>What is the actual fix here? Maybe I'm blind but I don't see how this patches the problem. Is there a missing file, or am I glossing over something critical?

@tadgh [This is the actual fix](https://github.com/hapifhir/hapi-fhir/pull/6852/files#diff-7c6aa85ac434596b74fd42bd81ac12980cefdbd7bd123576f6e50a5de39aa805R609). 
In summary, ensuring that the `myMaxResultsToFetch` stores the actual value that we submit to the search builder (notice the "+1" to know if there are more than what the requestor wants)

Later on, [in isFinished()](https://github.com/hapifhir/hapi-fhir/pull/6852/files#diff-7c6aa85ac434596b74fd42bd81ac12980cefdbd7bd123576f6e50a5de39aa805R394)
```
if (myMaxResultsToFetch != null && totalFetched < myMaxResultsToFetch) {
	// total fetched < max results to fetch -> we've exhausted the search
	return true;
}
```
we use `myMaxResultsToFetch` as one possible condition to check if the search is finished.

**Comment by tadgh** [comment]
> > What is the actual fix here? Maybe I'm blind but I don't see how this patches the problem. Is there a missing file, or am I glossing over something critical?
> 
> @tadgh [This is the actual fix](https://github.com/hapifhir/hapi-fhir/pull/6852/files#diff-7c6aa85ac434596b74fd42bd81ac12980cefdbd7bd123576f6e50a5de39aa805R609). In summary, ensuring that the `myMaxResultsToFetch` stores the actual value that we submit to the search builder (notice the "+1" to know if there are more than what the requestor wants)
> 
> Later on, [in isFinished()](https://github.com/hapifhir/hapi-fhir/pull/6852/files#diff-7c6aa85ac434596b74fd42bd81ac12980cefdbd7bd123576f6e50a5de39aa805R394)
> 
> ```
> if (myMaxResultsToFetch != null && totalFetched < myMaxResultsToFetch) {
> 	// total fetched < max results to fetch -> we've exhausted the search
> 	return true;
> }
> ```
> 
> we use `myMaxResultsToFetch` as one possible condition to check if the search is finished.
> 
> This used to evaluate to false, since we asked the search to do `myMaxResultsToFetch + 1` and the search actually returned a totalFetched == `myMaxResultsToFetch`.

Ahhhh this makes so much sense, i was indeed missing the fact that we were modifying a member variable that is _not_ local scoped. Thanks for informing me.

**Comment by robogary** [comment]
Formatting check succeeded!

**Comment by robogary** [comment]
Formatting check succeeded!
