### PR TITLE
2958 Fix for consistent error handling

### LINKED ISSUE #2958: Request for consistent error handling
Issue:

Calling ` http://localhost:8000/Procedure?patient=` returns different results.

Steps to reproduce the error: 

1. Call ` http://localhost:8000/Procedure`
2. Immediately follow the call with ` http://localhost:8000/Procedure?patient= `
    This results in `/Procedure?patient=` to return 200 with the same response body as `/Procedure`.
3. Wait a couple of minutes, call ` http://localhost:8000/Procedure?patient= `
    Results in 500 response

The assumed correct response for `/Procedure?patient=`:

This call will result in a 500 response:
` http://localhost:8000/Procedure?patient=`

```
{
    "resourceType": "OperationOutcome",
    "issue": [ {
        "severity": "error",
        "code": "processing",
        "diagnostics": "The validated expression is false"
    } ]
}
```

### PR DESCRIPTION
**Pull request by jdar8**
This fixes issue #2958 
Closes #2958 

* Fixed issue where the processing of queries like `/Procedure?patient=` after a Search like `/Procedure` would return the cached results of the initial call, despite being invalid. 
* Additionally, ensured that requests like Procedure?patient cause HTTP 400 Bad Request instead of HTTP 500 Internal Error.

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/index/IdHelperService.java [hunk 1]
```diff
@@ -204,7 +205,12 @@ private String toForcedIdToPidKey(@Nonnull RequestPartitionId theRequestPartitio
 	 */
 	@Nonnull
 	public List<ResourcePersistentId> resolveResourcePersistentIdsWithCache(RequestPartitionId theRequestPartitionId, List<IIdType> theIds) {
-		theIds.forEach(id -> Validate.isTrue(id.hasIdPart()));
+		for (IIdType id : theIds) {
+			if (!id.hasIdPart()) {
+				ourLog.error("Illegal Argument during database access");
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/index/IdHelperService.java:210]: This log line no longer needs to exist.

**Review by tadgh — APPROVED** [review]
