### PR TITLE
7390 - Make resource version-before-delete available to subscription interceptor

### LINKED ISSUE #7390: Subscriptions - delivering Delete events with specific criteria fails to match the resource
It works but only when the criteria is ‘Patient?’ and not ‘Patient?identifier=ABC123’

### PR DESCRIPTION
**Pull request by another-luis**
Fixes #7390

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java [hunk 1]
```diff
@@ -1851,6 +1851,7 @@ public enum Pointcut implements IPointcut {
 	STORAGE_PRECOMMIT_RESOURCE_DELETED(
 			void.class,
 			"org.hl7.fhir.instance.model.api.IBaseResource",
```
Comment (tadgh) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java:1853]: question: You indicated that the resource that was deleted "does not have a body" when it gets to the subscription processor. Does this IBaseResource not contain the body?

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_8_0/7390-fix-subscription-not-firing-on-delete-resource.yaml [hunk 2]
```diff
@@ -0,0 +1,4 @@
+---
+type: fix
+issue: 7390
+title: "Subscriptions were not triggering on delete when subscription criteria uses resource attributes. This has been fixed"
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_8_0/7390-fix-subscription-not-firing-on-delete-resource.yaml]:
```suggestion
title: "Subscriptions were not sending `DELETE` events when the criteria used resource attributes, for example `Patient?gender=male`. This has been fixed."
```

File: hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/submit/interceptor/SubscriptionMatcherInterceptor.java [hunk 3]
```diff
@@ -85,8 +86,11 @@ public void resourceCreated(IBaseResource theResource, RequestDetails theRequest
 	}
 
 	@Hook(Pointcut.STORAGE_PRECOMMIT_RESOURCE_DELETED)
-	public void resourceDeleted(IBaseResource theResource, RequestDetails theRequest) {
+	public void resourceDeleted(IBaseResource theResource, RequestDetails theRequest, IIdType previousId) {
 
+		// When matching for deleted resources, we want to match for the version before it was deleted because
+		// the resource version record for the deleted resource doesn't contain a body.
+		theResource.setId(previousId);
```
Comment (tadgh) [inline hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/submit/interceptor/SubscriptionMatcherInterceptor.java:93]: I don't understand how this fix actually corrects the issue. This is just setting the (I assume versioned) ID, onto the IBaseResource. Can you copy-paste me the contents of `theResource` as seen at this point in time?

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java (hunk 1 above)
Comment (another-luis) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java:1853]: The resource has a body while being handled by the hook, but when the ResourceModifiedMessage is created based on resource, the body is dropped by calling getPayloadLessMessageFromString(..). So it will up to the message handler to reconstitute the original resource by using the version included in the message. If the message points to the deleted version of the resource, it will retrieve that one which - in turn - has no body.

Comment (tadgh) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java:1853]: gotcha. so it has no actual clinical information in it. It is literally an empty resource?

File: hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/submit/interceptor/SubscriptionMatcherInterceptor.java (hunk 3 above)
Comment (another-luis) [reply hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/submit/interceptor/SubscriptionMatcherInterceptor.java:93]: The ResourceModifiedMessage is a payloadless message, so only the id survives. When picked up by the message handler, the resource is read from the cache/db. If the version retrieved is the deleted version, it will be bodiless, so the resource fields needed by the matching criteria won't be there. We have to retrieve the version right before it was deleted to "inflate" a resource with all its fields populated so that the matching criteria has a fighting chance. That's why I need to set the version to the one before the resource was deleted.

Take a look at theResource **before** I set the id in the next line. It's pointing to version 2 - the deleted version. If we let it continue, that's going to be in the contents of the ResourceModifiedMessage, and the message handler will inflate that (bodiless) version. I had to break the resource into two images because I can't figure out how to zoom out in the debugging window .

Screenshot 2025-12-11 at 5 03 33 PM

Screenshot 2025-12-11 at 5 04 33 PM

Comment (tadgh) [reply hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/submit/interceptor/SubscriptionMatcherInterceptor.java:93]: Ah I gotcha

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java (hunk 1 above)
Comment (another-luis) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java:1853]: yes
