### PR TITLE
7261: Return 404 when querying the status of a cancelled bulk export

### LINKED ISSUE #7261: Wrong Response Status on cancelled exports
Querying the status of a bulk data export jobs that has been cancelled should return a 404 and not a 202, per the [FHIR spec](https://hl7.org/fhir/uv/bulkdata/STU2/export.html#bulk-data-delete-request)

To reproduce:

1. Start a bulk export
2. Query the job - should return a 202 with information about the job in the header
3. Cancel the bulk export
4. Query the job - should return a 202, but instead returns a 202

### PR DESCRIPTION
**Pull request by another-luis**
Make sure we return a HTTP 404 when a user queries the status of a cancelled bulk export

Fixes #7261 
Fixes Smile [#7880](https://gitlab.com/simpatico.ai/cdr/-/issues/7880)

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/bulk/BulkDataExportProviderR4Test.java [hunk 1]
```diff
@@ -1093,6 +1093,38 @@ public void testDeleteForOperationPollStatus_COMPLETE_ShouldReturnError() throws
...
+			JpaConstants.PARAM_EXPORT_POLL_STATUS_JOB_ID + "=" + A_JOB_ID;
+		HttpDelete delete = new HttpDelete(url);
+		try (CloseableHttpResponse response = myClient.execute(delete)) {
+			ourLog.info("Response: {}", response.toString());
+
+			assertEquals(404, response.getStatusLine().getStatusCode());
+			assertEquals("Not Found", response.getStatusLine().getReasonPhrase());
+
+			String responseContent = IOUtils.toString(response.getEntity().getContent(), Charsets.UTF_8);
+			// content would be blank, since the job is cancelled
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/bulk/BulkDataExportProviderR4Test.java]: Leftover comment?

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7261-return-correct-http-code-when-querying-cancelled-job-status.yaml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+type: fix
+issue: 7261
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7261-return-correct-http-code-when-querying-cancelled-job-status.yaml:3]: add 
```
jira: SMILE-XXXX
```

For robogary traceability

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7261-return-correct-http-code-when-querying-cancelled-job-status.yaml [hunk 3]
```diff
@@ -0,0 +1,5 @@
...
+title: "Querying the status of a cancelled bulk export job was returning a 
+    HTTP 202 instead of a HTTP 404. This has been fixed."
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7261-return-correct-http-code-when-querying-cancelled-job-status.yaml]: suggestion: link to the specific part of the spec that defines this rule. (2.5.4 I believe)

File: hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportProvider.java [hunk 4]
```diff
@@ -493,6 +492,22 @@ public void exportPollStatus(
...
+						outcome,
+						"error",
+						"Job instance <" + theJobId.getValueAsString() + "> was cancelled.  No status to report.",
+						null,
+						null);
+				myFhirContext
+						.newJsonParser()
+						.setPrettyPrint(true)
+						.encodeResourceToWriter(outcome, response.getWriter());
+				response.getWriter().close();
```
Comment (tadgh) [inline hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportProvider.java:509]: nitpick: Double check that there's no additional close further down the line here.

**Review by tadgh — APPROVED** [review]

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7261-return-correct-http-code-when-querying-cancelled-job-status.yaml (hunk 2 above)
Comment (another-luis) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7261-return-correct-http-code-when-querying-cancelled-job-status.yaml:3]: Done

File: hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportProvider.java (hunk 4 above)
Comment (another-luis) [reply hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportProvider.java:509]: Done
