### PR TITLE
6046  text does not work with r5

### LINKED ISSUE #6046: `_text` does not work with R5
Replication setup: 
1. Enable Lucene/ES
2. Enable Fulltext indexing 
3. Setup an R5 Persistence module. 
4. Create a ServiceRequest with a narrative containing `asdf`.
5. Attempt: 
```http_request
GET ServiceRequest?_text=asdf
```

Result: 
```json
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "HAPI-1088: Unsupported full-text param type: class ca.uhn.fhir.rest.param.SpecialParam"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by tadgh**
- Add support for _text and _contains in R5. 
- add concept of `_text:contains` and `_content:contains` to support exact string matching in elasticsearch/lucene. 
- changelogs
- tests. 

Closes #6046

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/search/ExtendedHSearchClauseBuilder.java [hunk 1]
```diff
@@ -229,21 +256,34 @@ public void addStringTextSearch(String theSearchParamName, List<List<IQueryParam
...
-										.AND)); // term value may contain multiple tokens.  Require all of them to be
-				// present.
-			} else {
-				ourLog.warn("No Terms found in query parameter {}", nextOrList);
+		if (isContainsSearch(theSearchParamName, stringAndOrTerms)) {
+			for (List<? extends IQueryParameterType> nextOrList : stringAndOrTerms) {
+				Set<String> orTerms =
+						TermHelper.makePrefixSearchTerm(extractOrStringParams(theSearchParamName, nextOrList));
+				for (String orTerm : orTerms) {
+					myRootClause.must(myRootContext.match().field(fieldName).matching(orTerm));
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/search/ExtendedHSearchClauseBuilder.java:264]: Recommend adding a comment indicating how the match() being used here is different from below

File: hapi-fhir-jpaserver-elastic-test-utilities/src/test/resources/logback-test.xml [hunk 2]
```diff
@@ -9,4 +9,16 @@
 		<appender-ref ref="STDOUT" />
 	</root>
 
+	<logger name="org.hibernate.search.elasticsearch.request" additivity="false" level="trace">
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-elastic-test-utilities/src/test/resources/logback-test.xml]: Should these loggers be commented out or moved up to INFO with a comment indicating how to set to trace for debugging? I assume they're pretty noisy

**Review by jamesagnew — APPROVED** [review]

**Review by jamesagnew — APPROVED** [review]
