### PR TITLE
7282 - Added the ability for an Interceptor to alter the HTTP Response Code when an Exception is thrown

### LINKED ISSUE #7282: Allow A Custom Interceptor To Alter Response HTTP Status Code For Exceptions
During Exception handling, the HAPI-FHIR code in `ca.uhn.fhir.rest.server.interceptor.ExceptionHandlingInterceptor` takes the HTTP Status Code from the original `Exception` and returns it to the caller.

The purpose of this issue is to allow a custom Interceptor being called during the `SERVER_OUTGOING_FAILURE_OPERATIONOUTCOME` Pointcut to modify the HTTP Status Code being returned on the Response.

The Status Code is retrieved from the Exception here:
[hapi-fhir/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptor.java](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptor.java#L89) 

The Interceptor Pointcut `SERVER_OUTGOING_FAILURE_OPERATIONOUTCOME` is called here and does not allow that method to return anything back to the caller (it returns void): 
[hapi-fhir/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptor.java](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptor.java#L112) 

The Pointcut is defined here:
[hapi-fhir/hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java#L618) 

Currently, there is no option to change that original HTTP Status Code and it gets passed back to the caller:
[hapi-fhir/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptor.java](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptor.java#L121)

### PR DESCRIPTION
**Pull request by KevinDougan**
Closes #7282

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java [hunk 1]
```diff
@@ -373,6 +373,12 @@ public static void callOutgoingFailureOperationOutcomeHook(
 			theRequestDetails
 					.getInterceptorBroadcaster()
 					.callHooks(Pointcut.SERVER_OUTGOING_FAILURE_OPERATIONOUTCOME, responseParams);
+			Integer httpResponseCode =
```
Comment (jamesagnew) [inline hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java]: Thought: Relying on a hidden userdata feels clunky to me. Would it make more sense to define an optional response object that can be returned by hook methods implementing the `SERVER_OUTGOING_FAILURE_OPERATIONOUTCOME` pointcut, so that it's super explicit what is going on?

I'm picturing something along the lines of:

```java
public class ServerOutgoingFailureOperationOutcomeResponse {
   private Integer myResponseStatusCode;
   // add getter and setter
}
```

..and if the intercaptor chooses to return this and has populated a status code, we'll use it. This would make the feature fully discoverable.

Comment (KevinDougan) [reply hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java]: @jamesagnew  Thanks for the suggestion. I originally started down the path of adding a "wrapper class" to encapsulate the HttpResponseCode but then decided it would be simpler to just use the Spring HttpStatus class instead. I kept your idea of using an Optional as well. If you get a chance to review these latest changes and you agree with them, please Resolve this Conversation.

Comment (michaelabuckley) [reply hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java]: I would rather this was a modifiable outcome parameter than a return value because non-null return values short circuit the list of interceptors, and that is a breaking change of semantics.

File: hapi-fhir-base/pom.xml [hunk 2]
```diff
@@ -70,6 +70,11 @@
 			<groupId>org.apache.commons</groupId>
 			<artifactId>commons-lang3</artifactId>
 		</dependency>
+		<dependency>
+			<groupId>org.springframework</groupId>
```
Comment (michaelabuckley) [inline hapi-fhir-base/pom.xml]: problem: this is much too big to add to hapi-fhir-base.  This needs to run on Android phones.

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java [hunk 3]
```diff
@@ -612,11 +613,14 @@ public enum Pointcut implements IPointcut {
...
-	 * Hook methods must return <code>void</code>
+	 * Hook methods must return an instance of {@link java.util.Optional} which may contain an enum value from the
+	 * {@link org.springframework.http.HttpStatus} class. An HttpStatus enum result is to be returned from the
+	 * Interceptor implementation whenever the code wishes to change the default Http Response Code and return a
+	 * different response to the caller when an Exception occurs.
 	 * </p>
 	 */
 	SERVER_OUTGOING_FAILURE_OPERATIONOUTCOME(
-			void.class,
+			Optional.class,
```
Comment (michaelabuckley) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java]: problem: this is a breaking change.  Pointcuts that return objects stop processing the list of interceptors on first non-null value.

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java (hunk 1 above)
Comment (KevinDougan) [reply hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java]: I have applied the suggestions to the latest code.

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java [hunk 4]
```diff
@@ -619,7 +624,8 @@ public enum Pointcut implements IPointcut {
 			void.class,
 			"ca.uhn.fhir.rest.api.server.RequestDetails",
 			"ca.uhn.fhir.rest.server.servlet.ServletRequestDetails",
-			"org.hl7.fhir.instance.model.api.IBaseOperationOutcome"),
+			"org.hl7.fhir.instance.model.api.IBaseOperationOutcome",
+			"java.util.concurrent.atomic.AtomicInteger"),
```
Comment (michaelabuckley) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/interceptor/api/Pointcut.java]: problem:  please introduce a concrete class like `OutgoingOutcome` with a getter/setter for a property named statusCode.  The bare AtomicInteger is too mysterious.  While you are at it, consider adding the IBaseOperationOutcome so they can travel together.

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java [hunk 5]
```diff
@@ -362,17 +364,32 @@ public static boolean callOutgoingResponseHook(RequestDetails theRequest, Respon
...
+		// Call hooks if there is an interceptor broadcaster
 		if (theRequestDetails.getInterceptorBroadcaster() != null) {
 			theRequestDetails
 					.getInterceptorBroadcaster()
 					.callHooks(Pointcut.SERVER_OUTGOING_FAILURE_OPERATIONOUTCOME, responseParams);
 		}
+
+		// Retrieve the potentially updated & validated Status Code from the AtomicInteger container OR use the original
+		// value
+		theHttpStatusCode = Optional.ofNullable(HttpStatus.resolve(mutableStatusCode.get()))
```
Comment (michaelabuckley) [inline hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java]: suggestion: if we make the new object hold a bare primitive, you can remove this nullability complexity.

File: hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptorTest.java [hunk 6]
```diff
@@ -102,6 +105,65 @@ public void ExceptionHandlingInterceptor_HandlesFailure_WhenWriting() throws IOE
...
+		String responseContent = IOUtils.toString(status.getEntity().getContent(), Charsets.UTF_8);
+		IOUtils.closeQuietly(status.getEntity().getContent());
+		ourLog.info(responseContent);
+		assertEquals(500, status.getStatusLine().getStatusCode());
+		OperationOutcome oo = (OperationOutcome) ourCtx.newXmlParser().parseResource(responseContent);
+		ourLog.debug(ourCtx.newXmlParser().encodeResourceToString(oo));
+		assertThat(oo.getIssueFirstRep().getDiagnosticsElement().getValue()).contains("Simulated IOException");
+
+		//When: We add an Interceptor which will return an alternate Http Response Code, it gets returned to the caller
+		ourServer.registerInterceptor(alterHttpResponseCodeInterceptorToValid404Value);
```
Comment (michaelabuckley) [inline hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptorTest.java:131]: Nice.

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseHighlighterInterceptor.java [hunk 7]
```diff
@@ -379,14 +380,16 @@ public boolean handleException(
...
+				theRequestDetails, oo, theException);
+
 		streamResponse(
 				theRequestDetails,
 				theServletResponse,
 				responseDetails.getResponseResource(),
 				null,
 				theServletRequest,
-				responseDetails.getResponseCode());
+			outgoingFailureResponse.getStatusCode());
```
Comment (michaelabuckley) [inline hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ResponseHighlighterInterceptor.java]: problem: what if the hook modified the status in ReponseDetails?  That's basically the same class as this new one.

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java [hunk 8]
```diff
@@ -362,17 +365,33 @@ public static boolean callOutgoingResponseHook(RequestDetails theRequest, Respon
...
 			theRequestDetails
 					.getInterceptorBroadcaster()
 					.callHooks(Pointcut.SERVER_OUTGOING_FAILURE_OPERATIONOUTCOME, responseParams);
 		}
+
+		outgoingFailureResponse = responseParams.get(OutgoingFailureResponse.class);
+		int httpStatusCode = Optional.ofNullable(HttpStatus.resolve(outgoingFailureResponse.getStatusCode()))
+			.map(HttpStatus::value)
+			.orElse(theException.getStatusCode());
+		outgoingFailureResponse.setStatusCode(httpStatusCode);
```
Comment (michaelabuckley) [inline hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java]: problem:  delete this.  The hook can only call methods on this object, they can't replace it.  There is nothing to do.
