### PR TITLE
Refactor and fix functionality dealing with ReadPartitionIdRequestDetails

### LINKED ISSUE #5694: PatientIdPartitioningInterceptor produces NullPointerException when ReadPartitionIdRequestDetails is null
There are a couple of places where the `ReadPartitionIdRequestDetails` is being passed as null to `BaseRequestPartitionHelperSvc` method `determineReadPartitionForRequest`. There have already been two invocations fixed in the release branch #5659 and #5680.
1) There are other places such as Bulk Import and MDM. 
2) Consider doing some minimal refactoring to avoid this situation.

### PR DESCRIPTION
**Pull request by codeforgreen**
closes #5694

Summary of changes:
- populate ReadPartitionIdRequestDetails for all invocations of `IRequestPartitionHelperSvc` which involve computing partitionId for read requests (including search, history, mdm related operations and system operations like bulk import/export, reindex). Do not allow this parameter to be passed as null.
- Optimize calling pattern by adding new methods to `IRequestPartitionHelperSvc` such that caller no longer needs to pass null arguments. 
- Add test for bulk import with patientId partitioning and move existing bulk export tests.

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/QueryStack.java
Comment (codeforgreen) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/QueryStack.java:1]: These are just formatting changes for some reason it did not merge correctly with master so I had to bring these in manually.

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java
Comment (codeforgreen) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java:1]: This class contains the main changes which drive the rest of the refactoring changes.

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java [hunk 1]
```diff
@@ -34,22 +34,55 @@ public interface IRequestPartitionHelperSvc {
 
 	@Nonnull
 	RequestPartitionId determineReadPartitionForRequest(
-			@Nullable RequestDetails theRequest, ReadPartitionIdRequestDetails theDetails);
+			@Nonnull RequestDetails theRequest, @Nonnull ReadPartitionIdRequestDetails theDetails);
+
+	@Nonnull
+	default RequestPartitionId determineReadPartitionForRequestForOperation(
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java:40]: This all seems safe enough.

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java [hunk 2]
```diff
@@ -34,22 +34,55 @@ public interface IRequestPartitionHelperSvc {
...
-			String theResourceType,
-			SearchParameterMap theParams,
-			IBaseResource theConditionalOperationTargetOrNull) {
+			@Nonnull RequestDetails theRequest, @Nonnull String theResourceType) {
+		ReadPartitionIdRequestDetails details =
+				ReadPartitionIdRequestDetails.forSearchType(theResourceType, null, null);
+		return determineReadPartitionForRequest(theRequest, details);
+	}
+
+	@Nonnull
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java:70]: Question: I'm not sure I understand the purpose of these overrides.  How should new code choose which to call?  Please add javadoc describing when to chose one or the other.

I wonder if you could have achieved the same goal (null-safe) with better builder methods on ReadPartitionIdRequestDetails?  Replacing the ReadPartitionIdRequestDetails parameter object with multiple similar signatures confuses me.

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java [hunk 3]
```diff
@@ -59,18 +92,17 @@ default RequestPartitionId determineReadPartitionForRequestForSearchType(
 
 	@Nonnull
 	default RequestPartitionId determineReadPartitionForRequestForHistory(
-			RequestDetails theRequest, String theResourceType, IIdType theIdType) {
+			@Nonnull RequestDetails theRequest, String theResourceType, IIdType theIdType) {
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java:95]: It is always good to see more non-null constraints.

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/bulk/BulkExportWithPartitioningTest.java [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+import org.slf4j.LoggerFactory;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.boot.test.mock.mockito.SpyBean;
+
+import java.io.IOException;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertNotNull;
+
+public class BulkExportWithPartitioningTest extends BaseResourceProviderR4Test {
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/bulk/BulkExportWithPartitioningTest.java:27]: suggestion: rename to BulkExportWithPatientIdPartitioningTest

This isn't just partitioning, but patient id mode.

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/bulk/imprt2/BulkImportWithPartitioningTest.java [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+import java.util.concurrent.TimeUnit;
+
+import static org.awaitility.Awaitility.await;
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.blankOrNullString;
+import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.not;
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+public class BulkImportWithPartitioningTest extends BaseJpaR4Test {
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/bulk/imprt2/BulkImportWithPartitioningTest.java:35]: suggestion: same - rename to identify that this is patient id

**Review by michaelabuckley — APPROVED** [review]
This seems careful and safe.

Made a minor suggestion about test name.

I'm not sure about replacing the parameter object pattern with overloaded methods, but at least they are all non-null.  I think this would have been cleaner with overloads or builders on the underlying ReadPartitionIdRequestDetails instead of the service layer.  It shows up in all the mock changes for the new methods names.

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/svc/MdmResourceDaoSvcTest.java [hunk 6]
```diff
@@ -38,6 +39,9 @@ public class MdmResourceDaoSvcTest extends BaseMdmR4Test {
 	@Autowired
 	private ISearchParamExtractor mySearchParamExtractor;
 
+	@SpyBean
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/svc/MdmResourceDaoSvcTest.java:42]: Why is this a spy?  I don't see it inspected in the test

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/interceptor/model/ReadPartitionIdRequestDetails.java [hunk 7]
```diff
@@ -108,18 +108,9 @@ public static ReadPartitionIdRequestDetails forRead(IIdType theId) {
 		return forRead(theId.getResourceType(), theId, false);
 	}
 
-	public static ReadPartitionIdRequestDetails forOperation(
-			@Nullable String theResourceType, @Nullable IIdType theId, @Nonnull String theExtendedOperationName) {
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/interceptor/model/ReadPartitionIdRequestDetails.java:112]: Was this never called with a type or id?

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java (hunk 1 above)
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java:40]:
```suggestion
	default RequestPartitionId determineReadPartitionForRequestForServerOperation(
```

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/packages/JpaPackageCacheTest.java [hunk 8]
```diff
@@ -45,6 +46,9 @@ public class JpaPackageCacheTest extends BaseJpaR4Test {
 	@Autowired
 	private ISearchParamExtractor mySearchParamExtractor;
 
+	@SpyBean
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/packages/JpaPackageCacheTest.java:49]: question: why is this a spy?

File: hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexProviderTest.java [hunk 9]
```diff
@@ -74,7 +74,7 @@ public void beforeEach() {
 
 		when(myJobCoordinator.startInstance(isNotNull(), any()))
 			.thenReturn(createJobStartResponse());
-		when(myRequestPartitionHelperSvc.determineReadPartitionForRequest(any(), any())).thenReturn(RequestPartitionId.allPartitions());
```
Comment (michaelabuckley) [inline hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexProviderTest.java:77]: comment:  This is a consequence of abandoning the parameter object pattern.  But there aren't as many of these changes as I expected.  Interesting.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java [hunk 10]
```diff
@@ -140,16 +132,21 @@ public RequestPartitionId identifyForRead(
 				break;
 			case SEARCH_TYPE:
 				SearchParameterMap params = theReadDetails.getSearchParams();
+				if (params == null || params.isEmpty()) {
```
Comment (michaelabuckley) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java:135]: question: is this break correct?  Please add a comment explaining it.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java [hunk 11]
```diff
@@ -140,16 +132,21 @@ public RequestPartitionId identifyForRead(
...
 				if ("Patient".equals(theReadDetails.getResourceType())) {
 					List<String> idParts = getResourceIdList(params, "_id", "Patient", false);
-
 					if (idParts.size() == 1) {
 						return provideCompartmentMemberInstanceResponse(theRequestDetails, idParts.get(0));
 					} else {
 						return RequestPartitionId.allPartitions();
 					}
 				} else {
+					if (compartmentSps == null) {
```
Comment (michaelabuckley) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java:147]: minor suggestion: consider initializing  compartmentSps to an empty list so you can delete this null check and annotate the var as non-null

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java (hunk 2 above)
Comment (codeforgreen) [reply hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/partition/IRequestPartitionHelperSvc.java:70]: Good point. I may get rid of these. I wanted to make the call pattern simpler and just call `determineReadPartitionForRequest` instead of having to build `ReadPartitionIdRequestDetails` and call `determineReadPartitionForRequest`. Something feels off with that.
If I read logic in `determineReadPartitionForRequest` and in other places such as `PatientIdPartitionInterceptor` `identifyForRead` it seems as if we're at first trying to converge the behaviour and then split it again depending on the context. So I think this requires more careful thought and maybe a slight re-design to make it more robust. This is my honest opinion.

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/svc/MdmResourceDaoSvcTest.java (hunk 6 above)
Comment (codeforgreen) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/svc/MdmResourceDaoSvcTest.java:42]: At first I had an assertion but removed it as I didn't need it. I then noticed the injection didn't work in the test. I'll have to figure it out as I do want to inject it.

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/packages/JpaPackageCacheTest.java (hunk 8 above)
Comment (codeforgreen) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/packages/JpaPackageCacheTest.java:49]: Same answer https://github.com/hapifhir/hapi-fhir/pull/5691#discussion_r1490203388

File: hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexProviderTest.java (hunk 9 above)
Comment (codeforgreen) [reply hapi-fhir-storage-batch2-jobs/src/test/java/ca/uhn/fhir/batch2/jobs/reindex/ReindexProviderTest.java:77]: Yes it is. Only couple of places used the method with the `ReadPartitionIdRequestDetails` object as parameter. Coming back to the other thread https://github.com/hapifhir/hapi-fhir/pull/5691#discussion_r1490202459. I would go one way or the other and looking at all the usages of `IRequestPartitionHelperSvc` I would vote for keeping my changes.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java (hunk 10 above)
Comment (codeforgreen) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java:135]: There was a compile warning that it can be null. Just because `ReadPartitionIdRequestDetails` accepts null for this parameter. I was trying to prevent a NPE here. If there is any use-case where this happens I can document it.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java (hunk 11 above)
Comment (codeforgreen) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java:147]: I thought it over and over to decide which is better. Yes, I guess that is fine.

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/interceptor/model/ReadPartitionIdRequestDetails.java (hunk 7 above)
Comment (codeforgreen) [reply hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/interceptor/model/ReadPartitionIdRequestDetails.java:112]: Yes, that's right. Those few instances I found for system operations were either not creating this object at all (causing NPE in the PatientId interceptor) or creating it with type and id null and populating just operation name.

File: hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportProvider.java [hunk 12]
```diff
@@ -506,9 +503,6 @@ public void exportPollStatus(
 
 						String serverBase = getServerBase(theRequestDetails);
 
-						// an output is required, even if empty, according to HL7 FHIR IG
```
[the remark this answers is not in the document]
Comment (codeforgreen) [reply hapi-fhir-storage-batch2-jobs/src/main/java/ca/uhn/fhir/batch2/jobs/export/BulkDataExportProvider.java:509]: I don't recall explicitly deleting. Must have been a bad merge. It is the most recent change. I will restore it.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java (hunk 10 above)
Comment (codeforgreen) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java:135]: I went for initializing this to an empty param list and preventing null. There is one occurrence where this happens in MDM match, but I am not sure if that needs to be corrected or not, passing additional conditional resource or search param. So I left as is.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java [hunk 13]
```diff
@@ -132,10 +132,6 @@ public RequestPartitionId identifyForRead(
 				break;
 			case SEARCH_TYPE:
 				SearchParameterMap params = theReadDetails.getSearchParams();
-				if (params == null || params.isEmpty()) {
```
Comment (michaelabuckley) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java]: Problem: we might still need this null check.  the getResourceIdList call below uses params.  Not sure if it is nullable.

Comment (codeforgreen) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/interceptor/PatientIdPartitionInterceptor.java]: I've added an assertion and ensured it will not be null.
