### PR TITLE
Empty/null username and password in ElasticsearchHibernatePropertiesBuilder throws exception, multiple hosts not possible

### LINKED ISSUE #2975: Empty/null username and password in ElasticsearchHibernatePropertiesBuilder throws exception, multiple hosts not possible
When using ElasticsearchHibernatePropertiesBuilder without authentication it throw exception:
```java
Caused by: java.lang.IllegalArgumentException: Username may not be null
	at org.apache.http.util.Args.notNull(Args.java:54) ~[httpcore-4.4.14.jar:4.4.14]
	at org.apache.http.auth.UsernamePasswordCredentials.<init>(UsernamePasswordCredentials.java:81) ~[httpclient-4.5.13.jar:4.5.13]
	at ca.uhn.fhir.jpa.search.lastn.ElasticsearchRestClientFactory.createElasticsearchHighLevelRestClient(ElasticsearchRestClientFactory.java:58) ~[hapi-fhir-jpaserver-base-5.5.1-B3.jar:?]
	at ca.uhn.fhir.jpa.search.elastic.ElasticsearchHibernatePropertiesBuilder.injectStartupTemplate(ElasticsearchHibernatePropertiesBuilder.java:161) ~[hapi-fhir-jpaserver-base-5.5.1-B3.jar:?]
	at ca.uhn.fhir.jpa.search.elastic.ElasticsearchHibernatePropertiesBuilder.apply(ElasticsearchHibernatePropertiesBuilder.java:102) ~[hapi-fhir-jpaserver-base-5.5.1-B3.jar:?]
```

1. Use ElasticsearchHibernatePropertiesBuilder to insert properties (kotlin code):
```kotlin
ElasticsearchHibernatePropertiesBuilder()
        .setRestUrl(hapiFhirProperties.elasticsearch.hosts.joinToString(separator = ",") { it })
        .setProtocol(hapiFhirProperties.elasticsearch.protocol)
        .apply(this)
```
**Expected behavior**
Create a HttpClient without credentials

When using ElasticsearchHibernatePropertiesBuilder with multiple hosts, throws exception.

### PR DESCRIPTION
**Pull request by bratwurzt**
Closes #2975

### CODE REVIEW

**Comment by tadgh** [comment]
This is great! Thanks for the contribution. Couple super minor things: 

1. Can you modify TestR4WithElasticsearchClient.java line 24 to pass in null instead of empty strings, at least then this PR will get exercised by our testing suite. 
2. How would you like to be attributed for this fix? After we merge, I will add a changelog for this fix.  Is @bratwurzt  ok, or if you like, we could put your actual name. Or we can leave off the attribution, your call :)

**Comment by tadgh** [comment]
> Hi @tadgh!
> 
> I found another little bug (doesn't work with comma-separated hosts: localhost:9200,localhost:9201,localhost:9202) so if you don't mind, I'd amend the PR&issue to fix this aswell.
> 
>     1. Will do!
> 
>     2. If it's possible, by my name (Dušan Marković), since I'm doing this in scope of my job (https://www.better.care)

Heya! I didn't realize the elasticsearch high level reset client was even compatible with multiple hosts simultaneously. Learn something new every day I suppose. I would be happy to accept that PR. Let me know when I should have a look at this MR

**Comment by bratwurzt** [comment]
> Let me know when I should have a look at this MR

Hey!

PR is ready, IMO. Not sure about code style/refactoring - I'll fix it upon your feedback after your review.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilder.java [hunk 1]
```diff
@@ -102,20 +100,16 @@ public void apply(Properties theProperties) {
...
 
 	public ElasticsearchHibernatePropertiesBuilder setRequiredIndexStatus(IndexStatus theRequiredIndexStatus) {
 		myRequiredIndexStatus = theRequiredIndexStatus;
 		return this;
 	}
 
-	public ElasticsearchHibernatePropertiesBuilder setRestUrl(String theRestUrl) {
-		if (theRestUrl.contains("://")) {
-			throw new ConfigurationException("Elasticsearch URL cannot include a protocol, that is a separate property. Remove http:// or https:// from this URL.");
-		}
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilder.java:117]: I still think it is valuable to keep this runtime check for protocol included in the hosts, lots of people have been bitten by this in my experience. Thoughts?

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilder.java [hunk 2]
```diff
@@ -150,18 +144,13 @@ public ElasticsearchHibernatePropertiesBuilder setDebugPrettyPrintJsonLog(boolea
 	 * TODO GGG HS: In HS6.1, we should have a native way of performing index settings manipulation at bootstrap time, so this should
 	 * eventually be removed in favour of whatever solution they come up with.
 	 */
-	void injectStartupTemplate(String theProtocol, String theHostAndPort, String theUsername, String thePassword) {
+	void injectStartupTemplate(String protocol, String hosts, @Nullable String username, @Nullable String password) {
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilder.java:147]: The HAPI-FHIR convention is `the` as a prefix for method parameters. The nullable annotations are good though, just gotta revert the names 👍🏻

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/lastn/ElasticsearchRestClientFactory.java [hunk 3]
```diff
@@ -20,52 +20,60 @@
...
 
-	private static String stripHostOfScheme(String theHostname) {
-		int schemeIdx = theHostname.indexOf("://");
-		if (schemeIdx > 0) {
-			return theHostname.substring(schemeIdx + 3);
-		} else {
-			return theHostname;
+		if (hosts.contains("://")) {
+			throw new ConfigurationException("Elasticsearch URLs cannot include a protocol, that is a separate property. Remove http:// or https:// from this URL.");
+		}
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/lastn/ElasticsearchRestClientFactory.java:50]: Ah I see you just moved it, nice :)

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilderTest.java [hunk 4]
```diff
@@ -42,19 +36,42 @@ public void testRestUrlCannotContainProtocol() {
...
+		//SUT
+		try {
+			myPropertiesBuilder
+				.apply(new Properties());
+			fail();
+		} catch (ConfigurationException e ) {
+			assertThat(e.getMessage(), is(equalTo(failureMessage)));
+		}
+	}
+
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilderTest.java:76]: nice test 👍🏻

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/lastn.md [hunk 5]
```diff
@@ -31,12 +31,11 @@ In addition, the Elasticsearch client service, `ElasticsearchSvcImpl` will need
 ```java
   @Bean()
   public ElasticsearchSvcImpl elasticsearchSvc() {
-     String elasticsearchHost = "localhost";
-     String elasticsearchUserId = "elastic";
+     String elasticsearchHost = "localhost:9301";
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/lastn.md:34]: One minor change requested here: could you change `9301` to the default rest port of `9200`? This will help readers who  happen to copy and paste work out of the box.

**Review by tadgh — APPROVED** [review]
Approved, with super minor changes. Thanks for the contribution, this is great!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilder.java (hunk 1 above)
Comment (bratwurzt) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilder.java:117]: I concur, I just moved it to ca.uhn.fhir.jpa.search.lastn.ElasticsearchRestClientFactory#createElasticsearchHighLevelRestClient method.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilder.java (hunk 2 above)
Comment (bratwurzt) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/elastic/ElasticsearchHibernatePropertiesBuilder.java:147]: Oh, sorry - thought that it was copy/pasted. Will revert the naming.

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/lastn.md (hunk 5 above)
Comment (bratwurzt) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/lastn.md:34]: Sure can and will.

**Comment by tadgh** [comment]
Thanks for the contribution! Will add the attribution in a separate PR. 🎉

**Comment by tadgh** [comment]
@bratwurzt Can you check out https://github.com/hapifhir/hapi-fhir/pull/2981 and let me know if this works for you?

**Comment by bratwurzt** [comment]
> 
> 
> @bratwurzt Can you check out #2981 and let me know if this works for you?

sure, works for me!
