### PR TITLE
2533 - Fix Issue with Reference Resources Not Being Returned In Search Queries

### LINKED ISSUE #2533: Versioned References at Paths is not including the Referenced Resource in the Response when the History Version is 1
When issuing a request for a specific Resource and also specifying an _include param, the referenced resource is not returned when there is only 1 version of the referenced resource available. When there are more than 1 versions available, the referenced resource is returned in the response bundle.

**Steps to Reproduce:**

Create a Condition Resource:

POST http://localhost:8000/Condition
```
{
      "resourceType": "Condition",
      "meta": {
        "versionId": "1",
        "lastUpdated": "2021-03-08T11:40:21.128-05:00"
      },
      "identifier": [ {
        "extension": [ {
          "url": "https://mysite.ca/fhir/StructureDefinition/ext-identifierversion",
          "valueString": "Condition1"
        } ]
      }
    ]
}
```

Create a Task Resource with a "basedOn" reference to version 1 of the Condition Resource:

POST http://localhost:8000/Task
```
{
      "resourceType": "Task",
      "identifier": [ {
        "extension": [ {
          "url": "https://mysite.ca/fhir/StructureDefinition/ext-identifierversion",
          "valueString": "Task1"
        } ]
      }
    ],
    "basedOn": [ {
        "reference": "Condition/1356/_history/1"
    } ]
}
```

GET the Task Resource using the following URL:
http://localhost:8000/Task?_id=1357&_include=Task:based-on

Notice that the Response does not contain the referenced Condition resource:
```
{
    "resourceType": "Bundle",
    "id": "68cfa2ec-4d7f-4efb-8d4a-3f4e8d8312d2",
    "meta": {
        "lastUpdated": "2021-04-08T15:21:01.674-04:00"
    },
    "type": "searchset",
    "total": 1,
    "link": [
        {
            "relation": "self",
            "url": "http://localhost:8000/Task?_id=1357&_include=Task%3Abased-on"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://localhost:8000/Task/1357",
            "resource": {
                "resourceType": "Task",
                "id": "1357",
                "meta": {
                    "extension": [
                        {
                            "url": "http://hapifhir.io/fhir/StructureDefinition/resource-meta-source",
                            "valueUri": "#zDFPj4pH13wJQsBP"
                        }
                    ],
                    "versionId": "1",
                    "lastUpdated": "2021-04-08T15:14:50.955-04:00"
                },
                "identifier": [
                    {
                        "extension": [
                            {
                                "url": "https://mysite.ca/fhir/StructureDefinition/ext-identifierversion",
                                "valueString": "Task1"
                            }
                        ]
                    }
                ],
                "basedOn": [
                    {
                        "reference": "Condition/1356/_history/1"
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}
```

Now, UPDATE the Condition Resource, creating a version 2:

PUT http://localhost:8000/Condition/1356
```
{
      "resourceType": "Condition",
      "id": "1356",
      "identifier": [ {
        "extension": [ {
          "url": "https://mysite.ca/fhir/StructureDefinition/ext-identifierversion",
          "valueString": "Condition2"
        } ]
      }
    ]
}
```

Now, issue the same GET Request again and notice that the Response now contains the referenced Condition Resource:

GET http://localhost:8000/Task?_id=1357&_include=Task:based-on
```
{
    "resourceType": "Bundle",
    "id": "bc0684c5-5ad7-42a7-85a8-d6c62ac7ea67",
    "meta": {
        "lastUpdated": "2021-04-08T20:30:12.143-04:00"
    },
    "type": "searchset",
    "total": 1,
    "link": [
        {
            "relation": "self",
            "url": "http://localhost:8000/Task?_id=1357&_include=Task%3Abased-on"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://localhost:8000/Task/1357",
            "resource": {
                "resourceType": "Task",
                "id": "1357",
                "meta": {
                    "extension": [
                        {
                            "url": "http://hapifhir.io/fhir/StructureDefinition/resource-meta-source",
                            "valueUri": "#zDFPj4pH13wJQsBP"
                        }
                    ],
                    "versionId": "1",
                    "lastUpdated": "2021-04-08T15:14:50.955-04:00"
                },
                "identifier": [
                    {
                        "extension": [
                            {
                                "url": "https://mysite.ca/fhir/StructureDefinition/ext-identifierversion",
                                "valueString": "Task1"
                            }
                        ]
                    }
                ],
                "basedOn": [
                    {
                        "reference": "Condition/1356/_history/1"
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "http://localhost:8000/Condition/1356",
            "resource": {
                "resourceType": "Condition",
                "id": "1356",
                "meta": {
                    "extension": [
                        {
                            "url": "http://hapifhir.io/fhir/StructureDefinition/resource-meta-source",
                            "valueUri": "#QMk4a47YuzkESQo8"
                        }
                    ],
                    "versionId": "1",
                    "lastUpdated": "2021-04-08T15:14:28.506-04:00"
                },
                "identifier": [
                    {
                        "extension": [
                            {
                                "url": "https://mysite.ca/fhir/StructureDefinition/ext-identifierversion",
                                "valueString": "Condition1"
                            }
                        ]
                    }
                ]
            },
            "search": {
                "mode": "include"
            }
        }
    ]
}
```

**Expected Behaviour:**
When the first GET Request is issued, the full Condition Resource is expected to be included in the Response Bundle.

### PR DESCRIPTION
**Pull request by KevinDougan-SmileCDR**
Fixes #2533

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java [hunk 1]
```diff
@@ -497,7 +497,15 @@ private IBundleProvider executeQuery(String theResourceType, SearchParameterMap
...
-					pids.add(resultIter.next());
+					//
+					//pids.add(resultIter.next());
+					ResourcePersistentId result = resultIter.next();
+					if (result.getVersion() == null) {
+						ourLog.info("Found NULL version, overriding and setting it to 1, for resourceId: \n{}", result);
+						result.setVersion(1L);
+					}
+					pids.add(result);
+					//
```
Comment (KevinDougan-SmileCDR) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java:508]: The previous version of the code simply assigned the resourceId without any concern for the "version" value, which in some cases is NULL (i.e. for v1 of a Resource because there's no history yet).
My "fix" above is to check for NULL and override it with a "1" since it is obviously(?) the 1st version of this Resource.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 2]
```diff
@@ -606,11 +606,13 @@ private void doLoadPids(Collection<ResourcePersistentId> thePids, Collection<Res
 
 		Map<Long, Long> resourcePidToVersion = null;
 		for (ResourcePersistentId next : thePids) {
-			if (next.getVersion() != null && myModelConfig.isRespectVersionsForSearchIncludes()) {
+			//if (next.getVersion() != null && myModelConfig.isRespectVersionsForSearchIncludes()) {
+			if (myModelConfig.isRespectVersionsForSearchIncludes()) {
```
Comment (KevinDougan-SmileCDR) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:610]: My "fix" here is to allow a NULL version through and deal with it down below.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 3]
```diff
@@ -643,7 +645,8 @@ private void doLoadPids(Collection<ResourcePersistentId> thePids, Collection<Res
 			 */
 			if (resourcePidToVersion != null) {
 				Long version = resourcePidToVersion.get(next.getResourceId());
-				if (version != null && !version.equals(next.getVersion())) {
+				//if (version != null && !version.equals(next.getVersion())) {
+				if (version != null && (resourceId.getVersion() == null || !version.equals(next.getVersion()))) {
```
Comment (KevinDougan-SmileCDR) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:649]: I am adding a check here for a NULL resourceId.version value and letting it pass through so it can be assigned to the "version" variable.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java [hunk 4]
```diff
@@ -661,8 +664,15 @@ private void doLoadPids(Collection<ResourcePersistentId> thePids, Collection<Res
...
-				continue;
+				// FIXME KBD: If the version is NULL, try the lookup again with version set to 1
+				if (resourceId.getVersion() == null) {
+					resourceId.setVersion(1L);
+					index = thePosition.get(resourceId);
+				}
+				if (index == null) {
+					ourLog.warn("Got back unexpected resource PID {}", resourceId);
+					continue;
+				}
```
Comment (KevinDougan-SmileCDR) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/SearchBuilder.java:675]: If the lookup fails, try again by explicitly overriding a NULL version with a "1" and looking again...

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4VersionedReferenceTest.java [hunk 5]
```diff
@@ -397,6 +403,51 @@ public void testSearchAndIncludeVersionedReference_Synchronous() {
...
+		task.setBasedOn(Arrays.asList(new Reference(conditionId)));
+		IIdType taskId = myTaskDao.create(task).getId().toUnqualified();
+		ourLog.info("taskId: {}", taskId);
+
+		// Search for the Task using an _include=Task.basedOn and make sure we get the Condition resource in the Response
+		IBundleProvider outcome = myTaskDao.search(SearchParameterMap.newSynchronous().addInclude(Task.INCLUDE_BASED_ON));
+		assertEquals(2, outcome.size());
+		List<IBaseResource> resources = outcome.getResources(0, 2);
+		// FIXME KBD: Change this to "2"
+		assertEquals(2, resources.size());
```
Comment (KevinDougan-SmileCDR) [inline hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4VersionedReferenceTest.java:430]: Note that without my "fixes", this will result in just 1 Task Resource being returned in the List, and the referenced Condition Resource is missing, which is the point of the original Bug.

**Review by jamesagnew — APPROVED** [review]
This needs a changelog but otherwise looks good!
