### PR TITLE
Issue 3530 terserutil contained failure

### LINKED ISSUE #3530: terserutil contained failure
terserutil fails to duplicate a resource that has a contained resource

### PR DESCRIPTION
**Pull request by fil512**
Closes #3530

TerserUtil.mergeAllFields() threw an exception when a value was a contained resource.

### CODE REVIEW

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/TerserUtil.java [hunk 1]
```diff
@@ -529,19 +525,29 @@ private static BaseRuntimeChildDefinition getBaseRuntimeChildDefinition(FhirCont
 	 * Creates a new element taking into consideration elements with choice that are not directly retrievable by element
 	 * name
 	 *
+	 *
+	 * @param theFhirContext
```
Comment (tadgh) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/util/TerserUtil.java:529]: issue: This javadoc is incorrect, there is no `theFhirContext`.

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/TerserUtil.java [hunk 2]
```diff
@@ -529,19 +525,29 @@ private static BaseRuntimeChildDefinition getBaseRuntimeChildDefinition(FhirCont
...
 			runtimeElementDefinition = theChildDefinition.getChildElementDefinitionByDatatype(theFromFieldValue.getClass());
 		} else {
 			runtimeElementDefinition = theChildDefinition.getChildByName(theChildDefinition.getElementName());
 		}
-		return (theConstructorParam == null) ? runtimeElementDefinition.newInstance() : runtimeElementDefinition.newInstance(theConstructorParam);
+		if ("contained".equals(runtimeElementDefinition.getName())) {
+			IBaseResource sourceResource = (IBaseResource) theFromFieldValue;
+			return theFhirTerser.clone(sourceResource);
+		}
+		if (theConstructorParam == null) {
```
Comment (tadgh) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/util/TerserUtil.java:546]: suggestion(non-blocking): maybe convert to an else-if for easier readability so it will be one logical construct instead of 2.

File: hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/util/TerserUtilTest.java [hunk 3]
```diff
@@ -17,78 +18,99 @@
...
+			                          "system": "urn:hssc:srhs:contact:organizationId",
+			                          "value": "1000"
+			                      }
+			                  ],
+			                  "name": "BUILDERS FIRST SOURCE",
+			                  "resourceType": "Organization"
+			              }
+			          ]
+			    }
+				""";
```
Comment (tadgh) [inline hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/util/TerserUtilTest.java:113]: praise: nice test addition

**Review by tadgh — APPROVED** [review]
Approved pending changes.
