### PR TITLE
Fixes a bug with tags. 

### LINKED ISSUE #4819: Tags now have userSelected = false not provided by user.
**Describe the bug**
Tags now have a new property not present in the input data: `userSelected`.

**To Reproduce**

```
Patient patient1 = new Patient();
patient1.getMeta().addTag().setSystem("http://foo").setCode("bar");
IIdType pid1 = myPatientDao.create(patient1).getId();

// when
var patientReadback = myPatientDao.read(pid1);
System.out.println(myFhirContext.newJsonParser().setPrettyPrint(true).encodeResourceToString(patientReadback));
```

On 6_4, and HEAD, this prints

```
{
  "resourceType": "Patient",
  "id": "1",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2023-05-04T10:37:14.596-04:00",
    "tag": [ {
      "system": "http://foo",
      "code": "bar",
      "userSelected": false
    } ]
  },
}
```

Note the `"userSelected": false` bit.  This was not passed in.

**Expected behavior**

Print
```
{
  "resourceType": "Patient",
  "id": "1",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2023-05-04T10:37:14.596-04:00",
    "tag": [ {
      "system": "http://foo",
      "code": "bar"
    } ]
  },
}
```

### PR DESCRIPTION
**Pull request by tadgh**
Fixes #4819

The implementation in #4204 resulted in occasional `NonUniqueResultExceptions` during tag lookup. 

The core of the fix is relaxing the unique constraint on HFJ_TAG_DEF.  Some of our DBs do not consider tuples with null in uniqueness.  This means that we may now have multiple TagDefinition entities for the same tuples.  This is OK, and we now [pick the first one](https://github.com/hapifhir/hapi-fhir/pull/4813/files#diff-0e555772da8fd70288fe0c2b9511370844f0c355669d7fb038ee505b1ae5b33bR429)

Also fixes #4819.  Tags are Codings, and have userSelected and version fields.  These were only recently added, and IBaseCoding uses primitive.  We introduce a spy to preserve nulls in db round trips between model classes and entities.

### CODE REVIEW

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/Tag.java [hunk 1]
```diff
@@ -114,37 +115,22 @@ public boolean equals(Object obj) {
...
 
 	@Override
 	public int hashCode() {
 		final int prime = 31;
 		int result = 1;
-		result = prime * result + ((myScheme == null) ? 0 : myScheme.hashCode());
-		result = prime * result + ((myTerm == null) ? 0 : myTerm.hashCode());
-		result = prime * result + ((myVersion == null) ? 0 : myVersion.hashCode());
-		result = prime * result + Boolean.hashCode(myUserSelected);
+		result = prime * result + Objects.hashCode(myScheme);
```
Comment (fil512) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/Tag.java:130]: is this the same hashCode that's used in our SP_IDX table?  If so, I'd worry about messing with it

Comment (jamesagnew) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/Tag.java:130]: @fil512 assuming you're referring to the hashes that are used for actual indexed results, this change won't affect that. Those hashes are generated with a dedicated set of methods that don't rely on Object#hashCode

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java [hunk 2]
```diff
@@ -782,6 +782,7 @@ private void encodeResourceToJsonStreamWriter(RuntimeResourceDefinition theResDe
 						writeOptionalTagWithTextNode(theEventWriter, "system", tag.getScheme());
 						writeOptionalTagWithTextNode(theEventWriter, "code", tag.getTerm());
 						writeOptionalTagWithTextNode(theEventWriter, "display", tag.getLabel());
+						// wipmb should we be writing the new properties here?  There must be another path.
```
Comment (jamesagnew) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java:785]: To address @michaelabuckley 's question, yes we probably should.

This whole code path only applies to the old style DSTU2 structures. In DSTU3+ tags and the other Meta properties are just modelled as normal resource elements so they don't need any special code path, but the older structures didn't work that way.

It'd probably be worth refactoring the whole block this is in, starting with `if (theResource instanceof IResource) {` into a separate method with a name pointing out that this is DSTU2 specific. (The hint is that `IResource` is a legacy interface only implemented by DSTU2 structs)

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4813-fix-tag-nonunique.yaml [hunk 3]
```diff
@@ -0,0 +1,4 @@
+---
+type: fix
+issue: 4813
+title: "A previous implementation caused tags to be non-unique. This could cause `NonUniqueResultException` errors in some cases. This lookup path has been fixed, and that error will no longer be thrown."
```
Comment (jamesagnew) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4813-fix-tag-nonunique.yaml:4]: Recommended rewording for clarity:

```suggestion
title: "Under heavy concurrency, a bug resulted in identical tag definitions being rejected with a `NonUniqueResultException` some of the time.  This has been corrected."
```

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java [hunk 4]
```diff
@@ -95,6 +95,15 @@ public HapiFhirJpaMigrationTasks(Set<String> theFlags) {
...
 		init640();
 		init660();
+		init680();
+	}
+
+	protected void init680() {
+		Builder version = forVersion(VersionEnum.V6_8_0);
+
+		Builder.BuilderWithTableName tagDefTable = version.onTable("HFJ_TAG_DEF");
+		tagDefTable.dropIndex("20230209.4", "IDX_TAGDEF_TYPESYSCODEVERUS");
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java:105]: Should we also be replacing this with a new non-unique index? The search in `getTagOrNull` still appears to include all of the columns that were in the constraint

**Review by jamesagnew — APPROVED** [review]

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/Tag.java (hunk 1 above)
Comment (michaelabuckley) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/Tag.java:130]: Agree.  Tags do not use our hashing scheme.  This hashCode would only be used in ram and should agree with equals.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java (hunk 4 above)
Comment (michaelabuckley) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java:105]: I suppose since they are nullable, we should just add them to IDX_TAG_DEF_TP_CD_SYS.  They'll be basically free if you aren't using them.  We'll do that.

Comment (tadgh) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java:105]: 1. Dropped index. 
2. Re-added index with new column list.

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java (hunk 2 above)
Comment (tadgh) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java:785]: refactored into `parseMetaForDSTU2`
