### PR TITLE
rebuild golden resource from survivorship on link edit

### LINKED ISSUE #5236: Allow rebuilding of GoldenResources from existing link sources when a link is changed to no-match
When using survivorship rules, golden resources are composed of all the various values from all their linked source resources.

But when a link is broken (changed to no-match), the golden resource now has incorrect merged data.

We want to rebuild it.

### PR DESCRIPTION
**Pull request by TipzCM**
closes #5236

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/mdm/MdmLinkDaoJpaImpl.java [hunk 1]
```diff
@@ -380,7 +380,15 @@ public List<MdmLinkWithRevision<MdmLink>> getHistoryForIds(
 
 			if (!theMdmHistorySearchParameters.getGoldenResourceIds().isEmpty()
 					&& !theMdmHistorySearchParameters.getSourceIds().isEmpty()) {
-				goldenResourceAndOrResourceIdCriterion = AuditEntity.or(goldenResourceIdCriterion, resourceIdCriterion);
+				if (theMdmHistorySearchParameters.getParameterJoinType() == MdmHistorySearchParameters.JoinType.AND) {
```
Comment (longma1) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/mdm/MdmLinkDaoJpaImpl.java:383]: Looking at MdmHistorySearchParameter type, the parameterJoinType defaults to or and the setter never gets used. If this is preparation for the future I withdraw my comment but for now this seems to be dead code.

**Review by longma1 — APPROVED** [review]
