### PR TITLE
return 400 for invalid chained search param values

### LINKED ISSUE #7361: Chained search parameters with invalid values return HTTP 500 instead of HTTP 400
When performing a FHIR search with chained parameters (e.g., Observation?subject.birthdate=invaliddate), invalid input that triggers a DataFormatException incorrectly returns HTTP 500 Internal Server Error instead of the         
  expected HTTP 400 Bad Request.                                                                                                                                                                                                       
                                                                                                                                                                                                                                          
 ###  Expected Behavior                                                                                                                                                                                                                    
                                                                                                                                                                                                                                       
  Invalid client input (malformed dates, quantities, etc.) should return:                                                                                                                                                              
  - HTTP 400 Bad Request                                                                                                                                                                                                               
  - Error message: HAPI-1940: Invalid date/time/quantity format: "..."                                                                                                                                                                 
                                                                                                                                                                                                                                       
  ### Actual Behavior                                                                                                                                                                                                                      
                                                                                                                                                                                                                                       
  Invalid client input in chained searches returns:                                                                                                                                                                                    
  - HTTP 500 Internal Server Error ❌                                                                                                                                                                                                  
  - Same error message, but with incorrect status code

### PR DESCRIPTION
**Pull request by mrdnctrk**
## Summary                                                                                                                                                                                                                              
                                                                                                                                                                                                                                       
  Closes #7361 - Chained search parameters with invalid values now correctly return HTTP 400 Bad Request instead of HTTP 500 Internal Server Error.                                                                                     
                                                                                                                                                                                                                                       
  ## Problem

  When searching with chained parameters containing invalid input (e.g., Observation?subject.birthdate=invaliddate or DiagnosticReport?result.value-quantity=invalid), the server incorrectly returned HTTP 500 instead of HTTP
  400.
  
Simple (non-chained) parameters worked correctly and already returned HTTP 400, because they are validated much earlier in a synchronous manner and the [ExceptionHandlingInterceptor](https://github.com/hapifhir/hapi-fhir/blob/c8002daec051b097384108340817e0a2ccc5b6b2/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptor.java#L165) converted them to  InvalidRequestException (400 response).

  ## Root Cause

  Chained parameters are validated during async query execution in SearchTask, where DataFormatException was being treated as a server error (500) instead of a client error (400). The exception handling logic in SearchTask only checked for
  BaseServerResponseException types and defaulted everything else to 500.

   ## Solution

  Modified exception handling in SearchTask and SearchContinuationTask to explicitly check for DataFormatException in the root cause and return HTTP 400 for client input errors.

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java [hunk 1]
```diff
@@ -530,6 +517,43 @@ public Void call() {
...
+		}
+
+		if (HapiSystemProperties.isUnitTestCaptureStackEnabled()) {
+			failureMessage += "\nStack\n" + ExceptionUtils.getStackTrace(rootCause);
+		}
+
+		mySearch.setFailureMessage(failureMessage);
+		mySearch.setFailureCode(failureCode);
+		mySearch.setStatus(SearchStatusEnum.FAILED);
+	}
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:555]: Question: Can we not catch the error where it is actually occurring, and then bubble up a valid BaseServerResponseException?

To me, This looks like we are adding a shimmed route for handling a special type of exception, but shouldn't we just be throwing the correct exception up in the first place? I worry that this blanket catch of all DataFormatExceptions is overly broad, and we should catch it only where it specifically occurs, and rethrow a BaseServerResponseException. What are your thoughts?

Comment (mrdnctrk) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:555]: I went with this approach seeing that [ExceptionHandlingInterceptor](https://github.com/hapifhir/hapi-fhir/blob/c8002daec051b097384108340817e0a2ccc5b6b2/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/ExceptionHandlingInterceptor.java#L165) already has a blanket catch for the DataFormatExceptions as in this case. 

I am OK to change the handling of DataFormatExceptions deeper in the stack. But we have to decide where would be the best place to catch and convert this to a InvalidRequestException. The current call stack when the exception is thrown is as follows. Do you think catching it in SearchTask.doSearch would be better or should it be higher in the stack? Let me know if you have any suggestion.

```
at ca.uhn.fhir.rest.param.BaseParamWithPrefix.extractPrefixAndReturnRest(BaseParamWithPrefix.java:64)
at ca.uhn.fhir.rest.param.DateParam.setValueAsString(DateParam.java:182)
at ca.uhn.fhir.rest.param.DateParam.doSetValueAsQueryToken(DateParam.java:127)
at ca.uhn.fhir.rest.param.BaseParam.setValueAsQueryToken(BaseParam.java:109)
at ca.uhn.fhir.jpa.search.builder.QueryStack.newParameterInstance(QueryStack.java:2849)
at ca.uhn.fhir.jpa.search.builder.predicate.ResourceLinkPredicateBuilder.mapReferenceChainToRawParamType(ResourceLinkPredicateBuilder.java:809)
at ca.uhn.fhir.jpa.search.builder.predicate.ResourceLinkPredicateBuilder.addPredicateReferenceWithChain(ResourceLinkPredicateBuilder.java:541)
at ca.uhn.fhir.jpa.search.builder.predicate.ResourceLinkPredicateBuilder.createPredicate(ResourceLinkPredicateBuilder.java:277)
at ca.uhn.fhir.jpa.search.builder.QueryStack.createPredicateReference(QueryStack.java:1476)
at ca.uhn.fhir.jpa.search.builder.QueryStack.createPredicateReference(QueryStack.java:1429)
at ca.uhn.fhir.jpa.search.builder.QueryStack.createPredicateSearchParameter(QueryStack.java:2541)
at ca.uhn.fhir.jpa.search.builder.QueryStack.searchForIdsWithAndOr(QueryStack.java:2404)
at ca.uhn.fhir.jpa.search.builder.SearchBuilder.searchForIdsWithAndOr(SearchBuilder.java:359)
at ca.uhn.fhir.jpa.search.builder.SearchBuilder.createChunkedQueryNormalSearch(SearchBuilder.java:772)
at ca.uhn.fhir.jpa.search.builder.SearchBuilder.createChunkedQuery(SearchBuilder.java:712)
at ca.uhn.fhir.jpa.search.builder.SearchBuilder.createQuery(SearchBuilder.java:551)
at ca.uhn.fhir.jpa.search.builder.SearchBuilder$QueryIterator.initializeIteratorQuery(SearchBuilder.java:3149)
at ca.uhn.fhir.jpa.search.builder.SearchBuilder$QueryIterator.fetchNext(SearchBuilder.java:2961)
at ca.uhn.fhir.jpa.search.builder.SearchBuilder$QueryIterator.hasNext(SearchBuilder.java:3174)
at ca.uhn.fhir.jpa.search.builder.tasks.SearchTask.doSearch(SearchTask.java:687)
at ca.uhn.fhir.jpa.search.builder.tasks.SearchTask$$Lambda$2870/0x000000080200b710.run(Unknown Source:-1)
at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService$ExecutionBuilder.lambda$execute$0(HapiTransactionService.java:546)
at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService$ExecutionBuilder$$Lambda$2802/0x0000000801fbb728.doInTransaction(Unknown Source:-1)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteCallback(HapiTransactionService.java:444)
at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteInTransaction(HapiTransactionService.java:351)
at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecute(HapiTransactionService.java:288)
at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService$ExecutionBuilder.execute(HapiTransactionService.java:560)
at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService$ExecutionBuilder.execute(HapiTransactionService.java:549)
at ca.uhn.fhir.jpa.search.builder.tasks.SearchTask.call(SearchTask.java:453)
at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl.submitSearch(SearchCoordinatorSvcImpl.java:690)
at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl.registerSearch(SearchCoordinatorSvcImpl.java:484)
at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.search(BaseHapiFhirResourceDao.java:2176)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
at jdk.proxy1.$Proxy297.search(Unknown Source:-1)
at ca.uhn.fhir.jpa.rp.r4.ObservationResourceProvider.search(ObservationResourceProvider.java:371)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:568)
at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
at ca.uhn.fhir.rest.server.method.SearchMethodBinding.invokeServer(SearchMethodBinding.java:311)
at ca.uhn.fhir.rest.server.method.SearchMethodBinding.invokeServer(SearchMethodBinding.java:53)
at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:145)
at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:274)
at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1206)
at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:429)
at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1961)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1621)
at ca.uhn.fhir.test.utilities.server.BaseJettyServerExtension$RequestCapturingFilter.doFilter(BaseJettyServerExtension.java:352)
at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1593)
at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1554)
at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:819)
at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:469)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1064)
at org.eclipse.jetty.server.Handler$Sequence.handle(Handler.java:805)
at org.eclipse.jetty.server.Server.handle(Server.java:182)
at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:416)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
at java.lang.Thread.run(Thread.java:833) 
```

Comment (tadgh) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/tasks/SearchTask.java:555]: I see what you mean. I think the best fix is to perform validation way earlier up in the stack, at the same time that we validate non-chained params. That said, its too heavy a lift here I think. Keep your solution as is for now, consider my comment retracted.
