### PR TITLE
7040 contained resources plusplus

### LINKED ISSUE #7040: Parser should add a contained reference link when parsing/serializing resources that contain contained resources
When a resource has a contained resource, that contained resource's id does not get prepended with a "#".

So if this resource's contained resource is referenced, not by a Reference, but by the actual resource itself, it cannot be processed by the TransactionProcessor (because the contained resource does not contain a contained resource id!)

We should add a contained resource reference (that does contain the contained resource's id prepended by an #) so that transactions afterwards can store the resource.

This is to fix a regression

### PR DESCRIPTION
**Pull request by TipzCM**
closes #7040

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/BaseParser.java [hunk 1]
```diff
@@ -227,6 +242,12 @@ private String determineReferenceText(
 				}
 			}
 			return reference;
+		} else {
+			if (ref.isLocal() && !theContext.getContainedResources().referenceMatchesAContainedResource(ref)) {
+				throw new DataFormatException(
```
Comment (jamesagnew) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/BaseParser.java]: Reminder: This will need an error code

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java [hunk 2]
```diff
@@ -1829,7 +1829,14 @@ public Map<String, IBaseResource> getExistingIdToContainedResource() {
 			return myExistingIdToContainedResourceMap;
 		}
 
+		public boolean referenceMatchesAContainedResource(IIdType theRefId) {
```
Comment (jamesagnew) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java:1832]: Suggestion: Given how tricky this all is, I'd suggest adding the following line at the top of this method:

```java
assert theRefId.getIdPart().startsWith("#");
```

..just to catch any weirdness in unit tests. Given the calling context of the code here, I expect that will always be true, but it never hurts to add assertions about what you expect to always be true

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java [hunk 3]
```diff
@@ -1829,7 +1829,14 @@ public Map<String, IBaseResource> getExistingIdToContainedResource() {
...
+			String expectedResourceId = theRefId.getIdPart().substring(1);
+			return this.getContainedResources().stream()
+					.anyMatch(res -> res.getIdElement().getIdPart().equals(expectedResourceId));
+		}
+
 		public IIdType addContained(IBaseResource theResource) {
+			theResource.setUserData("IS_CONTAINED", true);
```
Comment (jamesagnew) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java]: Question: I don't see this getting used anywhere. Is it needed? If so, should it be extracted into a constant?

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java [hunk 4]
```diff
@@ -1246,7 +1249,7 @@ public void testCreateAndReadBackResourceWithContainedReferenceToContainer() {
 		ourLog.info(output);
 
 		Location loc = (Location) org.getContained().get(0);
-		assertEquals("#", loc.getManagingOrganization().getReference());
+		assertEquals("1", loc.getManagingOrganization().getReference());
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4Test.java:1252]: Oh this is so interesting. It took me a while of reading to figure out why you had changed `#` to `1` this in the first place, but I see: this was a bug before that your fix has actually corrected

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java (hunk 2 above)
Comment (TipzCM) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java:1832]: added

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/BaseParser.java (hunk 1 above)
Comment (TipzCM) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/BaseParser.java]: added

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java (hunk 3 above)
Comment (TipzCM) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java]: i'll verify with gary, but i think it can be removed
