### PR TITLE
Contained bug

### LINKED ISSUE #6403: Terser has odd behaviour
Currently, if you create a bundle with two resources, each with an identical contained resource, the JSON Parser will produce a garbled response, such as the following: 
```
{
	"resourceType": "Observation",
	"id": "1348",
	"contained": [
		{
			"resourceType": "Practitioner",
			"id": "1"
		}
	],
	"status": "final",
	"effectiveDateTime": "2024-10-11T15:24:00-06:00",
	"issued": "2024-10-11T15:24:00-07:00",
	"performer": [
		{
			"reference": "#1"
		}
	],
	"valueString": "0.032",
	"specimen": {
		"reference": "#1"
	}
}
```

### PR DESCRIPTION
**Pull request by tadgh**
- Test
- modify algorithm for server-assigned contained IDs.
- Process contained resources which have a client-assigned ID before those that do not in a resource. 
- moved ContainedResources from the Parser, to the EncodeContext object, so we get one per resource processed. 
Closes #6403

### CODE REVIEW

File: hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/JsonParserR4Test.java [hunk 1]
```diff
@@ -261,9 +265,83 @@ public void testDuplicateContainedResourcesNotOutputtedTwice() {
 
 		idx = encoded.indexOf("\"Medication\"", idx + 1);
 		assertEquals(-1, idx);
+	}
+
```
Comment (epeartree) [inline hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/JsonParserR4Test.java:269]: ouch! 
what a great test.  once u get it, u also understand that the implementation is correct

File: hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/JsonParserR4Test.java [hunk 2]
```diff
@@ -261,9 +265,83 @@ public void testDuplicateContainedResourcesNotOutputtedTwice() {
...
+			Practitioner practitioner = new Practitioner();
+			DiagnosticReport report = new DiagnosticReport();
+			report.addSpecimen(new Reference(specimen));
+
+			Observation obs = new Observation();
+			//When: The practitioner (which is parsed first, has an assigned id that will collide with auto-assigned
+			practitioner.setId("#1");
+			obs.addPerformer(new Reference(practitioner));
+			obs.setSpecimen(new Reference(specimen));
+
```
Comment (epeartree) [inline hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/JsonParserR4Test.java:314]: extra line

File: hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/JsonParserR4Test.java [hunk 3]
```diff
@@ -261,9 +265,83 @@ public void testDuplicateContainedResourcesNotOutputtedTwice() {
...
+			DiagnosticReport report = new DiagnosticReport();
+			report.addSpecimen(new Reference(specimen));
+
+			Observation obs = new Observation();
+
+			//When: The specimen (which is parsed second, has an assigned id that will collide with auto-assigned practitioner
+			specimen.setId("#1");
+			obs.addPerformer(new Reference(practitioner));
+			obs.setSpecimen(new Reference(specimen));
+
```
Comment (epeartree) [inline hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/JsonParserR4Test.java:335]: extra line

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4ContainedTest.java [hunk 4]
```diff
@@ -46,6 +49,33 @@ public void after() throws Exception {
...
+		observation.getPerformerFirstRep().setReference("#1");
+		observation.getSpecimen().setReference("#2");
+		observation.setSubject(new Reference("Patient/test-patient"));
+
+		observation.getCode().getCodingFirstRep().setSystem("LN").setCode("NV");
+		observation.setValue(new StringType("abc123"));
+
+		System.out.println(myFhirContext.newJsonParser().setPrettyPrint(true).encodeResourceToString(observation));
+		DaoMethodOutcome daoMethodOutcome = myObservationDao.create(observation, mySrd);
+
```
Comment (epeartree) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4ContainedTest.java:76]: this test has no assertion unless the test is about being able to create or encodeToString an Observation without raising an exception.

**Review by epeartree — APPROVED** [review]

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java [hunk 5]
```diff
@@ -1415,33 +1416,41 @@ public boolean acceptUndeclaredExtension(
 		});
 	}
 
+	private Integer hasId(IBaseReference ref) {
```
Comment (jamesagnew) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java:1419]: It's kinda confusing having a method in java called `hasXXX` that returns an int.... Recommend perhaps renaming it to `hasIdForComparison` or something like that. Also it can presumably be a static method, which is a tiny performance boost (important for fundamental stuff like parser code).

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java [hunk 6]
```diff
@@ -1415,33 +1416,41 @@ public boolean acceptUndeclaredExtension(
...
-						theContained.addContained(next.getReferenceElement(), potentialTarget);
-						containResourcesForEncoding(theContained, potentialTarget, theModifyResource);
-					}
-				}
-			}
-		}
 
+		//Note that we process all contained resources that have arrived here with an ID contained resources first, so that we dont accidentally auto-assign an ID
+		//which may collide with a resource we have yet to process.
+		allReferences = allReferences.stream()
```
Comment (jamesagnew) [inline hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java:1432]: Two more suggested performance tweaks (this is such heavily used code that we should be as performant as possible):

* Just sort the `allReferences` list directly instead of doing this stream thing - no sense creating a new list object every time when the list we're already working on is fresh for every call to this method
* Extract the comparator out into a static constant instead of creating a new one each time - Probably the JIT does this automatically, but it doesn't hurt to make it explicit

**Review by jamesagnew — APPROVED** [review]

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java (hunk 5 above)
Comment (jamesagnew) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java:1419]: Actually - just looked it up and boolean is comparable just like int is. So you could probably actually just make this return boolean.

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4ContainedTest.java (hunk 4 above)
Comment (tadgh) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4ContainedTest.java:76]: Ah this whole test should be removed , it was a first try before I found a better spot

Comment (tadgh) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4ContainedTest.java:76]: Ah this whole test should be removed , it was a first try before I found a better spot

File: hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java (hunk 6 above)
Comment (tadgh) [reply hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java]: Both good calls, both done!
