### PR TITLE
Jd 20260105 correct mdm virtualization bundle totals

### LINKED ISSUE #7447: MDM Virtualization endpoint - Bundle Total includes filtered resources for $everything
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
The bundle.total is incorrectly calculated when using the MDM virtualization endpoint. 

**To Reproduce**

1. Create 2 Patients(Patient/A and Patient/B), 2 Patients link to same golden resource
2. Create 1 Observations, subject.reference to Patient/A 
3. Create 1 Observation, subject.reference to Patient/B
4. GET [http://localhost:8000/Patient/A/$everything
5. Review bundle.total = 5

**Expected behavior**
 Patient B and Golden Patient have been filtered by the virtualization so the total should be 3.

**Screenshots**
N/A

**Environment (please complete the following information):**

- HAPI FHIR Version: 8.8.0
- OS:  macOS: 15.6.1 (24G90)
- Browser Chrome

**Additional context**

### PR DESCRIPTION
**Pull request by jdunlop-smile**
Correction to MDM Virtualization bundle.count for $everything

closes #7447

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderMatchR4Test.java [hunk 1]
```diff
@@ -24,9 +24,9 @@
 import static org.junit.jupiter.api.Assertions.assertEquals;
 import static org.junit.jupiter.api.Assertions.assertNotNull;
 
-public class MdmProviderMatchR4Test extends BaseProviderR4Test {
+public class MdmProviderMatchR4Test extends BaseMdmProviderR4Test {
 
-	private static final Logger ourLog = LoggerFactory.getLogger(MdmProviderMatchR4Test.class);
+	private static final Logger ourLog = LoggerFactory.getLogger(MdmProviderVirtualizationR4Test.class);
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderMatchR4Test.java]: Is this change deliberate? The old logger name looked right

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderQueryLinkR4Test.java [hunk 2]
```diff
@@ -308,9 +308,9 @@ public void testQueryLinkPages() {
 		}
 	}
 
-	private List<Parameters.ParametersParameterComponent> getParametersByName(Parameters theParams, String theName) {
-		return theParams.getParameter().stream().filter(p -> p.getName().equals(theName)).collect(Collectors.toList());
-	}
+//	private List<Parameters.ParametersParameterComponent> getParametersByName(Parameters theParams, String theName) {
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderQueryLinkR4Test.java]: Nitpick: dead code

**Review by jamesagnew — CHANGES_REQUESTED** [review]
This looks like it's still failing a number of CI issues - looks good to me, but should pass CI before final approval.

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderMatchR4Test.java (hunk 1 above)
Comment (jdunlop-smile) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderMatchR4Test.java]: Corrected

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderQueryLinkR4Test.java (hunk 2 above)
Comment (jdunlop-smile) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderQueryLinkR4Test.java]: Commented code removed
