### PR TITLE
Handle 400 and 404 codes returned by remote terminology operation.

### LINKED ISSUE #6150: Resource `$validate` operation returns 404 when a `ValueSet` has multiple includes from Remote Terminology
**Describe the bug**
Resource `$validate` operation returns 404 when the resource profile uses a `ValueSet` that includes codes from multiple systems that are present in a Remote Terminology server.

**To Reproduce**
Steps to reproduce the behaviour:
1. GET https://r4.ontoserver.csiro.au/fhir/CodeSystem/$lookup?code=a&system=http://snomed.info/sct
2. Notice that the request returns 404
3. Create a `ValueSet` bound to two systems, and a profile `StructureDefinition` that references that `ValueSet`. For example: [valueset-prescriptiondose.json](https://github.com/user-attachments/files/16367071/valueset-prescriptiondose.json)
[profile-MedicationAdministration.json](https://github.com/user-attachments/files/16367072/profile-MedicationAdministration.json).

4. POST http://localhost:8000/MedicationAdministration/$validate with a resource in the body that references the profile on step 3. For example: [MedicationAdministration.json](https://github.com/user-attachments/files/16367073/MedicationAdministration.json).

5. The request returns 404
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "not-found",
            "details": {
                "text": "[9fe6988a-5dbd-44b4-9939-b8d44a80062b]: The code min (http://snomed.info/sct:http://snomed.info/sct/32506021000036107/version/20240630) was not found."
            },
            "diagnostics": "[9fe6988a-5dbd-44b4-9939-b8d44a80062b]: The code min (http://snomed.info/sct:http://snomed.info/sct/32506021000036107/version/20240630) was not found."
        },
        {
            "severity": "information",
            "code": "informational",
            "diagnostics": "X-Request-Id: 26dd0ab5-6250-43db-aeae-70431c3b3ca5"
        }
    ]
}
```

**Expected behavior**
The request should return 200 with a list of validation issues.

**Environment (please complete the following information):**
 - HAPI FHIR Version 7.3.12

### PR DESCRIPTION
**Pull request by codeforgreen**
Closes #6150

### CODE REVIEW

File: hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java [hunk 1]
```diff
@@ -204,43 +206,52 @@ public LookupCodeResult lookupCode(
...
+					.withParameters(params)
+					.useHttpGet()
+					.execute();
+		} catch (ResourceNotFoundException | InvalidRequestException e) {
+			ourLog.error(e.getMessage(), e);
+			LookupCodeResult result = LookupCodeResult.notFound(system, code);
+			result.setErrorMessage(
+					getErrorMessage("unknownCodeInSystem", system, code, client.getServerBase(), e.getMessage()));
+			return result;
+		}
```
Comment (michaelabuckley) [inline hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java:241]: Question: Could this be implemented as a client interceptor?  This functionality (i.e. translating non-standard return codes) might be useful for all users of GenericClient.

**Review by michaelabuckley — APPROVED** [review]
This is fine.  I wonder if it can be cleaner with an interceptor.

File: hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java (hunk 1 above)
Comment (codeforgreen) [reply hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java]: Thanks for reviewing. As I understand it is a nice to have. I added a comment about this in the current solution.
