### PR TITLE
7168 canonicalurls in sps

### LINKED ISSUE #7168: Subscriptions on canoncal SP urls don't work
Attempting to match a subscription with a canonical url SP reference to a resource fails.

### PR DESCRIPTION
**Pull request by TipzCM**
closes #7168

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

**Review by lukedegruchy — APPROVED** [review]

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/search/ExtendedHSearchIndexExtractor.java [hunk 1]
```diff
@@ -181,9 +181,11 @@ public ExtendedHSearchIndexData extract(
 					// Case 1: Resource Type and Resource ID is known
 					// Case 2: Resource is unknown and referred by canonical url reference
 					if (!Strings.isNullOrEmpty(nextLink.getTargetResourceId())) {
+						// non-canonical
```
Comment (fil512) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/search/ExtendedHSearchIndexExtractor.java:185]: Nice. Thanks!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/search/ExtendedHSearchIndexExtractor.java [hunk 2]
```diff
@@ -181,9 +181,11 @@ public ExtendedHSearchIndexData extract(
...
 						qualifiedTargetResourceId =
 								nextLink.getTargetResourceType() + "/" + nextLink.getTargetResourceId();
```
Comment (fil512) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/search/ExtendedHSearchIndexExtractor.java:188]: Maybe assert type is not unknown (I.e. Java assert so it’s only asserted in tests)

File: hapi-fhir-jpaserver-model/src/main/java/ca/uhn/fhir/jpa/model/entity/ResourceLink.java [hunk 3]
```diff
@@ -340,7 +341,7 @@ public Long getTargetResourcePid() {
 	public void setTargetResourceUrlCanonical(String theTargetResourceUrl) {
 		Validate.notBlank(theTargetResourceUrl);
 
-		myTargetResourceType = "(unknown)";
+		myTargetResourceType = ResourceLinkUtils.UNKNOWN;
```
Comment (fil512) [inline hapi-fhir-jpaserver-model/src/main/java/ca/uhn/fhir/jpa/model/entity/ResourceLink.java:344]: Thanks. You’re good at leaving the campsite cleaner than when you arrived.

**Review by fil512 — APPROVED** [review]

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/search/ExtendedHSearchIndexExtractor.java (hunk 2 above)
Comment (TipzCM) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/search/ExtendedHSearchIndexExtractor.java:188]: added
