### PR TITLE
3242 search content param removed not readded

### LINKED ISSUE #3242: Search removes _content parameter for count but never adds it back
Searches with SearchMap setSearchTotal mode set to ACCURATE returns incorrect search results when using _content or _text parameters (returning everything instead of results filtered down by _content).

Expected Result:
Should return correct results

### PR DESCRIPTION
**Pull request by TipzCM**
closes #3242 

Changes:
* Fixed issue of searchmap returning incorrect values
* Added copy to searchmapparams 
* added changelog
* updated unit tests

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java [hunk 1]
```diff
@@ -119,12 +116,13 @@ public boolean supportsSomeOf(SearchParameterMap myParams) {
...
 					 */
-					List<List<IQueryParameterType>> contentAndTerms = theParams.remove(Constants.PARAM_CONTENT);
+					List<List<IQueryParameterType>> contentAndTerms = theParams.get(Constants.PARAM_CONTENT);
 					builder.addStringTextSearch(Constants.PARAM_CONTENT, contentAndTerms);
+
 					/*
 					 * Handle _text parameter (resource narrative content)
 					 */
-					List<List<IQueryParameterType>> textAndTerms = theParams.remove(Constants.PARAM_TEXT);
+					List<List<IQueryParameterType>> textAndTerms = theParams.get(Constants.PARAM_TEXT);
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java:125]: This behaviour is intentional, so that HAPI-FHIR's DAO-layer does not process _content or _text parameters, and they are only processed by the fulltext service. What is the impetus for this change?

Comment (TipzCM) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java]: Fixed - changed to copy params

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3242-fix-bug-that-mutates-searchparam-map.yaml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+issue: 3242
+type: fix
+title: "Fixed bug that caused accurate elastisearch searches to return all values when using
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3242-fix-bug-that-mutates-searchparam-map.yaml:4]:
```suggestion
title: "Fixed bug that caused queries that checked Elastisearch when setting `_total=accurate` searches to return all values when using
```

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java [hunk 3]
```diff
@@ -89,6 +90,42 @@ public SearchParameterMap() {
 		super();
 	}
 
+	/**
+	 * Creates and returns a copy of this map
+	 * @return
+	 */
+	@JsonIgnore
+	public SearchParameterMap cpy() {
```
Comment (tadgh) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java:98]:
```suggestion
	public SearchParameterMap clone() {
```

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java [hunk 4]
```diff
@@ -89,6 +90,42 @@ public SearchParameterMap() {
...
+		map.setSearchContainedMode(getSearchContainedMode());
+
+		for (Map.Entry<String, List<List<IQueryParameterType>>> entry : mySearchParameterMap.entrySet()) {
+			List<List<IQueryParameterType>> params = entry.getValue();
+			for (List<IQueryParameterType> p : params) {
+				for (IQueryParameterType t : p) {
+					map.add(entry.getKey(), t);
+				}
+			}
+		}
```
Comment (tadgh) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java:124]: I would like to see logic in the below test which exercises this part of the clone. I'd like to see in test that the two actual SP sets are the same. The current test just asserts on flags of the sp map, so i think this enhancement would help.

**Review by tadgh — CHANGES_REQUESTED** [review]
Minor changes requested, specifically just  a minor addition to a test, and a few naming/doc nitpicks. Overall, great work, and nice comments.

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java (hunk 4 above)
Comment (TipzCM) [reply hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java:125]: the test actually does do that, too.

but i added a more explicit test

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3242-fix-bug-that-mutates-searchparam-map.yaml [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+issue: 3242
+type: fix
+title: "Fixed bug that caused queries that checked Elastisearch when setting `_total=accurate` searches to return all
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_7_0/3242-fix-bug-that-mutates-searchparam-map.yaml:4]:
```suggestion
title: "Fixed bug that caused queries that checked Elasticsearch when setting `_total=accurate` searches to return all
```

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirSearchDaoR4Test.java [hunk 6]
```diff
@@ -37,6 +40,63 @@ public void testDaoCallRequiresTransaction() {
 		assert !TransactionSynchronizationManager.isActualTransactionActive();
 	}
 
+	//TODO - remove
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirSearchDaoR4Test.java:43]: is this a valid todo?

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java [hunk 7]
```diff
@@ -89,6 +90,43 @@ public SearchParameterMap() {
 		super();
 	}
 
+	/**
+	 * Creates and returns a copy of this map
+	 * @return
```
Comment (tadgh) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/SearchParameterMap.java:95]: incomplete docstring, remove the return or fill it out

**Review by tadgh — APPROVED** [review]
Approved pending super minot changes.
