### PR TITLE
Avoid a crash reading an unknown ID on partitioned server

### LINKED ISSUE #1953: (partitioned server) NullPointerException on BaseHapiFhirResourceDao when querying for non existing resource
In a partitioned server, a query for a non existing resource as following:
http://localhost:8080/partID/Patient/254

Returns an error:
"Failed to call access method: java.lang.NullPointerException"

This happens becuse in BaseHapiFhirResourceDao, the block:
```
		if (entity == null) {
			throw new ResourceNotFoundException(theId);
		}

```
Shall be placed before the block just above "Verify that the resource is for the correct partition" (there's a call to the null entity).

 - HAPI FHIR Version: 5.1.0-SNAPSHOT (master)

### PR DESCRIPTION
**Pull request by jamesagnew**
Fix #1953

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java [hunk 1]
```diff
@@ -1164,10 +1168,6 @@ public BaseHasResource readEntity(IIdType theId, boolean theCheckForForcedId, Re
 			}
 		}
 
-		if (entity == null) {
```
Comment (bbray) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java:1167]: This null check needs to be duplicated not moved.  

This actually creates another NPE issue if you request a resource that exists but not in the requested partition then `validateResourceType(entity);` fails (it does generate the correct debug message).  I'm working on the 5.2 branch which is a bit different but it looks like the `Validate.notNull(entity);` in this branch would fail in the same way.

**Review by bbray — CHANGES_REQUESTED** [review]

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java (hunk 1 above)
Comment (jamesagnew) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java:1167]: Interesting.. Will give that a shot
