### PR TITLE
3693 Search by id is returning a deleted resource with a client-generated id

### LINKED ISSUE #3693: Search by id is returning a deleted resource with a client generated id
**Describe the bug**
When searching for a deleted resource with a client generated id (i.e. added via PUT) using `_id`, the returned bundle includes the deleted resource in the total count.

**To Reproduce**
1. Create a Patient with a client-generated id via HTTP PUT (i.e. AAA)
2. Delete the Patient
3. Search for the deleted Patient using `_id` (issue persists when `Cache-Control:  no-cache`)
4. The returned bundle has a total count of 1 with no resources in the `entry` field

**Expected behavior**
The returned bundle should have a total value of 0 and no resources in the `entry` field

**Environment**
 - HAPI-FHIR: 6.0.1

### PR DESCRIPTION
**Pull request by nathandoef**
- Added functionality to optionally filter out deleted resources when resolving forced ids to persistent ids
- Bumps version

Closes #3693

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/custom/IForcedIdDaoCustom.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+ */
+
+public interface IForcedIdDaoCustom {
+
+	/**
+	 * This method returns a Collection where each row is an element in the collection. Each element in the collection
+	 * is an object array, where the order matters (the array represents columns returned by the query).
+	 * Deleted resources should not be filtered.
+	 */
+	Collection<Object[]> findAndResolveByForcedIdWithNoType(String theResourceType, Collection<String> theForcedIds);
```
Comment (jdar8) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/custom/IForcedIdDaoCustom.java:33]: Suggestion: should we rename this to reflect the fact that it does not filter deleted resource?

**Review by jdar8 — COMMENTED** [review]
Needs a changelog, but other than that, looks good to me

**Review by fil512 — APPROVED** [review]
Review done in person with FIXMEs
