### PR TITLE
4234 consent in conjunction with versionedapiconverterinterceptor fails

### LINKED ISSUE #4234: Consent in Conjunction with VersionedApiConverterInterceptor fails.
If both a consent interceptor, and a versioned api converter interceptor are loaded, the following stack trace occurs when attempting to make the following request:

```http
http://base:8000/Patient
> Accept: application/fhir+json; fhirVersion=3.0
```

```
"HAPI-1731: This context is for FHIR version \"R4\" but the class \"org.hl7.fhir.dstu3.model.Bundle\" is for version \"DSTU3\""
```

This is caused by the ordering of the interceptors. A quick fix is to have the converter occur post-consent.

### PR DESCRIPTION
**Pull request by tadgh**
Closes #4234 

* Order the converter interceptor to go after the consent interceptor
* Changelog
* Test

### CODE REVIEW

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/ConsentInterceptorResourceProviderR4Test.java [hunk 1]
```diff
@@ -282,6 +283,21 @@ public void testSearchMaskSubject() {
...
+		});
+		ourRestServer.getInterceptorService().registerInterceptor(myConsentInterceptor);
+		ourRestServer.getInterceptorService().registerInterceptor(new VersionedApiConverterInterceptor());
+
+		myClient.create().resource(new Patient().setGender(Enumerations.AdministrativeGender.MALE).addName(new HumanName().setFamily("1"))).execute();
+		Bundle response = myClient.search().forResource(Patient.class).count(1).accept("application/fhir+json; fhirVersion=3.0").returnBundle(Bundle.class).execute();
+
+		assertEquals(1, response.getEntry().size());
+		assertNull(response.getTotalElement().getValue());
+
```
Comment (TipzCM) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/ConsentInterceptorResourceProviderR4Test.java:298]: Do we not need to verify it hit the consent service see count?

**Review by TipzCM — APPROVED** [review]
