### PR TITLE
Fix exception when contained indexing met hibernate search.

### LINKED ISSUE #3371: NPE when combining hibernate search and contained resources
New lucene indexing NPEs with contained resources.

**To Reproduce**
In ModelConfig enable:
- enable `indexOnContainedResources`
- and `indexOnContainedResourcesRecursively`
In DaoConfig enable `advancedLuceneIndexing`
POST /Observation, contained Patient
{
  "resourceType": "Observation",
  "contained": [
    {
      "resourceType": "Patient",
      "id": "contained-patient",
      "name": [{
        "family": "Smith"
      }]
    }
  ],
  "subject": { "reference": "#contained-patient" }
}

**Expected behavior**
200 success

** Actual behaviour**

```
Caused by: org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteCallback(HapiTransactionService.java:149) [4 skipped]
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:83)
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:75)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.create(BaseHapiFhirResourceDao.java:212)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.create(BaseHapiFhirResourceDao.java:192)
... snip ...
**Caused by: org.hibernate.search.util.common.SearchException: HSEARCH700083: Exception while building document for entity 'ResourceTable#1335': HSEARCH600039: Invalid field reference for this document element: this document element has path 'sp.subject.general-practitioner', but the referenced field has a parent with path 'sp'.**
```

Hapi Fair 5.7.0-SNAPSHOT-PRE.

### PR DESCRIPTION
**Pull request by michaelabuckley**
Fixes #3371

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4SearchWithElasticSearchIT.java [hunk 1]
```diff
@@ -125,6 +125,9 @@
 	public void beforePurgeDatabase() {
 		purgeDatabase(myDaoConfig, mySystemDao, myResourceReindexingSvc, mySearchCoordinatorSvc, mySearchParamRegistry, myBulkDataExportSvc);
 		myDaoConfig.setAdvancedLuceneIndexing(true);
+		// we don't support chained or contained yet, but turn it on to test we don't blow up.
+		myDaoConfig.getModelConfig().setIndexOnContainedResources(true);
```
Comment (fil512) [inline hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4SearchWithElasticSearchIT.java:129]: Should we throw a warning in the logs if we start out with this config?  Or maybe add a ConfigDiagnosis entry for this?

**Review by fil512 — APPROVED** [review]

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4SearchWithElasticSearchIT.java (hunk 1 above)
Comment (michaelabuckley) [reply hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4SearchWithElasticSearchIT.java]: The search should still work.  It just won't use Lucene.  It will all happen in JPA.
