### PR TITLE
mdm delete with cascade bug fix

### LINKED ISSUE #6539: MDM - Deleting resources when mdm and delete cascade is enabled causes errors
Reproduction steps

* enable MDM
* enable delete cascade
* create a single patient (so it has exactly 1 mdm link)
* create a resource that references this patient in some way
* delete the patient

Result: error thrown (unable to obtain table lock for deleting mdmlink)

### PR DESCRIPTION
**Pull request by TipzCM**
closes #6539

### CODE REVIEW

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java [hunk 1]
```diff
@@ -199,26 +200,44 @@ public void blockManualGoldenResourceManipulationOnUpdate(
...
-					 * We will add the removed id to the deleted list so that
-					 * the deletedResourceId list is accurte for what has been
-					 * deleted.
-					 *
-					 * This benefits other interceptor writers who might want
-					 * to do their own resource deletion on this same pre-commit
-					 * hook (and wouldn't be aware if we did this deletion already).
-					 */
-					theTransactionDetails.addDeletedResourceId(goldenPid);
+		Map<IResourcePersistentId, Set<IResourcePersistentId>> goldenResourceIds2linkedSourceIds =
```
Comment (dotasek) [inline hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:210]: Nitpick: It's a complex name, but honestly, I can't think of a better one.

**Review by dotasek — APPROVED** [review]
Looks good to me.

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java (hunk 1 above)
Comment (TipzCM) [reply hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:210]: sorry

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml [hunk 2]
```diff
@@ -0,0 +1,12 @@
+---
+type: fix
+issue: 6539
+title: "Previously, deleting an MDM managed Patient
+        could result in errors if:
+        * the related Golden record had no other resources linked to it
+            (ie, this is the final linked resource)
+        * there existed other resources referencing the to-be-deleted resource
+        * 'cascade delete` was enabled (to clean up related resources)
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml:9]:
```suggestion
        * `cascade delete` was enabled (to clean up related resources)
```

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+        
+        This has now been fixed.
+"
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml:12]: question: Have you checked that this changelog actually renders as you expect it to?

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java (hunk 1 above)
Comment (tadgh) [inline hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:210]:
```suggestion
		Map<IResourcePersistentId, Set<IResourcePersistentId>> goldenIdToSourceIdsMap =
```

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java [hunk 4]
```diff
@@ -254,25 +273,25 @@ public void deleteMdmLinks(
...
-					Set<IResourcePersistentId> goldenIdsToDelete =
+					Map<IResourcePersistentId, Set<IResourcePersistentId>> goldenIdsToDelete2linkedSrcIds =
 							theTransactionDetails.getUserData(GOLDEN_RESOURCES_TO_DELETE);
-					if (goldenIdsToDelete == null) {
-						goldenIdsToDelete = new HashSet<>();
+					if (goldenIdsToDelete2linkedSrcIds == null) {
+						goldenIdsToDelete2linkedSrcIds = new ConcurrentHashMap<>();
+					}
+					if (!goldenIdsToDelete2linkedSrcIds.containsKey(goldenPid)) {
+						goldenIdsToDelete2linkedSrcIds.put(goldenPid, new HashSet<>());
```
Comment (tadgh) [inline hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:291]: issue: remove numeric value from variable name.

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java [hunk 5]
```diff
@@ -199,26 +200,44 @@ public void blockManualGoldenResourceManipulationOnUpdate(
 	@Hook(Pointcut.STORAGE_PRECOMMIT_RESOURCE_DELETED)
 	public void deletePostCommit(
 			RequestDetails theRequest, IBaseResource theResource, TransactionDetails theTransactionDetails) {
-		Set<IResourcePersistentId> goldenResourceIds = theTransactionDetails.getUserData(GOLDEN_RESOURCES_TO_DELETE);
+		if (!myMdmSettings.isSupportedMdmType(myFhirContext.getResourceType(theResource))) {
+			// if it's not an mdm supported type, leave immediately;
+			// we're only deleting goldenids / links if the source ids (which are mdm supported)
+			// are being deleted
+			return;
+		}
```
Comment (tadgh) [inline hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:208]: nitpick: this is the inverse of the logic of the STORAGE_PRESTORAGE_RESOURCE_DELETED (you exit early here, and the other hook has the positive equivalent of the conditional. Recommend unifying them to a single method, either early exit on negative conditional, or positive conditional gated logic.

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java [hunk 6]
```diff
@@ -199,26 +200,44 @@ public void blockManualGoldenResourceManipulationOnUpdate(
...
-					theTransactionDetails.addDeletedResourceId(goldenPid);
+		Map<IResourcePersistentId, Set<IResourcePersistentId>> goldenResourceIds2linkedSourceIds =
+				theTransactionDetails.getUserData(GOLDEN_RESOURCES_TO_DELETE);
+		if (goldenResourceIds2linkedSourceIds != null) {
+			IResourcePersistentId sourcePid =
+					myIdHelperSvc.getPidOrNull(RequestPartitionId.allPartitions(), theResource);
+			if (sourcePid != null) {
+				for (IResourcePersistentId goldenPid : goldenResourceIds2linkedSourceIds.keySet()) {
+					if (goldenResourceIds2linkedSourceIds.get(goldenPid).contains(sourcePid)) {
+						// we only delete the golden resource if it's matched to a source id;
```
Comment (tadgh) [inline hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:218]: question: How would the golden resource even get into this list if it was not attached to a source ID that was just deleted?

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml (hunk 3 above)
Comment (TipzCM) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml:12]: i have changed the format

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java (hunk 4 above)
Comment (TipzCM) [reply hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:291]: removed

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java (hunk 5 above)
Comment (TipzCM) [reply hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:208]: switched to use positive gates

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java (hunk 6 above)
Comment (TipzCM) [reply hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java:218]: This is a bit of 'futureproofing'.

Currently MDM only really works with Patients. So the first gate (`isSupportedMdmType`) would be sufficient in and of itself.

But should the patient be referenced by another resource (that isn't also a patient and *is* MDM managed), these referenced resources will still trigger this pointcut before the actual source resource (related to this golden resource) is finished being deleted (and thus, the MdmLink table is still locked).

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java (hunk 1 above)
Comment (TipzCM) [reply hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java]: changed

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml (hunk 2 above)
Comment (TipzCM) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml]: updated

File: hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java (hunk 6 above)
Comment (tadgh) [reply hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java]: I'm confused, MDM absolutely works with other resources than patients, what makes you think patient is unique for the purposes of MDM?

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml [hunk 7]
```diff
@@ -0,0 +1,12 @@
+---
+type: fix
+issue: 6539
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml:3]: needs `jira: SMILE-XXXX` tag if there is a related jira.

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptorIT.java [hunk 8]
```diff
@@ -97,18 +113,124 @@ private MdmLink getLinkByTargetId(IBaseResource theResource) {
...
+			// link some encounters
+			for (String id : new String[]{"P1", "P2"}) {
+				Encounter enc = new Encounter();
+				enc.setSubject(new Reference("Patient/" + id));
+				myEncounterDao.create(enc, new SystemRequestDetails());
+			}
+
+			// test
+			// delete the patient
+			DeleteMethodOutcome outcome = myPatientDao.deleteByUrl("Patient?_id=P1,P2", details);
```
Comment (tadgh) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptorIT.java:217]: What happens in this test if you only delete `Patient?_id=P1` with cascade enabled? I would expect P2, the golden resource, and the P2 encounter to survive. Can you write that test case?

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptorIT.java [hunk 9]
```diff
@@ -97,18 +113,124 @@ private MdmLink getLinkByTargetId(IBaseResource theResource) {
...
+
+			assertTrue(outcome.getOperationOutcome() instanceof OperationOutcome);
+			OperationOutcome out = (OperationOutcome) outcome.getOperationOutcome();
+			assertTrue(out.getIssue().stream()
+				.anyMatch(f -> f.getDiagnostics().toLowerCase().contains("successfully deleted 2 resource(s)")));
```
Comment (tadgh) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptorIT.java:222]: question: I know this is likely not new, but .... like 5 resources were deleted here, weird that it would say 2.

**Review by tadgh — APPROVED** [review]

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptorIT.java (hunk 8 above)
Comment (TipzCM) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptorIT.java]: added

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptorIT.java (hunk 9 above)
Comment (TipzCM) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptorIT.java]: I think this is the result of using a 'fake' cascading interceptor.

The real one actually goes through and adds additional messages. But that code isn't in the test, so it only says it deletes 2 resources (no matter what)

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml (hunk 7 above)
Comment (TipzCM) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_8_0/6539-handle-mdm-link-deletion-when-delete-cascade-enabled.yaml:3]: added
