### PR TITLE
Fix Patch in bundle to return Response Entry

### LINKED ISSUE #3574: PATCH request inside a Bundle Transaction doesn't provide proper success response.
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
After a successful PATCH operation request inside a  Bundle transaction, the  Transaction response doesn't include response entry for that operation.
On the other hand, PUT works fine and includes a response entry.

**PATCH Transaction Request**

```
{
	"resourceType": "Bundle",
	"type": "transaction",
	"entry": [{
		"fullUrl": "Patient/e642ec07-c4d1-4f3f-bae6-4cd9e7f9d0d4",
		"resource": {
			"resourceType": "Binary",
			"contentType": "application/json-patch+json",
			"data": "W3sib3AiOiJyZXBsYWNlIiwicGF0aCI6IlwvdGVsZWNvbVwvMFwvdmFsdWUiLCJ2YWx1ZSI6IjQwMTEyMzQ1NiJ9XQ=="
		},
		"request": {
			"method": "PATCH",
			"url": "Patient/e642ec07-c4d1-4f3f-bae6-4cd9e7f9d0d4"
		}
	}]
}
```

**Response**
```
{
    "resourceType": "Bundle",
    "id": "43767579-b8bd-4477-9cb8-409c44535433",
    "type": "transaction-response",
    "link": [
        {
            "relation": "self",
            "url": "http://hapi.fhir.org/baseR4"
        }
    ]
}
```

**PUT Transaction Request**
```
{
	"resourceType": "Bundle",
	"type": "transaction",
	"entry": [{
		"fullUrl": "Patient/e642ec07-c4d1-4f3f-bae6-4cd9e7f9d0d4",
		"resource": {
			"resourceType": "Patient",
			"id": "e642ec07-c4d1-4f3f-bae6-4cd9e7f9d0d4",
			"meta": {
				"versionId": "9",
				"lastUpdated": "2022-04-29T18:39:04.724+00:00",
				"source": "#VGrUe9jNHLmnalmb"
			},
			"text": {
				"status": "generated",
				"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><div class=\"hapiHeaderText\">Adam <b>ADAMS </b></div><table class=\"hapiPropertyTable\"><tbody><tr><td>Address</td><td><span>NAIROBI </span><span>Kenya </span></td></tr><tr><td>Date of birth</td><td><span>14 February 2020</span></td></tr></tbody></table></div>"
			},
			"active": true,
			"name": [{
				"family": "Adams",
				"given": [
					"Adam"
				]
			}],
			"telecom": [{
				"system": "phone",
				"value": "401123456-01"
			}],
			"gender": "male",
			"birthDate": "2020-02-14",
			"address": [{
				"city": "NAIROBI",
				"country": "Kenya"
			}]
		},
		"request": {
			"method": "PUT",
			"url": "Patient/e642ec07-c4d1-4f3f-bae6-4cd9e7f9d0d4",
		}
	}]
}
```
**Response** 
```
{
    "resourceType": "Bundle",
    "id": "be5b83f0-a3d3-440e-a542-8b9e54e166a6",
    "type": "transaction-response",
    "link": [
        {
            "relation": "self",
            "url": "http://hapi.fhir.org/baseR4"
        }
    ],
    "entry": [
        {
            "response": {
                "status": "200 OK",
                "location": "Patient/e642ec07-c4d1-4f3f-bae6-4cd9e7f9d0d4/_history/12",
                "etag": "12",
                "lastModified": "2022-04-29T18:39:04.724+00:00"
            }
        }
    ]
}
```

**To Reproduce**
1. Use the requests shown above to do a `POST` request to the https://hapi.fhir.org/baseR4/  and see the response.

**Expected behavior**
Transaction response Bundle should include an entry response for the PATCH operation for the clients to be able to get the updated version, etag and modified time.
e.g. Like the PUT response above.
```
{
"entry": [
        {
            "response": {
                "status": "200 OK",
                "location": "Patient/e642ec07-c4d1-4f3f-bae6-4cd9e7f9d0d4/_history/12",
                "etag": "12",
                "lastModified": "2022-04-29T18:39:04.724+00:00"
            }
        }
    ]
}
```

**Screenshots**

**Environment (please complete the following information):**
 http://hapi.fhir.org/baseR4
    HAPI FHIR Test/Demo Server R4 Endpoint
    HAPI FHIR Server 6.0.0-PRE8-SNAPSHOT/3f58e277e6/2022-03-23
 - Browser Chrome & Postman tool

**Additional context**

### PR DESCRIPTION
**Pull request by tadgh**
Closes #3574 

* Add missing handling for outgoing bundle response for patch operations. 
* Modify test to validate new scenario. 
* Add changelog

### CODE REVIEW

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/BaseTransactionProcessor.java [hunk 1]
```diff
@@ -1184,6 +1193,14 @@ protected EntriesToProcessMap doTransactionWriteOperations(final RequestDetails
 		}
 	}
 
+	private boolean shouldSwapBinaryToActualResource(IBaseResource res, String resourceType, IIdType nextResourceId) {
+		if ("Binary".equalsIgnoreCase(resourceType) && nextResourceId.hasResourceType() && !nextResourceId.getResourceType().equalsIgnoreCase("Binary")) {
```
Comment (fil512) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/BaseTransactionProcessor.java:1197]:
```suggestion
		if ("Binary".equalsIgnoreCase(resourceType) && nextResourceId.isResourceType("Binary")) {
```

**Review by fil512 — APPROVED** [review]

**Review by jingtang10 — COMMENTED** [review]
The test case looks good to me. Thanks for the fix @tadgh!

FYI @aditya-07
