### PR TITLE
7787: Fix topic subscription partition escape

### LINKED ISSUE #7787: Topic Subscriptions break through partition boundaries
When partitioning is enabled, a topic Subscription stored in one partition can incorrectly receive delivery notifications for resources created in a different partition

### PR DESCRIPTION
**Pull request by another-luis**
A topic Subscription in one partition was incorrectly triggered by resources created in a different partition because SubscriptionTopicDispatcher fetched all subscriptions globally without filtering by partition. Added a partition guard in matchFiltersAndDeliver() to skip delivery when the triggering resource's partition does not match the subscription's partition. Includes regression test SubscriptionTopicPartitionR5IT.

Fixes #7787

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+		myStorageSettings.setExpungeEnabled(new JpaStorageSettings().isExpungeEnabled());
+		myStorageSettings.setAllowMultipleDelete(new JpaStorageSettings().isAllowMultipleDelete());
+
+		// prevent the parent from trying to delete already-expunged resources
+		mySubscriptionIds.clear();
+		super.afterUnregisterRestHookListener();
+	}
+
+	/**
+	 * Regression test for: Topic Subscription Partition Escape (issue #8611)
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java:76]: Ref to Smile issue is not appropriate. Change to hapi issue

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+		// fires after dispatch() returns. If the partition guard blocks delivery, nothing is
+		// ever queued on the delivery channel, so the assertion is safe immediately.
+		myPartitionInterceptor.setPartitionId(REQ_PART_1);
+		Patient patient = new Patient();
+		patient.setActive(true);
+		createResource(patient, false);
+
+		// Give the async delivery thread time to complete any in-flight outbound call,
+		// so the assertion below fires before teardown if the partition guard is broken.
+		Thread.sleep(300);
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java]: Thread.sleep is a blocker in sonarqube. Use awaitility lib for tests

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/8611-fix-topic-subscription-partition-escape.yaml [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+type: fix
+issue: 8611
+title: "Previously, when partitioning was enabled, a topic Subscription stored in one partition could
```
Comment (jmarchionatto) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/8611-fix-topic-subscription-partition-escape.yaml:4]: Reads as if that's always wrong, but it's only wrong for non-cross-partition subscriptions. A clearer phrasing would be something
like:

Previously, when partitioning was enabled, a topic Subscription could incorrectly receive delivery notifications for resources created in a different partition, even when the Subscription was not configured as cross-partition. This has been fixed.

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/8611-fix-topic-subscription-partition-escape.yaml [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+type: fix
```
Comment (jmarchionatto) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/8611-fix-topic-subscription-partition-escape.yaml:2]: Wrong location. Move under 8_10_0

File: hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/topic/SubscriptionTopicDispatcher.java [hunk 5]
```diff
@@ -115,6 +116,15 @@ private ISendResult matchFiltersAndDeliver(
 			SubscriptionTopicDispatchRequest theSubscriptionTopicDispatchRequest,
 			ActiveSubscription theActiveSubscription) {
 
+		CanonicalSubscription subscription = theActiveSubscription.getSubscription();
+		RequestPartitionId requestPartitionId = theSubscriptionTopicDispatchRequest.getRequestPartitionId();
+		if (requestPartitionId != null
+				&& requestPartitionId.hasPartitionIds()
+				&& !subscription.isCrossPartitionEnabled()
+				&& !requestPartitionId.hasPartitionId(subscription.getRequestPartitionId())) {
+			return ISendResult.FAILURE;
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/topic/SubscriptionTopicDispatcher.java:125]: suggestion: debug log ("skipping delivery: subscription lives in partition X, event in Y")

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java [hunk 6]
```diff
@@ -0,0 +1,126 @@
...
+import org.hl7.fhir.r5.model.Patient;
+import org.hl7.fhir.r5.model.SubscriptionTopic;
+import org.junit.jupiter.api.AfterEach;
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.Test;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+// Created by claude-sonnet-4-6
+class SubscriptionTopicPartitionR5IT extends BaseSubscriptionsR5Test {
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java:34]: No positive-path coverage in the new integration test
SubscriptionTopicPartitionR5IT has a single test, the negative case. The change silently introduces these paths that are not covered:

1. Same-partition event → subscription fires
2. crossPartitionEnabled = true subscription → fires regardless of event partition 
3. requestPartitionId == null (no partition info on dispatch) → fires (backward compat)
4. requestPartitionId with multiple partition ids including subscription's partition → fires

Any one of these could regress without this test noticing. Add at least the "same partition fires" and "cross-partition subscription fires" cases.

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java [hunk 7]
```diff
@@ -0,0 +1,126 @@
...
+		myPartitionSettings.setPartitioningEnabled(false);
+
+		myStorageSettings.setExpungeEnabled(true);
+		myStorageSettings.setAllowMultipleDelete(true);
+		myDaoRegistry.getSystemDao().expunge(new ExpungeOptions().setExpungeEverything(true), null);
+		myStorageSettings.setExpungeEnabled(new JpaStorageSettings().isExpungeEnabled());
+		myStorageSettings.setAllowMultipleDelete(new JpaStorageSettings().isAllowMultipleDelete());
+
+		// prevent the parent from trying to delete already-expunged resources
+		mySubscriptionIds.clear();
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java]: nitpick: couples the test to the base class's teardown invariants. Fragile — wrap in a protected helper or reorder teardown.

**Review by jmarchionatto — APPROVED** [review]
Looks good in general. Approved pending a couple of needed fixes. a few improvements suggested.

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/8611-fix-topic-subscription-partition-escape.yaml (hunk 4 above)
Comment (another-luis) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/8611-fix-topic-subscription-partition-escape.yaml:2]: Done

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/8611-fix-topic-subscription-partition-escape.yaml (hunk 3 above)
Comment (another-luis) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_10_0/8611-fix-topic-subscription-partition-escape.yaml:4]: Done

File: hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/topic/SubscriptionTopicDispatcher.java (hunk 5 above)
Comment (another-luis) [reply hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/topic/SubscriptionTopicDispatcher.java:125]: There can be multiple partitions involved. Logging the the lists for each.

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java (hunk 1 above)
Comment (another-luis) [reply hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java:76]: Done

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java (hunk 6 above)
Comment (another-luis) [reply hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java:34]: Done

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java (hunk 7 above)
Comment (another-luis) [reply hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java]: Addressed.

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java (hunk 2 above)
Comment (another-luis) [reply hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java]: ok. Done.

Having said that, I noticed that the Thread.sleep() pattern is al over the place in tests - that where I copied it from. SonarQube must have an exception.

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java (hunk 7 above)
Comment (another-luis) [reply hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java]: Done

File: hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java (hunk 2 above)
Comment (another-luis) [reply hapi-fhir-jpaserver-test-r5/src/test/java/ca/uhn/fhir/jpa/subscription/resthook/SubscriptionTopicPartitionR5IT.java]: Done

**Review by tadgh — APPROVED** [review]
