### PR TITLE
fix replace-references operation for high cardinality elements 

### LINKED ISSUE #6672: for high cardinality elements $hapi.fhir.replace-references overwrites the whole collection of references instead of replacing a specific element
1. Use the following transaction bundle to create 2 organizations and a patient that that references the organizations in `generalPractitioner` field: 

```
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [
        {
            "fullUrl": "Organization/org1",
            "resource": {
                "resourceType": "Organization",
                "id": "org1",
                "name": "Organization 1"
            },
            "request": {
                "method": "PUT",
                "url": "Organization/org1"
            }
        },
        {
            "fullUrl": "Organization/org2",
            "resource": {
                "resourceType": "Organization",
                "id": "org2",
                "name": "Organization 2"
            },
            "request": {
                "method": "PUT",
                "url": "Organization/org2"
            }
        },
        {
            "fullUrl": "Patient/pat-mult-gen-practitioner",
            "resource": {
                "resourceType": "Patient",
                "id": "pat-mult-gen-practitioner",
                "generalPractitioner": [
                    {
                        "reference": "Organization/org1"
                    },
                    {
                        "reference": "Organization/org2"
                    }
                ]
            },
            "request": {
                "method": "PUT",
                "url": "Patient/pat-mult-gen-practitioner"
            }
        }
    ]
}
```

2. Call `$hapi.fhir.replace-references` operation to replace references of org1 to org3: 

`POST <fhir_host>/$hapi.fhir.replace-references`

```
{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "source-reference-id",
            "valueString": "Organization/org1"
        },
        {
            "name": "target-reference-id",
            "valueString": "Organization/org3"
        }
    ]
}
```

4. Call `GET <fhir_host>/Patient/pat-mult-gen-practitioner` to check if reference to org2 replaced with org3

### Actual Result:  

All the elements in  `generatePractitioner` array are wiped and a reference to org3 is added (reference to org2 is lost)

```
{
                "resourceType": "Patient",
                "id": "pat-mult-gen-practitioner",
                "meta": {
                    "versionId": "3",
                    "lastUpdated": "2025-01-13T12:06:07.150-05:00",
                    "source": "#HJarEoO6nIrPjv0n"
                },
                "generalPractitioner": [
                    {
                        "reference": "Organization/org3"
                    }
                ]
            }
```

### Expected result:

The patient should have 2 references in generalPractitioner, a ref to org3 (replacing the ref to org1) and a ref to org2.

### PR DESCRIPTION
**Pull request by mrdnctrk**
closes #6672 

- Added a check in replace-references patch builder for the cardinality of the element that contains the reference. If the element is a high cardinality one then a specific filter is appended to the FHIR path for the replace operation. This filter prevents overwriting all the references in the element and just replaces the specific element containing the reference to be replaced. 
- Also fixed a bug where the replace-references endpoint was failing with a 500 Internal error exception (nstead of 400 InvalidRequest ) if one of the required parameters is missing.
- Added tests.

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/JpaSystemProvider.java [hunk 1]
```diff
@@ -205,13 +205,14 @@ public IBaseParameters replaceReferences(
...
-		if (isBlank(theSourceId)) {
+	private static void validateReplaceReferencesParams(
+			IPrimitiveType<String> theSourceId, IPrimitiveType<String> theTargetId) {
+		if (theSourceId == null || isBlank(theSourceId.getValue())) {
 			throw new InvalidRequestException(Msg.code(2583) + "Parameter '"
 					+ OPERATION_REPLACE_REFERENCES_PARAM_SOURCE_REFERENCE_ID + "' is blank");
 		}
 
-		if (isBlank(theTargetId)) {
+		if (theTargetId == null || isBlank(theTargetId.getValue())) {
```
Comment (TipzCM) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/JpaSystemProvider.java:215]: isBlank already checks for nulls, so this null check is unneeded

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/replacereferences/ReplaceReferencesPatchBundleSvc.java [hunk 2]
```diff
@@ -115,6 +115,28 @@ private static boolean matches(ResourceReferenceInfo refInfo, IIdType theSourceI
...
+			// filter to the path. If we don't do this, all the existing references in the element would be lost as a
+			// result of getting replaced with the new reference, and that is not the behaviour we want.
+			// e.g. "Observation.performer.where(reference='Practitioner/123')"
+			return String.format(
+					"%s.where(reference='%s')",
+					path,
+					theRefInfo.getResourceReference().getReferenceElement().getValueAsString());
+		}
+		// the element allows max cardinality of 1, so the whole element can be safely replaced
+		return path;
```
Comment (TipzCM) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/replacereferences/ReplaceReferencesPatchBundleSvc.java:137]: Q: Is 0 a valid max cardinality that could be returned?

**Comment by TipzCM** [comment]
you probably want to change your pr description to instead have "closes #6672" (not "issue...")

We use this specific format to find the issue that is to be closed when the pr merges.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/JpaSystemProvider.java (hunk 1 above)
Comment (mrdnctrk) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/JpaSystemProvider.java:215]: here isBlank checks  the nullness of`theTargetId.getValue()` but `theTargetId` is itself null if it is not provided as a parameter (theTargetId.getValue() throws null pointer exception even before isBlank is called). That's why I added it.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/replacereferences/ReplaceReferencesPatchBundleSvc.java (hunk 2 above)
Comment (mrdnctrk) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/replacereferences/ReplaceReferencesPatchBundleSvc.java:137]: No, 0 doesn't seem to be meaningful max cardinality. The FHIR spec uses the following as the cardinalities,`0..1, 0..*, 1..1, and 1..*` ([src](https://build.fhir.org/conformance-rules.html#cardinality)). The code we have uses 1 as the default and uses the sentinel value of -1 to denote unlimited cardinality.
