### PR TITLE
Fixed an issue where bundles containing an operation outcome from a search get blocked from access.

### LINKED ISSUE #6799: Bundles containing an operation outcome resource from a search get blocked from access.
**Describe the bug**
If a search request is made and the bundle includes an OperationOutcome, access is denied. This occurs if the **_STORAGE_PRESHOW_RESOURCES_** hook is invoked and the entries of the Bundle are passed into the requestDetails params as a list of resources.

This causes `AuthorizationInterceptor.hookPreShow()` to go through each resource and verify that permission is granted to view each resource, including the OperationOutcome. But without explicit permission to view the OperationOutcome, the search results in a 403 error. 

**Expected behavior**
A search that contains an OperationOutcome should result in a 200 OK response and not a 403 access denied error.

### PR DESCRIPTION
**Pull request by AbayomiE-T**
When a search request is made and the **_STORAGE_PRESHOW_RESOURCES_** hook is invoked, the results of that search (that may include an OperationOutcome) are received as list of resources instead of a bundle in the receiving method, `AuthorizationInterceptor.hookPreShow()`. 

Each of the resources, including the OperationOutcome, will pass through security to verify access. This MR fixes the issue where explicit permission has to be given to view an OperationOutcome in a search if the search passes through the **_STORAGE_PRESHOW_RESOURCES_** hook. 

Closes #6799

### CODE REVIEW

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptor.java [hunk 1]
```diff
@@ -577,21 +582,37 @@ private enum OperationExamineDirection {
...
 		if (!shouldExamineChildResources) {
-			return Collections.singletonList(theResponseObject);
+			return toListOfResourcesAndExcludeOperationOutcomeBasedOnRestOperationType(
+					theResponseObject, theRequestDetails);
 		}
 
 		return toListOfResourcesAndExcludeContainer(theResponseObject, fhirContext);
 	}
 
+	private static List<IBaseResource> toListOfResourcesAndExcludeOperationOutcomeBasedOnRestOperationType(
```
Comment (TipzCM) [inline hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptor.java:600]: Do all these methods need to be static?

It looks like they've been created via the refactor tool.

If it's too much of a change to make them all non-static (since it looks like other methods are already static) it's fine. But i don't think they should be static in this case.

**Review by TipzCM — APPROVED** [review]

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptor.java (hunk 1 above)
Comment (AbayomiE-T) [reply hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptor.java:600]: Yeah the `RuleImpOp `class uses `toListOfResourcesAndExcludeContainerUnlessStandalone()` inside of a static method. It doesn't use an instance of AuthorizationInterceptor to use `toListOfResourcesAndExcludeContainerUnlessStandalone()`.

I had to make this new method static so it can be used inside `toListOfResourcesAndExcludeContainerUnlessStandalone()`

File: hapi-fhir-validation/src/test/java/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptorR4Test.java [hunk 2]
```diff
@@ -4242,12 +4245,50 @@ public void testToListOfResourcesAndExcludeContainer_withSearchSetContainingPati
...
-		List<IBaseResource> resources = AuthorizationInterceptor.toListOfResourcesAndExcludeContainerUnlessStandalone(searchSet, ourCtx);
+		List<IBaseResource> resources = AuthorizationInterceptor.toListOfResourcesAndExcludeContainerUnlessStandalone(searchSet, ourCtx, requestDetails);
 		assertEquals(2, resources.size());
 		assertTrue(resources.contains(patient1));
 		assertTrue(resources.contains(patient2));
 	}
 
+	@ParameterizedTest
+	@MethodSource("provideArgumentsForToListOfResourcesAndExcludeContainerUnlessStandalone")
+	public void testToListOfResourcesAndExcludeContainer_withREST_OPERATIONS_TO_EXCLUDE_OPERATION_OUTCOME_FROM_SECURITY_returnsNoOperationOutcome(
```
[the remark this answers is not in the document]
Comment (AbayomiE-T) [reply hapi-fhir-validation/src/test/java/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptorR4Test.java]: Right. I updated the method name. Is it more descriptive now?

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_2_0/6799-bundles-containing-an-operation-outcome-resource-from-a-search-get-blocked-from-access.yaml [hunk 3]
```diff
@@ -0,0 +1,4 @@
+---
+type: fix
+issue: 6799
+title: "Fixed an issue where bundles containing an operation outcome from a search get blocked from access."
```
[the remark this answers is not in the document]
Comment (AbayomiE-T) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_2_0/6799-bundles-containing-an-operation-outcome-resource-from-a-search-get-blocked-from-access.yaml]: I updated the wording of this to _"Fixed an issue where bundles containing an operation outcome from a search cannot be accessed without explicit
 read permissions given for the OperationOutcome resource."_. How does that sound?

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptor.java [hunk 4]
```diff
@@ -577,21 +579,37 @@ private enum OperationExamineDirection {
...
```
Comment (jamesagnew) [inline hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptor.java:597]: Please add a javadoc to this method explaining the behaviour and rationale for it. Future developers will thank you.

**Review by jamesagnew — APPROVED** [review]
