### PR TITLE
7220 fix odd behaviour with subscription trigger caused by search expiry

### LINKED ISSUE #7220: Fix odd behaviour with subscription trigger caused by search expiry
Fix search expiry logic

- still use create time for freshness.
- but also track last-access-time for actual deletion.  Some results take a long time to page through, and as long as last access was < 10 min, this should be legal.

Also, change logging levels from trace to error for better visibility.logging levels for these messages:

* `"Client requested unknown paging ID[{}]"` [ExceptionService.java#L38]
* `"Search has expired, submission is done"` [SubscriptionTriggeringSvcImpl.java#L373]

### PR DESCRIPTION
**Pull request by YalingPeiS**
**Background**

With large amount of search records, search results were expired prematurely before all the pages could be fetched.

**Fix search expiry logic**

- still use create time for freshness.
- but also track last-access-time for actual deletion. Some results take a long time to page through, and as long as last access was < 10 min, this should be legal.

Also, change logging levels from trace to error for better visibility.

Closes #7220

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java [hunk 1]
```diff
@@ -332,6 +334,10 @@ public List<JpaPid> getResources(
 
 		List<JpaPid> pids = fetchResultPids(theUuid, theFrom, theTo, theRequestDetails, search, theRequestPartitionId);
```
Comment (YalingPeiS) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java:336]: I couldn't find the existing search property `myExpiryOrNull` (db column `EXPIRE_OR_NULL`) being used anywhere in the code base other than in tests and an sql select statement, so instead of creating a new column in Search table, I am using `EXPIRE_OR_NULL` to keep track of the search result's expiry time based on the last access time.

The existing query to find search records for deletion has already taken into account of `EXPIRE_OR_NULL` in `SearchDao.findWhereCreatedBefore()`, so no code change in stale search deletion  process is needed.

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4QueryCountTest.java
Comment (YalingPeiS) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4QueryCountTest.java:1]: Keeping track of the last access time of the search results adds extra database hits.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/ExceptionService.java [hunk 2]
```diff
@@ -35,7 +35,7 @@ public ExceptionService(FhirContext theContext) {
 
 	@Nonnull
 	public ResourceGoneException newUnknownSearchException(String theUuid) {
-		ourLog.trace("Client requested unknown paging ID[{}]", theUuid);
+		ourLog.error("Client requested unknown paging ID[{}]", theUuid);
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/ExceptionService.java]: problem: it is not an error in the system for a client to make an illegal request.  If we change this to error, then an attacker could fill our error log by making repeated invalid requests.  This is a normal 410 error, and will be logged appropriately by the exception below.
```suggestion
		ourLog.debug("Client requested unknown paging ID[{}]", theUuid);
```

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4QueryCountTest.java
Comment (michaelabuckley) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4QueryCountTest.java:1]: Agree.  Is there anything we can do to reduce this?  Could we update the expiry less frequently?

File: hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/triggering/SubscriptionTriggeringSvcImpl.java [hunk 3]
```diff
@@ -370,7 +370,7 @@ private void processAsynchronous(
 			allResourceIds = mySearchCoordinatorSvc.getResources(
 					theJobDetails.getCurrentSearchUuid(), fromIndex, toIndex, null, requestPartitionId);
 		} catch (ResourceGoneException e) {
-			ourLog.trace("Search has expired, submission is done.");
+			ourLog.error("Search has expired, submission is done with error: {}", e.getMessage());
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/triggering/SubscriptionTriggeringSvcImpl.java]: problem: user errors are not system errors.  Expiry is normal operation.
```suggestion
			ourLog.debug("Search has expired, submission is done with error: {}", e.getMessage());
```

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4QueryCountTest.java
Comment (YalingPeiS) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoR4QueryCountTest.java:1]: Updated to only start tracking last-access-time when the search is halfway towards expiry.
The change also ensures that the SQL count in the unit tests are unchanged.

**Comment by YalingPeiS** [comment]
> Let's figure out if we can reduce the number of updates on the read-only path.

Updated track search last-access-time only when it is halfway towards expiry based on created time.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java [hunk 4]
```diff
@@ -332,6 +334,14 @@ public List<JpaPid> getResources(
...
 
+		// start tracking last-access time for this search when it is more than halfway to expire by created time
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java]:
```suggestion
		// start tracking last-access time for this search when it is more than halfway to expire by created time
		// we do this to avoid generating excessive write traffic on busy cached searches.
```

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java [hunk 5]
```diff
@@ -353,6 +357,20 @@ private List<JpaPid> fetchResultPids(
...
+	private void updateSearchExpiryOrNull(Search theSearch, RequestPartitionId theRequestPartitionId) {
+		// The created time may be null in some unit tests
+		if (theSearch.getCreated() != null) {
+			// start tracking last-access-time for this search when it is more than halfway to expire by created time
+			// we do this to avoid generating excessive write traffic on busy cached searches.
+			long expireAfterMillis = myStorageSettings.getExpireSearchResultsAfterMillis();
+			long createdCutoff = theSearch.getCreated().getTime() + expireAfterMillis;
+			if (createdCutoff - System.currentTimeMillis() < expireAfterMillis / 2) {
+				theSearch.setExpiryOrNull(DateUtils.addMinutes(new Date(), SEARCH_EXPIRY_OFFSET_MINUTES));
+				mySearchCacheSvc.save(theSearch, theRequestPartitionId);
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java:370]:
```suggestion
				// TODO: A nice future enhancement might be to make this flush be asynchronous
				mySearchCacheSvc.save(theSearch, theRequestPartitionId);
```
