### PR TITLE
SMILE-3459 Implemented -l parameter in validator. Added SnapshotGener…

### LINKED ISSUE #4003: CLI Validation against FHIR profile not working
**Describe the bug**

### PR DESCRIPTION
**Pull request by KGJ-software**
Implemented support for -l parameter. Added test to ensure local profile is used.

Closes #4003

### CODE REVIEW

**Comment by dotasek** [comment]
I would need to see some manner of test for this to verify that it's working.

I'd imagine that it would follow a similar format to: ca.uhn.fhir.cli.ValidateCommandTest testValidateLocalProfileR4() for example.

File: hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java [hunk 1]
```diff
@@ -229,7 +229,6 @@ protected List<ValidationMessage> validate(IValidationContext<?> theValidationCt
 			.setBestPracticeWarningLevel(getBestPracticeWarningLevel())
 			.setErrorForUnknownProfiles(isErrorForUnknownProfiles())
 			.setExtensionDomains(getExtensionDomains())
-			.setValidatorResourceFetcher(validatorResourceFetcher)
```
Comment (dotasek) [inline hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java:232]: This looks like it will cause breakage; ValidatorWrapper would have no way to have its ValidatorResourceFetcher set here.

File: hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/ValidateCommand.java [hunk 2]
```diff
@@ -164,7 +163,11 @@ public void run(CommandLine theCommandLine) throws ParseException {
 				case R4: {
 					FhirInstanceValidator instanceValidator = new FhirInstanceValidator(ctx);
 					val.registerValidatorModule(instanceValidator);
-					ValidationSupportChain validationSupport = new ValidationSupportChain(new DefaultProfileValidationSupport(ctx), new InMemoryTerminologyServerValidationSupport(ctx));
+					ValidationSupportChain validationSupport = new ValidationSupportChain(
+						new DefaultProfileValidationSupport(ctx),
+						new InMemoryTerminologyServerValidationSupport(ctx),
+						new LocalFileValidationSupport(ctx),
```
Comment (dotasek) [inline hapi-fhir-cli/hapi-fhir-cli-api/src/main/java/ca/uhn/fhir/cli/ValidateCommand.java:169]: I think, based on what I see below, that LocalFileValidationSupport and SnapshotGeneratingValidationSupport can be added optionally. Like it is when theCommandLine.hasOption("r") adds support with addValidationSupport.

File: hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java (hunk 1 above)
Comment (KGJ-software) [reply hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java:232]: setValidatorResourceFetcher is called below, I think the one I removed was merely a duplicate.

**Comment by KGJ-software** [comment]
@dotasek @nathandoef 

I think this PR is in a good place now.

**Review by dotasek — CHANGES_REQUESTED** [review]
See comments in code for details:

1) The ValidateCommandTest is perhaps a little too brittle. There's a less verbose check that might be sufficient.
2) LocalFileValidationSupport doesn't discriminate between types of resource, which could cause errors, and could be updated to be more robust. 
3) LocalFileValidationSupport should have its own unit test.

File: hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java (hunk 1 above)
Comment (markiantorno) [reply hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/validator/FhirInstanceValidator.java:232]: Might be a good opportunity to change this implementation of Validator wrapper to take a parameter argument, vs just chaining in 10+ vars here.

**Review by markiantorno — COMMENTED** [review]
So, if there are tests that already exist that test that validation works when you provide a local profile, I wouldn't test that again. 

What I would suggest is going even more granular and tests the changes specifically, test the 'l' param is detected and causes the load to occure, test the struct def is loaded correctly, and test that the validator is called with the appropriate structure def used.

If we add another validation here, it will add more time to the overall tests. We want to keep them as lean as possible.

**Review by dotasek — APPROVED** [review]
This looks good to me. If @markiantorno approves as well, we're good to go!

**Review by markiantorno — APPROVED** [review]
