### PR TITLE
fix: adjust grouped search handling for HAPI SearchQueryBuilder SQL issue

### LINKED ISSUE #6709: _sort=near throws exception when used in offset search
**Describe the bug**
When using a near search WITH `_sort=near` and WITH offset search a SQLGrammarException is thrown.

**To Reproduce**
Start a hapi(jpastarter) server and search: http://localhost:8080/fhir/Location?near=50.097%7C8.6648%7C1000&_sort=near&_count=1&_offset=1

`"HAPI-1262: org.hibernate.exception.SQLGrammarException: JDBC exception executing SQL [SELECT t1.RES_ID,(ABS((t0.SP_LATITUDE - ?)) + ABS((t0.SP_LONGITUDE - ?))) AS MHD0 FROM HFJ_RESOURCE t1 INNER JOIN HFJ_SPIDX_COORDS t0 ON (t1.RES_ID = t0.RES_ID) WHERE ((t0.HASH_IDENTITY = ?) AND (((t0.SP_LATITUDE >= ?) AND (t0.SP_LATITUDE <= ?)) AND ((t0.SP_LONGITUDE >= ?) AND (t0.SP_LONGITUDE <= ?)))) GROUP BY t1.RES_ID ORDER BY MHD0 offset ? rows fetch next ? rows only] [ERROR: column \"t0.sp_latitude\" must appear in the GROUP BY clause or be used in an aggregate function\n  Position: 24] [n/a]"`

**Expected behavior**
All resources are returned in the correct order, no exception is thrown.

**Actual behaviour**
PostgreSQL rejects the query because t0.SP_LATITUDE and t0.SP_LONGITUDE are neither included in the GROUP BY clause nor used in an aggregate function.

**Environment (please complete the following information):**
 - HAPI FHIR 7.6.0

### PR DESCRIPTION
**Pull request by patrick-werner**
This PR fixes #6709 by ensuring the computed near-sort distance column alias (`EUC_DIST*`) is added to `GROUP BY` when grouped/deduplicated SQL is generated (e.g. `_offset` searches).

Without this, PostgreSQL can reject `_sort=near` + `_offset` queries with `SQLGrammarException` due to invalid `GROUP BY` semantics.

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/sql/SearchQueryBuilder.java [hunk 1]
```diff
@@ -1000,6 +1000,17 @@ public void addSortCoordsNear(
 		String columnName = "MHD" + (myNextNearnessColumnId++);
 		mySelect.addAliasedColumn(sum, columnName);
 		mySelect.addCustomOrderings(columnName + ordering);
+		/**
+		 * Workaround for a bug in {@code com.healthmarketscience.sqlbuilder}.
```
Comment (jkiddo) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/sql/SearchQueryBuilder.java]: Can you point to the actual bug in that library? Is there an issue on it already that can be referenced?

Comment (jamesagnew) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/sql/SearchQueryBuilder.java]: Agree with this comment, and just to add: If they ever fix it in the source library, would that cause any issues and would our tests catch those issues?

Comment (patrick-werner) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/sql/SearchQueryBuilder.java]: after further investigation the cause is not a bug in the library, but in HAPI's SearchQueryBuilder. The generated SQL orders by a computed distance column (MHD0) that references SP_LATITUDE and SP_LONGITUDE, but only groups by RES_ID. PostgreSQL requires all non-aggregated columns in SELECT to appear in GROUP BY. It's not the responsibility of com.healthmarketscience.sqlbuilder to validate SQL semantics—it's a building tool, not a validator.

@jamesagnew ready to be merged now

**Comment by jamesagnew** [comment]
@patrick-werner This looks good to me - I've added a test that verifies across database types.

Curiously, this test already passed for me without your fix. I'm wondering if this is a postgres version thing, or if my test is missing some nuance. Any thoughts?

**Comment by patrick-werner** [comment]
> @patrick-werner This looks good to me - I've added a test that verifies across database types.
> 
> Curiously, this test already passed for me without your fix. I'm wondering if this is a postgres version thing, or if my test is missing some nuance. Any thoughts?

@jamesagnew i've adapted your test to show the issue. You missed to add `_count` and `&_offset` to your test. I've added both, now the test is failing as expected without the fix with psql and MsSQL:
image

**Review by jamesagnew — APPROVED** [review]
Amazing, thanks for doing that.
