### PR TITLE
Fix transaction conditional URL prefetch on non-token params

### LINKED ISSUE #6815: HAPI-0550: could not execute batch [Unique index or primary key violation: \"PUBLIC.PRIMARY_KEY_38 ON PUBLIC.HFJ_RES_SEARCH_URL(RES_SEARCH_URL, PARTITION_ID)
hapi-fhir-jpaserver-starter. HAPI FHIR 8.0 and previous versions. 
First POST of transaction bundle works fine.
POSTing the same transaction bundle with conditional PUTs a second time, we get the following error:
`"HAPI-0550: could not execute batch [Unique index or primary key violation: \"PUBLIC.PRIMARY_KEY_38 ON PUBLIC.HFJ_RES_SEARCH_URL(RES_SEARCH_URL, PARTITION_ID) VALUES ( /* key:4 */ 'Location?name=loc1', -1)\"; SQL statement:\ninsert into hfj_res_search_url (created_time,partition_date,res_id,res_search_url,partition_id) values (?,?,?,?,?) [23505-232]] [insert into hfj_res_search_url (created_time,partition_date,res_id,res_search_url,partition_id) values (?,?,?,?,?)]"`

Appears to be trying to create resource Location?name=loc1 instead of updating it.

Test Bundle.

> {
	"resourceType":"Bundle",
	"id":"0ade3579-3ef8-4400-929a-291240ad2cc2",
	"type":"transaction",
	"entry":[
		{
			"fullUrl":"urn:uuid:1dcb9d69-7dfe-44c4-8438-f4d65ff6f835",
			"resource":{
				"resourceType":"Patient",
				"identifier":[
					{
						"use":"usual",
						"type":{
							"coding":[
								{
									"code":"MR",
									"display":"Medical Record Number",
									"system":"http://terminology.hl7.org/CodeSystem/v2-0203"
								}
							]
						},
						"value":"12345"
					}
                ],
				"name":[
					{
						"use":"official",
						"text":"Shira43 Olson653",
						"family":"Olson653",
						"given":[
							"Shira43"
						]
					}
				],
				"gender":"female",
				"birthDate":"1980-11-18",
				"deceasedBoolean":false,
				"address":[
					{
						"line":[
							"491 Anderson Neck Apt 28"
						],
						"city":"Dallas",
						"state":"Texas",
						"postalCode":"75231"
					}
				]
			},
			"request":{
				"method":"PUT",
				"url":"Patient?identifier=12345"
			}
		},
        		{
			"fullUrl":"urn:uuid:328b3cca-9cb4-4f90-aa69-3896995f5335",
			"resource":{
				"resourceType":"Practitioner",
				"identifier":[
					{
						"value":"306114e1"
					}
				],
				"name":[
					{
						"family":"O'Conner199",
						"given":[
							"Serita370"
						]
					}
				]
			},
			"request":{
				"method":"PUT",
				"url":"Practitioner?identifier=306114e1"
			}
		},
        		{
			"fullUrl":"urn:uuid:00ffcc8b-f0e1-4f2d-8bf7-4936b152a37b",
			"resource":{
				"resourceType":"Encounter",
				"meta":{
					"lastUpdated":"2024-09-30T18:19:22+00:00"
				},
				"identifier":[
					{
						"system":"urn:sending:fac:TEST",
						"value":"d2d3e0bb916a"
					}
				],
				"status":"unknown",
				"class":{
					"code":"AMB",
					"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode"
				},
				"subject":{
					"display":"Patient MR: 12345, Name: Shira43 Olson653",
					"reference":"urn:uuid:1dcb9d69-7dfe-44c4-8438-f4d65ff6f835"
				},
				"participant":[
					{
						"individual":{
							"reference":"urn:uuid:328b3cca-9cb4-4f90-aa69-3896995f5335",
							"display":"Participant ID: 306114e1, Name: Serita370 O'Conner199"
						},
						"type":[
							{
								"coding":[
									{
										"code":"REF",
										"display":"referrer",
										"system":"http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
									}
								]
							}
						]
					}
				],
				"location":[
					{
						"location":{
							"reference":"urn:uuid:e0a1d16a-daf1-4e00-8bcd-40d70951838a"
						}
					}
				]
			},
			"request":{
				"method":"PUT",
				"url":"Encounter?identifier=d2d3e0bb916a"
			}
		},
        		{
			"fullUrl":"urn:uuid:e0a1d16a-daf1-4e00-8bcd-40d70951838a",
			"resource":{
				"resourceType":"Location",
				"name":"loc1",
				"description":"location 1",
				"type":[
					{
						"coding":[
							{
								"system":"https://infor.com/fhircodes#locationtype",
								"code":"Facility",
								"display":"Facility",
								"userSelected":false
							}
						],
						"text":"Facility Code"
					}
				]
			},
			"request":{
				"method":"PUT",
				"url":"Location?name=loc1"
			}
		}
    ]
}

### PR DESCRIPTION
**Pull request by jamesagnew**
Fix #6815 

When performing a FHIR transaction with conditional create/update/patch/etc where the conditional URL used parameters with a SearchParameter.type value other than `token`, the system would fail with a constraint error if the resource already existed. This has been fixed.

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TransactionProcessor.java [hunk 1]
```diff
@@ -88,7 +92,7 @@
 
 public class TransactionProcessor extends BaseTransactionProcessor {
 
-	public static final Pattern SINGLE_PARAMETER_MATCH_URL_PATTERN = Pattern.compile("^[^?]+[?][a-z0-9-]+=[^&,]+$");
+	public static final Pattern MATCH_URL_PATTERN = Pattern.compile("^[^?]++[?][a-z0-9-]+=[^&,]++");
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TransactionProcessor.java:95]: interesting, i've never seen `++` before, just looked it up. pretty cool!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TransactionProcessor.java [hunk 2]
```diff
@@ -204,29 +211,95 @@ protected EntriesToProcessMap doTransactionWriteOperations(
...
+	@SuppressWarnings("rawtypes")
 	private void preFetch(
+			RequestDetails theRequestDetails,
 			TransactionDetails theTransactionDetails,
 			List<IBase> theEntries,
 			ITransactionProcessorVersionAdapter theVersionAdapter,
 			RequestPartitionId theRequestPartitionId) {
 		Set<String> foundIds = new HashSet<>();
-		List<Long> idsToPreFetch = new ArrayList<>();
+		List<JpaPid> idsToPreFetchBodiesFor = new ArrayList<>();
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TransactionProcessor.java:222]: nitpick: could this also be a hashset? probably too much of a refactor

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/MatchResourceUrlService.java [hunk 3]
```diff
@@ -139,6 +139,23 @@ public <R extends IBaseResource> Set<T> processMatchUrl(
 			retVal = search(paramMap, theResourceType, theRequest, theConditionalOperationTargetOrNull);
 		}
 
+		if (!myStorageSettings.isMassIngestionMode() && !myStorageSettings.isMatchUrlCacheEnabled()) {
+			retVal = invokePreShowInterceptorForMatchUrlResults(theResourceType, theRequest, retVal, matchUrl);
+		}
```
Comment (tadgh) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/MatchResourceUrlService.java:144]: question: is this right? if match url caching is _disabled_ then we want to reach out to the preshow? interceptor? and if cache is enabled, we always just want to skip it

**Review by tadgh — APPROVED** [review]
Looks good so far!

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TransactionProcessor.java (hunk 1 above)
Comment (jamesagnew) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TransactionProcessor.java:95]: @tadgh I hadn't either. Oddly enough Sonarqube was complaining about the original regex that was here because of this: https://rules.sonarsource.com/java/tag/regex/RSPEC-5998/

Adding the greedy qualifier made it happy, and certainly meets the needs here.

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TransactionProcessor.java (hunk 2 above)
Comment (jamesagnew) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/TransactionProcessor.java:222]: Yeah I guess you're right. That'll probably give less surprise factor for future devs too

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/MatchResourceUrlService.java (hunk 3 above)
Comment (jamesagnew) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/dao/MatchResourceUrlService.java:144]: It is right yeah. The idea being that if you enable the match URL cache, then we're optimizing out a bunch of additional checks, such as the interceptor calls. I'll add a javadoc explaining.

**Comment by robogary** [comment]
Formatting check succeeded!
