### PR TITLE
Fixing ValueSet expansion not supporting canonical url.

### LINKED ISSUE #3515: Supporting expansion of ValueSet include/exclude system URI expressed in canonical format during validation
**Describe the bug**
Validation of a code against a ValueSet with an including where the system uri is expressed in canonical format fails.

**To Reproduce**
1. Create a ValueSet including a CodeSystem
2. Create a CodeableConcept.code with uri expressed in a canonical format
3. Validated the code against the ValueSet.
4. Validation will fail.

**Expected behavior**
Validation succeeds.

### PR DESCRIPTION
**Pull request by epeartree**
Fixing issue where `code` validation would fail when the` system` identifying the code is represented in canonical format.

- Adding constructions to detect and parse canonical codeSystem url.

closes #3515

### CODE REVIEW

File: hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupportTest.java [hunk 1]
```diff
@@ -423,8 +423,45 @@ public void testExpandValueSet_VsUsesVersionedSystem_CsIsCompleteWithCode() {
...
+
+		 String theCodeToValidateCodeSystemUrl = pipedCodeSystemUrl;
+		 String theCodeToValidate = codeMD;
+
+		 IValidationSupport.CodeValidationResult codeValidationResult = mySvc.validateCodeInValueSet(
+			 valCtx,
+			 options,
+			 theCodeToValidateCodeSystemUrl,
+			 theCodeToValidate,
+			 "dontCare",
```
Comment (jdar8) [inline hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupportTest.java:457]:
```suggestion
			 null,
```
i noticed the other tests used `null`, would `null` be better?

File: hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupport.java [hunk 2]
```diff
@@ -554,15 +559,24 @@ private boolean expandValueSetR5IncludeOrExclude(ValidationSupportContext theVal
...
 		CodeSystem includeOrExcludeSystemResource = null;
+
 		if (isNotBlank(includeOrExcludeConceptSystemUrl)) {
 
+			if( includeOrExcludeConceptSystemUrl.contains(PIPE_CHARACTER) ){
+				if(isBlank(includeOrExcludeConceptSystemVersion)){
+					includeOrExcludeConceptSystemVersion = substringAfter(includeOrExcludeConceptSystemUrl, PIPE_CHARACTER);
+				}
+				includeOrExcludeConceptSystemUrl = substringBefore(includeOrExcludeConceptSystemUrl, PIPE_CHARACTER);
+			}
```
Comment (tadgh) [inline hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupport.java:578]: Suggestion: move this nested arrow code into a helper method called `optionallPopulateVersionFromUrl()`

File: hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupport.java [hunk 3]
```diff
@@ -542,10 +544,13 @@ private void expandValueSetR5IncludeOrExcludes(ValidationSupportContext theValid
 	 * Returns <code>true</code> if at least one code was addded
```
[the remark this answers is not in the document]
Comment (epeartree) [reply hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupport.java:544]: i can change that for sure.

File: hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupportTest.java (hunk 1 above)
Comment (epeartree) [reply hapi-fhir-validation/src/test/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupportTest.java:457]: In this case, it would not matter and i can change it for consistency.  But as a general rule, passing a NULL value implies that the implementer of the functionality assumes that the parameter can be NULL and will code accordingly.  In such case, I would expect an @Nullable annotation on the parameter or have it wrapped in an Optional<T>.  That is not the case here so as a rule of thumb, i always provide a filler value since i assume that the inner working of the method will dereference the point without asserting that it is non-null.
