### PR TITLE
4098 Resultset missing resources when querying with _sort result parameter

### LINKED ISSUE #4098: _sort omits resources that lack the sorted parameter
Steps to reproduce: 
1. Create a male patient
2. Create a female patient
3. Create a patient with no gender attribute. 
4. Execute a search: `Patient?_sort=gender`

**Expected results:**
3 patients are returned. 

**Actual results:**
only the two patients with genders assigned are returned.

### PR DESCRIPTION
**Pull request by tadgh**
Resources for which searchable fields where not populated are dropped from resultset when sorting is requested on missing fields.

What was done:
- Modification of the implementation to move the hashIdentity condition from the where clause to the 'on' condition of the 'left join' used for sorting (see SQL queries in comments below).
- Adding a test for '_sort' chaining;
- Adding changelog;

Closes #4098

### CODE REVIEW

**Comment by epeartree** [comment]
Generated SQL before the fix.
```
SELECT
        t0.RES_ID 
    FROM
        HFJ_RESOURCE t0 
    LEFT OUTER JOIN
        HFJ_SPIDX_TOKEN t1 
            ON (
                t0.RES_ID = t1.RES_ID
                             
            ) 
    WHERE
        (
            (
                t0.RES_TYPE = 'Patient'
            ) 
            AND (
                t0.RES_DELETED_AT IS NULL
            )
            AND (
                t1.HASH_IDENTITY = '2817066266609047850'
            )
        ) 
    ORDER BY
        t1.SP_SYSTEM ASC NULLS LAST,
        t1.SP_VALUE ASC NULLS LAST
```

**Comment by epeartree** [comment]
Generated SQL after the fix:
```
SELECT
        t0.RES_ID 
    FROM
        HFJ_RESOURCE t0 
    LEFT OUTER JOIN
        HFJ_SPIDX_TOKEN t1 
            ON (
                (
                    t0.RES_ID = t1.RES_ID
                ) 
                AND (
                    t1.HASH_IDENTITY = '2817066266609047850'
                )
            ) 
    WHERE
        (
            (
                t0.RES_TYPE = 'Patient'
            ) 
            AND (
                t0.RES_DELETED_AT IS NULL
            )
        ) 
    ORDER BY
        t1.SP_SYSTEM ASC NULLS LAST,
        t1.SP_VALUE ASC NULLS LAST

```

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/sql/SearchQueryBuilder.java [hunk 1]
```diff
@@ -173,14 +173,21 @@ public CoordsPredicateBuilder addCoordsPredicateBuilder(@Nullable DbColumn theSo
 	}
 
 	/**
-	 * Add and return a predicate builder (or a root query if no root query exists yet) for selecting on a DATE search parameter
+	 * Create, add and return a predicate builder (or a root query if no root query exists yet) for selecting on a DATE search parameter
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/builder/sql/SearchQueryBuilder.java:176]: ❤️ more accurate javadocs!

**Review by jamesagnew — APPROVED** [review]
