### PR TITLE
6083 clinical reasoning version bump v38

### LINKED ISSUE #6083: Clinical Reasoning Version Bump v3.8
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
Bumping clinical reasoning version to 3.8 to resolve a number of underlying bugs and enhancements

- care-gaps: measureScoring on group level breaks care-gaps validation check. https://github.com/cqframework/clinical-reasoning/issues/466
- evaluate-measure: subject-list reportType incorrectly populates subject references in contained Lists https://github.com/cqframework/clinical-reasoning/issues/484

### PR DESCRIPTION
**Pull request by Capt-Mac**
closes #6083

### CODE REVIEW

File: hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java [hunk 1]
```diff
@@ -86,10 +87,10 @@ public <T extends IBaseResource> MethodOutcome create(T theResource, Map<String,
 	public <I extends IIdType, P extends IBaseParameters> MethodOutcome patch(
 			I theId, P thePatchParameters, Map<String, String> theHeaders) {
 		var details = startWith(myRequestDetails).addHeaders(theHeaders).create();
-		// TODO: conditional url, patch type, patch body?
+		// defaulting PatchType to FHIR_PATCH_JSON as this is required for patch operation
 		return myDaoRegistry
 				.getResourceDao(theId.getResourceType())
-				.patch(theId, null, null, null, thePatchParameters, details);
+				.patch(theId, null, PatchTypeEnum.FHIR_PATCH_JSON, null, thePatchParameters, details);
```
Comment (JPercival) [inline hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java:93]: issue: can we add a test to validate that either this is fixed or ensure that we don’t have a regression?

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_0/6083-clinical-reasoning-v3-8.yaml [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+type: fix
+issue: 6083
+title: "Address care-gaps bug for handling missing improvement notation validation, and group level measure scoring definition.
+Bug fix for evaluate-measure subject-list where contained List resource was setting invalid references. Bumping to latest version
+of clinical reasoning 3.8.
```
Comment (JPercival) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_0/6083-clinical-reasoning-v3-8.yaml:6]: question: I don’t see the patch operation changes here. That is potentially breaking, no?

**Review by JPercival — CHANGES_REQUESTED** [review]

File: hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java (hunk 1 above)
Comment (Capt-Mac) [reply hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java:93]: @JPercival  we can't successfully test patch because it has a current bug in FhirPatch, but this operation completely fails without PatchType being specified, which is not an available parameter otherwise.

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_0/6083-clinical-reasoning-v3-8.yaml (hunk 2 above)
Comment (Capt-Mac) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/7_4_0/6083-clinical-reasoning-v3-8.yaml:6]: Patch operation change is not a breaking change, the previous call of patch was incomplete

**Review by JPercival — APPROVED** [review]

File: hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java [hunk 3]
```diff
@@ -86,7 +86,7 @@ public <T extends IBaseResource> MethodOutcome create(T theResource, Map<String,
 	public <I extends IIdType, P extends IBaseParameters> MethodOutcome patch(
 			I theId, P thePatchParameters, Map<String, String> theHeaders) {
 		var details = startWith(myRequestDetails).addHeaders(theHeaders).create();
-		// TODO: conditional url, patch type, patch body?
+		// TODO update FHIR patchType once FHIRPATCH bug has been fixed
```
Comment (tadgh) [inline hapi-fhir-storage-cr/src/main/java/ca/uhn/fhir/cr/repo/HapiFhirRepository.java:89]: If this is a TODO for the future and not for now, i recommend you open an issue for it so it doesnt slip through the cracks.

**Review by tadgh — APPROVED** [review]
