### PR TITLE
4968 mdm throws nonsensical error when updating resources after mdm clear

### LINKED ISSUE #4968: MDM throws nonsensical error when updating resources after $mdm-clear
**Describe the bug**
This issue requests better error handling for an invalid condition:  an $mdm-clear, no $mdm-submit, and updating existing resources.
The $mdm-clear operation "is intended to be used during the rules-tuning phase of the MDM implementation" which typically involves performing a `$mdm-clear`, tuning rules, then a `$mdm-submit`. If an update to an existing resource is performed after the `$mdm-clear`, but before the `$mdm-submit`, there will be a `NullPointerException`. 

**To Reproduce**
1. Post mdm bundle
2. Perform `$mdm-clear`
3. Post the bundle again (with some edits to make it slightly different)

**Expected behavior**
Better error handling in this edge case scenario where a resource is updated between a `$mdm-clear` and `$mdm-submit`

### PR DESCRIPTION
**Pull request by jdar8**
Closes #4968

### CODE REVIEW

File: hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java [hunk 1]
```diff
@@ -80,10 +80,15 @@ void handleMdmUpdate(IAnyResource theTargetResource, MatchedGoldenResourceCandid
 		} else {
 			//This is a new linking scenario. we have to break the existing link and link to the new Golden Resource. For now, we create duplicate.
 			//updated patient has an EID that matches to a new candidate. Link them, and set the Golden Resources possible duplicates
-			linkToNewGoldenResourceAndFlagAsDuplicate(theTargetResource, theMatchedGoldenResourceCandidate.getMatchResult(), updateContext.getExistingGoldenResource(), updateContext.getMatchedGoldenResource(), theMdmTransactionContext);
+			IAnyResource theOldGoldenResource = updateContext.getExistingGoldenResource();
+			if (theOldGoldenResource == null) {
+				ourLog.error("Old golden resource was null while updating MDM links with new golden resource. It is likely that a $mdm-clear was performed without a $mdm-submit. Link will not be updated.");
```
Comment (lukedegruchy) [inline hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java:85]: Why did you decide not to throw another Exception here?   The client will still see the NullPointerException in the logs as before, just with an extra error message before.   I see no reason to continue execution here.

**Review by lukedegruchy — CHANGES_REQUESTED** [review]

File: hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java (hunk 1 above)
Comment (jdar8) [reply hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java:85]: The NPE is thrown in `linkToNewGoldenResourceAndFlagAsDuplicate()` in the else statement, so it will not be seen by the client. I can definitely change to an exception with HAPI error code though

Comment (jdar8) [reply hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java:85]: If I add a HAPI error code, I think I will also change it to an exception, as it seems like the HAPI error codes are only used with exceptions and not with log error messages

Comment (lukedegruchy) [reply hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmEidUpdateService.java:85]: I'm suggesting that you throw an InternalErrorException in this case, with a HAPI-****, rather than to simply log an error.

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderBatchR4Test.java [hunk 2]
```diff
@@ -186,4 +196,23 @@ public void testBatchRunOnAllTypesWithInvalidCriteria(ServletRequestDetails theS
 				.or(containsString(Msg.code(488) + "Failed to parse match URL")));// Sync case
 		}
 	}
+
+	@Test
+	public void testClearAndUpdateResource_WithoutMdmSubmit_LogsError() {
```
Comment (lukedegruchy) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderBatchR4Test.java:200]: Suggestion, not crucial:  try adding the same test but with $mdm-submit and assert that the request completes without an error.

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4968-fix-MDM-throws-nonsensical-error-when-updating-resources-after-mdm-clear.yaml [hunk 3]
```diff
@@ -0,0 +1,4 @@
+---
+type: fix
+issue: 4968
+title: "Previously, when performing a `$mdm-clear` followed by an update to an existing resource without doing the required `$mdm-submit` first, a non-descriptive NullPointerException was thrown. To fix this, a more descriptive/suggestive message will be logged when this condition is detected."
```
Comment (lukedegruchy) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4968-fix-MDM-throws-nonsensical-error-when-updating-resources-after-mdm-clear.yaml:4]: Please don't forget to update the changelog with the new solution

Comment (jdar8) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/6_8_0/4968-fix-MDM-throws-nonsensical-error-when-updating-resources-after-mdm-clear.yaml]: ahh right, updated it. thanks!

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderBatchR4Test.java (hunk 2 above)
Comment (jdar8) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderBatchR4Test.java:200]: added new test with submit and ensure expected number of links are created

**Review by lukedegruchy — APPROVED** [review]

**Review by tadgh — APPROVED** [review]

**Review by michaelabuckley — APPROVED** [review]
