### PR TITLE
2491 - Fix NullPointerException when performing cascade delete

### LINKED ISSUE #2491: Cascade Delete Results In NullPointerException
When issuing a Cascade Delete, a NullPointerException is encountered when attempts are made to delete referenced Resources.

The following Stack Trace has been modified to only provide the relevant Open Source references:
```
13:30:13.634 [fhir_endpoint.fhirEndpointServer-2208] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor - Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method: java.lang.NullPointerException
	:   :   : 
ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:154)
	at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBindingWithResourceIdButNoResourceBody.invokeServer(BaseOutcomeReturningMethodBindingWithResourceIdButNoResourceBody.java:33)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1062)
	at ca.uhn.fhir.rest.server.RestfulServer.doDelete(RestfulServer.java:366)
	:   :   :
Caused by: java.lang.reflect.InvocationTargetException: null
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:245) [1 skipped]
	at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:154)
	... 106 common frames omitted
Caused by: java.lang.NullPointerException: null
	at ca.uhn.fhir.rest.server.interceptor.partition.RequestTenantPartitionInterceptor.extractPartitionIdFromRequest(RequestTenantPartitionInterceptor.java:64)
	at ca.uhn.fhir.rest.server.interceptor.partition.RequestTenantPartitionInterceptor.PartitionIdentifyRead(RequestTenantPartitionInterceptor.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService$HookInvoker.invoke(BaseInterceptorService.java:530) [1 skipped]
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService.doCallHooks(BaseInterceptorService.java:291)
	at ca.uhn.fhir.interceptor.executor.BaseInterceptorService.callHooksAndReturnObject(BaseInterceptorService.java:260)
	at ca.uhn.fhir.jpa.util.JpaInterceptorBroadcaster.doCallHooksAndReturnObject(JpaInterceptorBroadcaster.java:62)
	at ca.uhn.fhir.jpa.partition.RequestPartitionHelperSvc.determineReadPartitionForRequest(RequestPartitionHelperSvc.java:109)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.readEntity(BaseHapiFhirResourceDao.java:1145)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.readEntity(BaseHapiFhirResourceDao.java:1131)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.doRead(BaseHapiFhirResourceDao.java:1088)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.lambda$read$9(BaseHapiFhirResourceDao.java:1074)
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:65) [1 skipped]
	at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:56)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.read(BaseHapiFhirResourceDao.java:1074)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.read(BaseHapiFhirResourceDao.java:1067)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.read(BaseHapiFhirResourceDao.java:1062)
	... 111 common frames omitted
```

### PR DESCRIPTION
**Pull request by KevinDougan-SmileCDR**
Closes #2491

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/interceptor/CascadingDeleteInterceptorTest.java [hunk 1]
```diff
@@ -21,14 +26,18 @@
 import org.hl7.fhir.r4.model.Reference;
 import org.junit.jupiter.api.AfterEach;
 import org.junit.jupiter.api.Test;
+import org.mockito.ArgumentCaptor;
 import org.springframework.beans.factory.annotation.Autowired;
+import org.testcontainers.shaded.org.bouncycastle.cert.ocsp.Req;
```
Comment (jamesagnew) [inline hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/interceptor/CascadingDeleteInterceptorTest.java:31]: Was this import added in error?

**Review by jamesagnew — APPROVED** [review]
