### PR TITLE
Issue 2883 unable to load open api docs

### LINKED ISSUE #2883: Unable to load OpenAPI docs
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
Getting an error when trying to load OpenAPI docs on FHIR endpoint.

**Expected behavior**
OpenAPI docs should load properly.

### PR DESCRIPTION
**Pull request by katiesmilecdr**
Closes #2883 

Implementation URLs that end with trailing slashes cause problems with openAPI page loading as we end up adding a double slash. This ends up causing subsequent failed calls.

### CODE REVIEW

File: hapi-fhir-server-openapi/src/main/java/ca/uhn/fhir/rest/openapi/OpenApiInterceptor.java [hunk 1]
```diff
@@ -267,10 +267,17 @@ protected boolean handleResourceRequest(HttpServletResponse theResponse, Servlet
 		return false;
 	}
 
+	public String removeTrailingSlash(String theUrl) {
+		while(theUrl.endsWith("/")) {
+			theUrl = theUrl.substring(0, theUrl.length() - 1);
+		}
+		return theUrl;
```
Comment (tadgh) [inline hapi-fhir-server-openapi/src/main/java/ca/uhn/fhir/rest/openapi/OpenApiInterceptor.java:274]: Can we add a null check in here in case theUrl is null? This will NPE if it is. e.g. `while(theUrl != null && theUrl.endsWith....)`

File: hapi-fhir-server-openapi/src/main/java/ca/uhn/fhir/rest/openapi/OpenApiInterceptor.java [hunk 2]
```diff
@@ -281,9 +288,9 @@ private void serveSwaggerUiHtml(ServletRequestDetails theRequestDetails, HttpSer
 		context.setVariable("DESCRIPTION", cs.getImplementation().getDescription());
 		context.setVariable("SERVER_NAME", cs.getSoftware().getName());
 		context.setVariable("SERVER_VERSION", cs.getSoftware().getVersion());
-		context.setVariable("BASE_URL", cs.getImplementation().getUrl());
+		context.setVariable("BASE_URL", baseUrl);
```
Comment (tadgh) [inline hapi-fhir-server-openapi/src/main/java/ca/uhn/fhir/rest/openapi/OpenApiInterceptor.java:291]: Are you sure you also want to use the slash-removed version here? I would revert this part, as it is not part of the relevant fix, and some downstream clients may rely on a trailing slash.

**Review by tadgh — CHANGES_REQUESTED** [review]
Overall implementation looks good! 

Minor changes requested. Also, needs a changelog associated.

**Review by tadgh — APPROVED** [review]
Nice!
