### PR TITLE
7384 mdm expansion search impacts the search operation with conditional references

### LINKED ISSUE #7384: MDM Expansion Search impacts the Search operation with conditional references
### Problem Statement 
Search operation with conditional referencing is not working after enabling MDM expansion search.

### Description
When MDM expansion search is enabled, search operations of other resource types are failing.
Example: http://localhost:8000/AllergyIntolerance?patient.identifier=https://test.ca/fhir/NamingSystem/hw-1222%7Cpaaaid1102101

This worked fine before enabling the MDM expansion search. but doesn't work after enabling it. Below is the error message
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-2001: Resource NamingSystem/hw-1222|paaaid1102101 is not known"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by YalingPeiS**
### Problem Statement 
Search operation with chained referencing is not working after enabling MDM expansion search.

### Description
When MDM expansion search is enabled, search operations with chained reference are failing.
Example: http://localhost:8000/AllergyIntolerance?patient.identifier=https://test.com/fhir/NamingSystem/hw-1222%7Cpaaaid1102101

This worked fine before enabling the MDM expansion search. but doesn't work after enabling it. Below is the error message
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-2001: Resource NamingSystem/hw-1222|paaaid1102101 is not known"
        }
    ]
}
```
### Cause
It is noticed that the existing MDM expansion on chained or conditional reference search behaved differently for the user with FHIR_AUTO_MDM permission and the user without this permission.

* When the user (e.g. admin) has FHIR_AUTO_MDM, conditional reference search failed with 404 resource not known error as described in the ticket due to search param parsing error.
* When the user does not have FHIR_AUTO_MDM, conditional reference search would succeed with 200 response. However, the search did not perform MDM-expansion at all.

### Fix
A 400 bad request error will be thrown if MDM expansion is attempted on a chain.

Closes #7384

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-base/src/test/java/ca/uhn/fhir/rest/param/ReferenceParamTest.java [hunk 1]
```diff
@@ -34,4 +36,13 @@ void testEqualsAndHashCode(String theToken0Qualifier, String theToken0Value, Str
...
 
+	@Test
+	void testChainedParamWithMdmExpand() {
+		ReferenceParam param = new ReferenceParam();
+		param.setValueAsQueryToken(null, "patient", ".name:mdm", "Smith");
+
+		assertThat(param.isMdmExpand()).isTrue();
+		assertThat(param.getChain()).isEqualTo("name");
+		assertThat(param.getValue()).isEqualTo("Smith");
+	}
```
Comment (tadgh) [inline hapi-fhir-base/src/test/java/ca/uhn/fhir/rest/param/ReferenceParamTest.java:47]: Nice clean test!

**Review by tadgh — APPROVED** [review]
