### PR TITLE
Fix JSON Patch add on empty repeating elements (#7578)

### LINKED ISSUE #7578: Fhirpath processing issue during JSON Patch operation
Scenario:

We are creating Group Resource for Provider Access API. Initially the Group resource will not have any Member. When a Member Opt-In, we are adding the Member to the Group Resource. This scenario was working till last month but now we are not able to add a Member to a Group which do not have any existing Member.

- This is NOT working when the Group DO NOT have any Member
- This is working if the Group has existing Member

Empty group: 
```
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
        "resource":{
          "resourceType" : "Group",
          "id" : "some-id2",
          "meta" : {
            "profile":"http://hl7.org/fhir/us/davinci-pdex/StructureDefinition/pdex-provider-group"
          },
          "extension" : [{
            "url" : "http://hl7.org/fhir/us/davinci-atr/StructureDefinition/ext-contractValidityPeriod",
            "valuePeriod" : {
              "start" : "2025-01-01",
              "end" : "2025-12-31"
            }
          },
          {
            "url" : "http://hl7.org/fhir/us/davinci-atr/StructureDefinition/ext-attributionListStatus",
            "valueCode" : "draft"
          }],
          "identifier" : [{
            "use" : "official",
            "type" : {
              "coding" : [{
                "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
                "code" : "NPI",
                "display" : "National Provider Identifier"
              }]
            },
            "system" : "http://hl7.org/fhir/sid/us-npi",
            "value" : "1851454001"
          },
          {
            "use" : "official",
            "type" : {
              "coding" : [{
                "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
                "code" : "TAX",
                "display" : "Tax ID Number"
              }]
            },
            "system" : "urn:oid:2.16.840.1.113883.4.4",
            "value" : "942728481"
          }
          ],
          "active" : true,
          "type" : "person",
          "actual" : true,
          "name" : "TPMG RICHMOND - INDEPENDENT LAB 1",
          "managingEntity" : {
            "reference" : "Organization/some-id1,
            "display" : "Healthcare related organization"
          }
        },
          "request": {
            "method": "PUT",
            "url": "Group/some-id2"
          }
        }
  ]
}
```

and the patch operation: 

```
[
 { 
   "op": "add", 
   "path": "/member/0", 
   "value": {
            "extension" : [{
              "url" : "http://hl7.org/fhir/us/davinci-atr/StructureDefinition/ext-changeType",
              "valueCode" : "add"
            },
            {
              "url" : "http://hl7.org/fhir/us/davinci-atr/StructureDefinition/ext-coverageReference",
              "valueReference" : {
                "reference" : "Coverage/some-other-id"
              }
            },
            {
              "url" : "http://hl7.org/fhir/us/davinci-atr/StructureDefinition/ext-attributedProvider",
              "valueReference" : {
                "reference" : "Organization/some-id3"
              }
            }],
            "entity" : {
              "reference" : "Patient/some-patient"
            },
            "period" : {
              "start" : "2025-01-01"
            },
            "inactive" : false
          }
 }
]
```

and the error: 

```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-1272: parent of node to add does not exist"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by tadgh**
Fixes #7578

## Summary

JSON Patch (RFC 6902) "add" operations fail with HAPI-1272 when targeting a repeating FHIR element that has no existing entries, because HAPI's JSON serializer omits empty arrays entirely, leaving the parent path unresolvable. This fix pre-populates missing parent arrays in the serialized JSON document before applying the patch, so that paths like `/member/0` or `/member/-` resolve correctly even when the resource has never had values in that field.

1. Added `ensureParentArraysExist()` to `JsonPatchUtils` that inspects each "add" operation in the patch, detects paths targeting array elements (numeric index or `-` append), and inserts an empty JSON array for the parent field if it is absent from the serialized document.
2. Added two unit tests covering the primary scenario (adding a member to an empty Group at `/member/0`) and the append-path variant (`/member/-`), as well as unit tests which do this via a transaction bundle, and via the endpoint. 

Coauthored by Claude Opus 4.6

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/PatchProviderR4Test.java [hunk 1]
```diff
@@ -957,4 +958,96 @@ public void testPatchInTransaction_InvalidContentType_Fhir() throws Exception {
...
+
+		// Create a Group with no members
+		Group group = new Group();
+		group.setType(Group.GroupType.PERSON);
+		group.setActual(true);
+		group.setActive(true);
+		IIdType groupId = myClient.create().resource(group).execute().getId().toUnqualifiedVersionless();
+
+		// JSON Patch: add a member at /member/0
+		String patchText = "[{\"op\":\"add\",\"path\":\"/member/0\",\"value\":{\"entity\":{\"reference\":\"" + patientId.getValue() + "\"},\"inactive\":false}}]";
```
Comment (fil512) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/PatchProviderR4Test.java:983]: nitpick: use """ for readability

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/PatchProviderR4Test.java [hunk 2]
```diff
@@ -957,4 +958,96 @@ public void testPatchInTransaction_InvalidContentType_Fhir() throws Exception {
...
+
+		// Create a Group with no members
+		Group group = new Group();
+		group.setType(Group.GroupType.PERSON);
+		group.setActual(true);
+		group.setActive(true);
+		IIdType groupId = myClient.create().resource(group).execute().getId().toUnqualifiedVersionless();
+
+		// JSON Patch body as a Binary resource in a transaction bundle
+		String patchText = "[{\"op\":\"add\",\"path\":\"/member/0\",\"value\":{\"entity\":{\"reference\":\"" + patientId.getValue() + "\"},\"inactive\":false}}]";
```
Comment (fil512) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/PatchProviderR4Test.java:1024]: nitpick: use """ for readability

**Review by fil512 — APPROVED** [review]
