### PR TITLE
[7530] FHIR Patch replace operations with extension in the path failed with error

### LINKED ISSUE #7530: Conditional reference in the FHIRPath of a Transaction Patch request is not being resolved
### Issue: 
Conditional reference in the FHIRPath of a Transaction Patch request is not being resolved.

The Post patch operation with the following request body fails with error

```
{
    "resourceType": "Bundle",
    "type": "transaction",
    "identifier": {
        "system": "https://test.com/fhir/NamingSystem/hw/bundle/identifier",
        "value": "16bfacf5-fbd0-4d84-b96e-d1774bec5a19"
    },
    "timestamp": "2026-01-26T10:02:00Z",
    "entry": [
        {
            "fullUrl": "urn:uuid:5c68e283-908c-4e51-90aa-074ebc6db001",
            "resource": {
                "resourceType": "Parameters",
                "parameter": [
                    {
                        "name": "operation",
                        "part": [
                            {
                                "name": "type",
                                "valueCode": "replace"
                            },
                            {
                                "name": "path",
                                "valueString": "EpisodeOfCare.extension('https://test.com/fhir/extensions/global/updateDate').value"
                            },
                            {
                                "name": "value",
                                "valueDateTime": "2025-04-01T22:37:44-04:00"
                            }
                        ]
                    }
                ]
            },
            "request": {
                "method": "PATCH",
                "url": "EpisodeOfCare/3beccd7e-ed61-49c5-bd0e-9fc20a29f1d6"
            }
        }
    ]
}
```

### Error:
```
HAPI-2761: No element matches the specified path: EpisodeOfCare.extension('https://test.com/fhir/extensions/global/updateDate').value
```

### PR DESCRIPTION
**Pull request by YalingPeiS**
#### Issue
FHIR Patch replace operations with extension in the path failed with error

#### Cause
Existing FHIR Patch replace operation did not set the `BaseRuntimeChildDefinition` properly for a choice type (e.g. value[x]) when parse and process the path that contains the `extension('url').value` or` extension.where(url='url').value` syntax

#### What was done
* Updated FhirPatch class to make sure BaseRuntimeChildDefinition is set properly when Fhir path using `extension('url')` or `extension.where(url='url')` syntax
* Added/updated unit tests
* Added/updated documentation

Closes #7530

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java [hunk 1]
```diff
@@ -496,15 +501,8 @@ private void replaceSingleValue(
...
 				} else {
-					if (theTargetChildDefinition.getBaseRuntimeDefinition() != null
-							&& !theTargetChildDefinition
-									.getBaseRuntimeDefinition()
-									.isMultipleCardinality()) {
-						// basic primitive type assignment
-						target.setValueAsString(source.getValueAsString());
-						return;
-					}
-
```
Comment (YalingPeiS) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java:507]: The `else` (L503) handles the case when source and target have different Fhir Types, so `setValueAsString` in the above `if` block could fail even with primitive types. E.g., source can be `DateTimeType` and target can be `BooleanType`. Remove the block to allow the target being set properly.

Comment (YalingPeiS) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java:507]: Not applicable anymore as Ken fixed it.

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/fhir_patch.md [hunk 2]
```diff
@@ -0,0 +1,166 @@
+# FHIR Patch
```
Comment (jmarchionatto) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/fhir_patch.md:1]: Great documentation!

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java [hunk 3]
```diff
@@ -743,7 +753,13 @@ private Optional<FhirPathChildDefinition> childDefinition(
 		definition.setFhirPath(head);
 
 		if (theParent.getElementDefinition() != null) {
-			definition.setBaseRuntimeDefinition(theParent.getElementDefinition().getChildByName(head));
+			BaseRuntimeChildDefinition runtimeChild =
+					theParent.getElementDefinition().getChildByName(head);
+			if (runtimeChild == null) {
+				// possibly a choice type (e.g. value[x] on Extension)
+				runtimeChild = theParent.getElementDefinition().getChildByName(head + "[x]");
```
Comment (jmarchionatto) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java:760]: What if it is still null?

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java [hunk 4]
```diff
@@ -300,6 +305,7 @@ private void handleReplaceOperation(
 			@Nullable IBaseResource theResource, @Nullable IBase theParameters, PatchOutcome theOutcome) {
 		String path = ParametersUtil.getParameterPartValueAsString(myContext, theParameters, PARAMETER_PATH);
 		path = defaultString(path);
+		path = normalizeExtensionFunctionSyntax(path);
```
Comment (jmarchionatto) [inline hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java:308]: Why is it only normalized for replace? What about add or Insert?
If there is a reason whould be good to document it

File: hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/patch/FhirPatchTest.java [hunk 5]
```diff
@@ -445,6 +448,249 @@ void testValidate() {
 			);
 	}
 
+	@Test
```
Comment (jmarchionatto) [inline hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/patch/FhirPatchTest.java:452]: Please add test for use case: old and new values are of different type

**Review by jmarchionatto — APPROVED** [review]
Looks good! Approved with a questions and an additional test request

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/fhir_patch.md (hunk 2 above)
Comment (YalingPeiS) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_jpa/fhir_patch.md:1]: Ken added it.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java (hunk 4 above)
Comment (YalingPeiS) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java:308]: It looks that `add` and `insert` input are a bit different than that of `replace`, so the path would be different. Here is the description from the current documentation.
> The **Add** operation takes a path to a parent element within a resource (or the name of the resource itself), the name of the element to add, and a value to actually add.
> The **Insert** operation takes a path to a repeatable element, an index to insert at, and a value to actually insert.
> The **Replace** operation takes a path to an element to replace, and a value to actually replace it with. The path must resolve to a single element.

File: hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java (hunk 3 above)
Comment (YalingPeiS) [reply hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/patch/FhirPatch.java:760]: If it is still null, the input path would be invalid since this `head` is not a valid child node for the element definition. An exception of no RuntimeChildDefinition will be thrown downstream.

File: hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/patch/FhirPatchTest.java (hunk 5 above)
Comment (YalingPeiS) [reply hapi-fhir-storage/src/test/java/ca/uhn/fhir/jpa/patch/FhirPatchTest.java:452]: Done
