### PR TITLE
fixed $translate operation caching

### LINKED ISSUE #7371: Remote Terminology $translate calls not being cached
The $translate operation calls are not cached, i.e. if a request is repeated twice both result in request to the remote terminology server.

### PR DESCRIPTION
**Pull request by mrdnctrk**
closes #7371

## Problem

The ConceptMap `$translate` operation caching was not working properly due to an issue with the cache key comparison. The `TranslateCodeRequest` class was using default object equality for `IBaseCoding` instances, which meant that two semantically identical codings (same system, code, and version) but different object instances were treated as different cache keys. This resulted in unnecessary cache misses.

## Solution
Implemented a `CodingEqualsAdapter` inner class in `TranslateCodeRequest` class. THis provides semantic equality comparison for `IBaseCoding` instances. The adapter compares codings based on their semantic content:
- System
- Code
- Version

The display value is intentionally excluded from the comparison as it is not semantically significant for code translation operations.

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-validation/src/test/java/ca/uhn/fhir/context/support/TranslateCodeRequestTest.java [hunk 1]
```diff
@@ -0,0 +1,189 @@
...
+import static org.junit.jupiter.api.Assertions.assertNotEquals;
+
+/**
+ * Tests for {@link ca.uhn.fhir.context.support.IValidationSupport.TranslateCodeRequest}
+ * which is used as a cacheKey for $translate operations.
+ */
+class TranslateCodeRequestTest {
+
+	@Test
+	void testEqualsImpliesHashEqual() {
```
Comment (jmarchionatto) [inline hapi-fhir-validation/src/test/java/ca/uhn/fhir/context/support/TranslateCodeRequestTest.java]: nitpick: I think you meant Involves instead of Implies

Comment (mrdnctrk) [reply hapi-fhir-validation/src/test/java/ca/uhn/fhir/context/support/TranslateCodeRequestTest.java]: thanks, updated the name.
