### PR TITLE
[7367] Fix value set not found with remote terminology service

### LINKED ISSUE #7367: Enable remote Remote Terminology Service, failed to validate resource
### Problem Statement
Enable remote Remote Terminology Service, GET $validate resource, return 404, not find value set, version is null

### PR DESCRIPTION
**Pull request by YalingPeiS**
### Problem Statement
`$validate` resource fails and returns 404 when Remote Terminology Service is enabled and its base URL is set to [https://r4.ontoserver.csiro.au/fhir/](https://r4.ontoserver.csiro.au/fhir/)

### Cause
It appears that the request sent to the remote server is https://r4.ontoserver.csiro.au/fhir/ValueSet?url=http%3A%2F%2Fhl7.org%2Ffhir%2FValueSet%2Fadministrative-gender%5C%7C4.0.1&_summary=false, where the version is added to the end of the url with a pipe ("|"). This causes the remote server not being able to process the search properly.

### Fix
Separate the code system and the version if the valueSet url contains a pipe delimited (system|version) string.

Closes #7367

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java [hunk 1]
```diff
@@ -544,9 +545,16 @@ private IBaseResource fetchValueSet(String theValueSetUrl, SummaryEnum theSummar
...
+		IQuery<IBaseBundle> valueSetQuery = client.search().forResource("ValueSet");
+
+		int pipeIdx = theValueSetUrl.indexOf("|");
+		if (pipeIdx < 0) {
+			valueSetQuery.where(CodeSystem.URL.matches().value(theValueSetUrl));
+		} else {
+			valueSetQuery.where(CodeSystem.URL.matches().value(theValueSetUrl.substring(0, pipeIdx)));
+			valueSetQuery.where(
+					new StringClientParam("version").matches().value(theValueSetUrl.substring(pipeIdx + 1)));
+		}
```
Comment (YalingPeiS) [inline hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/RemoteTerminologyServiceValidationSupport.java:557]: The fix above is to separate system and version parameters for ValueSet search. It appears that the remote terminology server [https://r4.ontoserver.csiro.au/fhir/](https://r4.ontoserver.csiro.au/fhir/) does not support ValueSet search with the parameter like `url=system|version`. It caused `$validate` resource requests failure with 404 Not Found error.

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7367-fix-validate-resource-failure-on-remote-terminology-server.yaml [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+type: fix
+issue: 7367
+title: "Previously, when the Remote Terminology Service was enabled and its base URL was set to 
+[https://r4.ontoserver.csiro.au/fhir/](https://r4.ontoserver.csiro.au/fhir/), sending a `$validate` request returned
```
Comment (jmarchionatto) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7367-fix-validate-resource-failure-on-remote-terminology-server.yaml]: I think it was only failing with some specific $validate requests. Right? If that is the case I would write "...when sending some $validate requests..."?

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java [hunk 3]
```diff
@@ -215,18 +216,14 @@ public void testValidateSimpleCode_SupportedByRemoteService_EmptyValueSet() {
 		// Verify 1
 		Assertions.assertEquals(0, myCaptureQueriesListener.countGetConnections());
 		assertThat(ourValueSetProvider.mySearchUrls).asList().containsExactlyInAnyOrder(
-			"http://hl7.org/fhir/ValueSet/administrative-gender|4.0.1",
+			"http://hl7.org/fhir/ValueSet/administrative-gender", "4.0.1",
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java:219]: This doesn't look right. "4.0.1" isn't a search request. Please explain

File: hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/validation/IValidationProvidersR4.java [hunk 4]
```diff
@@ -130,14 +135,29 @@ public IBaseParameters validateCode(
 			String code = theCode != null ? theCode.getValue() : null;
 			return getTerminologyResponse("$validate-code", url, code);
 		}
+
+		@Search
+		public List<ValueSet> find(@RequiredParam(name = "url") UriParam theUrlParam,
+								   @RequiredParam(name = "version") TokenParam theVersionParam) {
```
Comment (jmarchionatto) [inline hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/validation/IValidationProvidersR4.java]: I don;t think it is required. Or is it?

Comment (YalingPeiS) [reply hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/validation/IValidationProvidersR4.java]: It is required for the tests in `ValidateWithRemoteTerminologyTest` since remote searching of ValueCode is tested there. Without this method, the test will get
```InvalidRequest HTTP 400 Bad Request: Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[ValueSet] with parameters [[_summary, version, url]]```

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7367-fix-validate-resource-failure-on-remote-terminology-server.yaml (hunk 2 above)
Comment (YalingPeiS) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7367-fix-validate-resource-failure-on-remote-terminology-server.yaml]: Updated.

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java (hunk 3 above)
Comment (YalingPeiS) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java:219]: This assertion is for request parameters. I guess the variable was originally named `mySearchUrls` assuming it was just an URL since version was added to the URL with `|`. I've updated the variable name to `mySearchParams`.

File: hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/validation/IValidationProvidersR4.java (hunk 4 above)
Comment (jmarchionatto) [reply hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/validation/IValidationProvidersR4.java]: I meant the @RequiredParam(name = "version"). Is version really required parameter?

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java (hunk 3 above)
Comment (jmarchionatto) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java:219]: I read it is for urls: assertThat(ourValueSetProvider.mySearchUrls).asList()

Comment (YalingPeiS) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java:219]: Since this is testing Remote Terminology server, for the test, the  request is
GET http://localhost:61876/ValueSet?url=http%3A%2F%2Fhl7.org%2Ffhir%2FValueSet%2Fadministrative-gender&version=4.0.1&_summary=false
where `http://hl7.org/fhir/ValueSet/administrative-gender` and `4.0.1` are both parameters (after /ValueSet?), not the request base url. 
Line 479-484 shows how this variable is populated.

File: hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/validation/IValidationProvidersR4.java (hunk 4 above)
Comment (YalingPeiS) [reply hapi-fhir-test-utilities/src/main/java/ca/uhn/fhir/test/utilities/validation/IValidationProvidersR4.java]: Ah, got it. Updated to OptionalParam.

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java (hunk 3 above)
Comment (jmarchionatto) [reply hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/interceptor/RemoteTerminologyServiceJpaR4Test.java:219]: Ahh. Right.

**Review by jmarchionatto — APPROVED** [review]
