### PR TITLE
PackageInstallerSvcImpl Says R4 is NOT Compatible with R4B

### LINKED ISSUE #4395: PackageInstallerSvcImpl Says R4 is NOT Compatible with R4B
**Describe the bug**
The `PackageInstallerSvcImpl` says that FHIR version 4.0.1 (R4) is **NOT** compatible with FHIR version 4.3.0 (R4B).

**To Reproduce**
1. Run `hapi-fhir-jpaserver-starter` Integration Test Class `ExampleServerR4BIT`
2. Notice that it attempts to STORE_AND_INSTALL a Package for `hl7.fhir.dk.core` **v1.1.0**
3. When it checks the current FHIR version (**4.3.0**) against the FHIR version for the package (**4.0.1**) and converts them to ENUM values as **R4B** and **R4** respectively, it determines that they are NOT compatible
4. An Exception is thrown: "ca.uhn.fhir.jpa.packages.ImplementationGuideInstallationException: HAPI-1288: Cannot install implementation guide: FHIR versions mismatch (expected <=4.3.0, package uses 4.0.1)"

**Expected behavior**
The **4.0.1 (R4)** FHIR version from the package should be accepted as being compatible with runtime FHIR version **4.3.0 (R4B)**.

**Screenshots**
image

**Environment (please complete the following information):**
 - HAPI FHIR Version **6.2.2**
 - HAPI-FHIR-JPASERVER-STARTER Version **master Branch**

### PR DESCRIPTION
**Pull request by KevinDougan-SmileCDR**
Closes #4395

### CODE REVIEW

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java [hunk 1]
```diff
@@ -285,14 +285,17 @@ private void fetchAndInstallDependencies(NpmPackage npmPackage, PackageInstallat
...
 		throws ImplementationGuideInstallationException {
 
 		FhirVersionEnum fhirVersionEnum = FhirVersionEnum.forVersionString(fhirVersion);
 		FhirVersionEnum currentFhirVersionEnum = FhirVersionEnum.forVersionString(currentFhirVersion);
 		Validate.notNull(fhirVersionEnum, "Invalid FHIR version string: %s", fhirVersion);
 		Validate.notNull(currentFhirVersionEnum, "Invalid FHIR version string: %s", currentFhirVersion);
 		boolean compatible = fhirVersionEnum.equals(currentFhirVersionEnum);
+		if (!compatible && fhirVersion.startsWith("R4") && currentFhirVersion.startsWith("R4")) {
+			compatible = true;
+		}
```
Comment (tadgh) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java:298]: issue: this requires a changelog

**Review by tadgh — CHANGES_REQUESTED** [review]
Approved pending the addition of a changelog

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java (hunk 1 above)
Comment (KevinDougan-SmileCDR) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java:298]: Changelog added.

**Review by tadgh — APPROVED** [review]
