### PR TITLE
fixing issue with infinite cache refresh loop

### LINKED ISSUE #6044: Refreshing a cache when doing a search using Advanced Hibernate Search results in an infinite loop
Enable advanced hibernate cache and try and refresh the cache.

This will trigger a search for all StructureDefinitions which will check the cache, which results in a cache refresh which checks the cache which results in a cache refresh which...

### PR DESCRIPTION
**Pull request by TipzCM**
closes #6044

### CODE REVIEW

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/registry/SearchParamRegistryImpl.java [hunk 1]
```diff
@@ -432,9 +438,15 @@ public void handleInit(Collection<IIdType> theResourceIds) {
 		initializeActiveSearchParams(searchParams);
 	}
 
+	@Override
+	public boolean isInitialized() {
+		return myIsInitialized;
```
Comment (fil512) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/registry/SearchParamRegistryImpl.java:443]: rather than using a new field, can we just return `theSearchParams != null` ?

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java [hunk 2]
```diff
@@ -151,6 +151,15 @@ public boolean canUseHibernateSearch(String theResourceType, SearchParameterMap
 			return true;
 		}
 
+		// if the registry has not been initialized
+		// we cannot use HibernateSearch because it
+		// will, internally, trigger a new search
+		// when it refreshes the search parameters
+		// (which will cause an infinite loop)
+		if (!mySearchParamRegistry.isInitialized()) {
+			return false;
```
Comment (fil512) [inline hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java:160]: is is possible for the fhir endpoint to be up before the sp registry is initialized? Guesing "no". But if "yes" then there is a risk of a silent ommission. if isInitialized() is always true by the time the app context has been refreshed, then I have no concern.

File: hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/cache/ResourceChangeListenerRegistryImplIT.java [hunk 3]
```diff
@@ -55,6 +64,61 @@ public void after() {
...
+
+		assertTrue((cache instanceof ResourceChangeListenerCache));
+
+		// set the HSearchIndexing
+		boolean useAdvancedHSearch = myStorageSettings.isAdvancedHSearchIndexing();
+		myStorageSettings.setAdvancedHSearchIndexing(true);
+
+		// so they will be forced to be refreshed
+		mySearchParamRegistry.setActiveSearchParams(null);
+		try (MockedStatic<CacheConstants> cacheConstants = mockStatic(CacheConstants.class)) {
```
Comment (fil512) [inline hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/cache/ResourceChangeListenerRegistryImplIT.java:99]: interesting!

**Review by fil512 — APPROVED** [review]

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/registry/SearchParamRegistryImpl.java (hunk 1 above)
Comment (TipzCM) [reply hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/registry/SearchParamRegistryImpl.java:443]: updated

File: hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java (hunk 2 above)
Comment (TipzCM) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java:160]: seems to be.

I've verified with some manual testing and an automated test i won't be checking in.

Comment (michaelabuckley) [reply hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FulltextSearchSvcImpl.java:160]: I definitely see the registry initialized during startup.  I can't find the actual even because it's in some loop with the change listener and the startup sequence.

File: hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/CacheConstants.java [hunk 4]
```diff
@@ -0,0 +1,14 @@
+package ca.uhn.fhir.jpa;
+
+public class CacheConstants {
```
Comment (michaelabuckley) [inline hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/CacheConstants.java:3]: minor: This feels excessive.  Why extract a whole new class when it is used in only one place?

**Review by michaelabuckley — APPROVED** [review]
Looks like a clean snip of a loop.
