### PR TITLE
Fix bug with inconsistent error messages

### LINKED ISSUE #2496: invalid date format error behaves differently if we are using a builtin SP or a custom SP
Executing the following search
```http
http://localhost:8000/ExplanationOfBenefit?created=01-01-2020
```
Correctly returns a 400 with message
```json
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Invalid date/time format: \"01-02-2020\""
    }
  ]
}
```

However, if a user creates a custom search parameter (Say, the Carin-BB [service-date](https://build.fhir.org/ig/HL7/carin-bb/SearchParameter-explanationofbenefit-service-date.json.html) parameter, and then executes a search against it, a 500 is returned. 

```http
http://localhost:8000/ExplanationOfBenefit?service-date=01-01-2020
```

incorrectly returns a 500 with message
```json
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: \"01-01-2020\""
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by tadgh**
* If we catch a DataFormatException during server invocation, rethrow that instead of InternalErrorException.
* This will allow us to cleanly bubble up 400 errors to clients calling custom search parameters with invalid formats. 

Closes #2496

### CODE REVIEW

**Review by KevinDougan-SmileCDR — APPROVED** [review]

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderCustomSearchParamR4Test.java [hunk 1]
```diff
@@ -416,6 +420,59 @@ public void testSearchWithCustomParam() {
...
+		//Try with builtin SP
+		try {
+			myClient
+				.search()
+				.forResource(ExplanationOfBenefit.class)
+				.where(new StringClientParam("created").matches().value("01-01-2020"))
+				.returnBundle(Bundle.class)
+				.execute();
+
+		} catch	(Exception e) {
```
Comment (patrick-vachon-smilecdr) [inline hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderCustomSearchParamR4Test.java:458]: Should it catch the expected exception here, DataFormatException?

And fails on other exception types?

Comment (tadgh) [reply hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderCustomSearchParamR4Test.java:458]: I think this is safe, as we are asserting on the actual message. Already merged this, but next time I'm in the code, I'll change it 👍🏻
