### PR TITLE
[7332] Fix $mdm-query-links in partition mode

### LINKED ISSUE #7332: If enable database_partition_mode, GET $mdm-query-links, response Requested resource not found
If enable database_partition_mode setting, create Patient, mdm generate golden resource, GET /Partition-A/$mdm-query-links, response Requested resource not found when the resources exist in database.

### PR DESCRIPTION
**Pull request by YalingPeiS**
If enable database_partition_mode setting, create Patient, mdm generate golden resource, GET /Partition-A/$mdm-query-links, response showed `Requested resource not found` when the resources exist in database.

### Cause
Looks like we added partitionId to the primary key in the resource table last year, but the query for MDM linked resources does not contain the partitionId, resulting in empty result set.

Closes #7332

### CODE REVIEW

**Comment by robogary** [comment]
Formatting check succeeded!

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java [hunk 1]
```diff
@@ -88,4 +96,65 @@ public void testCreateLinkWithResourcesInSpecificPartition(){
 
 		assertTrue(MdmResourceUtil.isGoldenRecord(searchResult.getAllResources().get(0)));
 	}
+
+	@Test
+	void testQueryMdmLink_goldenResourceInSamePartition() {
+		myMdmSettings.setSearchAllPartitionForMatch(false);
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java]: New test seem to only defer in parameters. Would it be better to have a single param. test?

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java [hunk 2]
```diff
@@ -88,4 +96,65 @@ public void testCreateLinkWithResourcesInSpecificPartition(){
...
+			new UnsignedIntType(10), new StringType(), myRequestDetails, new StringType("Patient"));
+
+		assertThat(result.getParameter()).hasSize(3);
+		assertThat(result.getParameter().get(0).getName()).isEqualTo("self");
+		assertThat(result.getParameter().get(1).getName()).isEqualTo("total");
+		assertThat(((DecimalType)(result.getParameter().get(1).getValue())).getValueAsInteger()).isEqualTo(1);
+		assertThat(result.getParameter().get(2).getName()).isEqualTo("link");
+		assertThat(result.getParameter().get(2).getPart()).hasSize(9);
+
+		myInterceptorRegistry.unregisterInterceptor(interceptor);
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java]: The practice is to unregister in finally block or afterEach

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java [hunk 3]
```diff
@@ -88,4 +96,65 @@ public void testCreateLinkWithResourcesInSpecificPartition(){
...
+
+		Parameters result = (Parameters) myMdmProvider.queryLinks(null, null, null, null, new UnsignedIntType(0),
+			new UnsignedIntType(10), new StringType(), myRequestDetails, new StringType("Patient"));
+
+		assertThat(result.getParameter()).hasSize(3);
+		assertThat(result.getParameter().get(0).getName()).isEqualTo("self");
+		assertThat(result.getParameter().get(1).getName()).isEqualTo("total");
+		assertThat(((DecimalType)(result.getParameter().get(1).getValue())).getValueAsInteger()).isEqualTo(1);
+		assertThat(result.getParameter().get(2).getName()).isEqualTo("link");
+		assertThat(result.getParameter().get(2).getPart()).hasSize(9);
```
Comment (jmarchionatto) [inline hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java]: Is 9 good because of he 9 parameters? Please add comment indicating why 9 is good.

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java (hunk 2 above)
Comment (YalingPeiS) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java]: Moved the interceptor to the class level so it can be unregistered in afterEach.

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java (hunk 3 above)
Comment (YalingPeiS) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java]: Updated to check the part list not empty to make it more generic

File: hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java (hunk 1 above)
Comment (YalingPeiS) [reply hapi-fhir-jpaserver-mdm/src/test/java/ca/uhn/fhir/jpa/mdm/provider/MdmProviderCrossPartitionR4Test.java]: Updated to parameterized test.

File: hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7332-fix-query-mdm-links-not-return-resources.yaml [hunk 4]
```diff
@@ -0,0 +1,6 @@
+---
+type: fix
+issue: 7332
+title: "In partition mode, the FHIR endpoint GET `$mdm-query-links` and the admin JSON endpoint GET 
+'{module_id}/query-link` returned a 404 Not Found error when source and golden resources existed in the partition.
```
Comment (tadgh) [inline hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7332-fix-query-mdm-links-not-return-resources.yaml]: issue: remove reference to {module_id}/query-link. That is not part of this product.

Comment (YalingPeiS) [reply hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/8_6_0/7332-fix-query-mdm-links-not-return-resources.yaml]: Done.
